### ISSUE TITLE
failed to send message

### ISSUE THREAD

**Issue by mx4** [WhisperSystems/TextSecure#1398] opened 2014-04-20 08:59 UTC
This might be an existing issue, please close as dupe if that's the case.

My phone: Nexus 4 up to date with latest TS.
Son's phone: Wiko Ozzy running 4.2.2 with latest TS.

The problem:
 - my son's phone can see that my phone & number are registered with TS's servers, yet when he tries to send me a message, I never receive it.
 - when I try to send a message to my son, TS doesn't see him as being registered: he's not listed under "Textsecure Users". So he does get my message but that message is sent as an SMS.

Everything works fine with WhatsApp.

We tried to "refresh push directory" on both phones, but that didn't help. Thoughts?

**Comment by rhodey** [comment] 2015-03-16 18:52
since this issue was reported support for encrypted SMS/MMS has been dropped, websockets are now used in the client, and some of our server backend has changed. closing this issue now because I'm unable to reproduce it, no debug log exists, and it is rather old. thanks for the support, hope things are working for you now :)

**Closed by rhodey** 2015-03-16 18:52 UTC
Labels: bug
