### ISSUE TITLE
Internatìonal number format and reject call with message issue 

### ISSUE THREAD

**Issue by smoother** [WhisperSystems/TextSecure#3551] opened 2015-07-07 20:18 UTC
Using TextSecure 2.21.0 on Android 5.0.2 and my Samsung Galaxy Alpha, I recently noticed the following bug: If I reject an incoming call with a message and the corresponding number is given in the international format, e.g. +49..., the message will be instead send to %2B49... (cf. URL encoding)

I could not check whether or not this also happens when using the default text messaging application. However, sending messages to such specially formatted numbers is not included by my flatrate.

**Comment by jeremymasters** [comment] 2015-07-07 20:23
I think this is a dupe of #3518

**Closed** 2015-07-07 20:25 UTC
