### ISSUE TITLE
Sharing from Google Photos is broken (again)

### ISSUE THREAD

**Issue by mammuth** [WhisperSystems/TextSecure#4018] opened 2015-09-04 18:31 UTC
When sharing a photo from the Google photos app to TextSecure, it disappears after pressing the send button and never gets send.

It seems like the fixes referenced in #3307 does not work anymore.

Here is the debug log: 
https://gist.github.com/anonymous/1bf131be013dab8036bc

Money quote:
W/MessageSender( 8614): Caused by: java.io.IOException: java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.photos.contentprovider.MediaContentProvider from ProcessRecord{33f650ab 8614:org.thoughtcrime.securesms/u0a153} (pid=8614, uid=10153) that is not exported from uid 10099
W/MessageSender( 8614): 	at org.thoughtcrime.securesms.mms.PartAuthority.getPartStream(PartAuthority.java:55)

**Comment by mcginty** [comment] 2015-09-04 18:39
seems like dupe of #3989

**Closed by mcginty** 2015-09-04 18:39 UTC
