### ISSUE TITLE
Flash SMS don't arrive

### ISSUE THREAD

**Issue by FelixSt** [WhisperSystems/TextSecure#950] opened 2014-03-03 07:47 UTC
Hello

Running TextSecure 2.0.3 on Android 4.3 (Samsung Galaxy Nexus GSM), stock Android. I do not receive any flash SMS, f.e. login codes for my online banking. I verified this issue with Hangouts and stock SMS app, both apps receive flash SMS.

Any ideas?

**Comment by rhodey** [comment] 2015-03-16 20:35
duplicate of #105 and #551, closing and moving the @moxie0 assignment from this issue to the original.

**Closed by rhodey** 2015-03-16 20:35 UTC
Labels: bug
