### ISSUE TITLE
Allow arbitrary usernames instead of only phone numbers.

### ISSUE THREAD

**Issue by mtahmed** [WhisperSystems/TextSecure#3483] opened 2015-06-27 00:04 UTC
Currently, only phone numbers are allowed as user IDs but this is a breach of privacy as phone number is identifying information for the user, even if it is encrypted (no trust should be needed).

Instead, allow users to pick arbitrary usernames and contacts can be added by their usernames.

**Comment by 2-4601** [comment] 2015-06-27 00:20
Duplicate of issues [which can be found using the search function].

**Comment by 2-4601** [comment] 2015-06-27 00:21
E.g. #1085

**Comment by rhodey** [comment] 2015-06-27 01:02
thanks @2-4601

**Closed by rhodey** 2015-06-27 01:02 UTC
