### ISSUE TITLE
Sending picture with text window behavior

### ISSUE THREAD

**Issue by rmueller83** [WhisperSystems/TextSecure#4347] opened 2015-11-03 11:45 UTC
Using Signal 3.1.1: When I have sent a picture with text, my chat window looks like this:

![current-state](https://cloud.githubusercontent.com/assets/2698076/10907125/bd65dc38-8227-11e5-8e42-ca3ffc4a079c.png)

I would either expect the chat to scroll to the bottom (as in text-only messages) like this:

![expectation1](https://cloud.githubusercontent.com/assets/2698076/10907133/d19062e6-8227-11e5-8580-eb8e5429e3c6.png)

Or the keyboard should disappear, also scrolling to the bottom (like it in picture-only messages), looking like this:

![expectation2](https://cloud.githubusercontent.com/assets/2698076/10907149/ef5f8676-8227-11e5-90ce-482ff7aa85f0.png)

**Comment by 2-4601** [comment] 2015-11-03 13:28
Duplicate of #2856?

**Comment by moxie0** [comment] 2015-11-03 17:46
looks like it, thanks

**Closed by moxie0** 2015-11-03 17:46 UTC
