### ISSUE TITLE
feature request: use system default emoji

### ISSUE THREAD

**Issue by icismachine** [WhisperSystems/TextSecure#3980] opened 2015-08-26 03:41 UTC
In the last few months the app in Android uses another emoji character set which isn't that appealing. Can there be an option to switch between default and this newer one?

**Comment by piratenpanda** [comment] 2015-08-26 05:39
They switched to the Apple emoji set so that Android and iOS users have the same emojis. Some may not like this decision but from the last discussions in the bugtracker it doesn't seem very likely that there will be an option for that.

**Comment by oaim** [comment] 2015-08-26 09:08
This is a duplicate of like 10 issues already. Please... close it.

**Closed** 2015-08-26 14:25 UTC
