### ISSUE TITLE
All MMS since last update show "MMS download failed!" error

### ISSUE THREAD

**Issue by alexandreboivin** [WhisperSystems/TextSecure#2916] opened 2015-04-07 18:51 UTC
Incoming MMS messages used to work reliably but, since last update, do not download automatically and show "MMS download failed!" error when manually retrying to download. I'm using the default APN for MMS as I did with the previous version, but manually adding the Rogers MMS APN did not resolve the issue. The problem occurs whether I'm on Wifi or mobile data.

Device info: HTC One M8, Android 5.0.1, TextSecure 2.9.3, Rogers
Debug log: https://gist.github.com/anonymous/9877942146a38387cb1e

**Comment by moxie0** [comment] 2015-04-07 19:02
Hey @alexandreboivin as of 2.9 we now use the Android APIs for sending MMS messages.  That means that before we were building the APN information ourselves based on your MNCMCC, where as now the APN information is all drawn from your Android APN configuration.

I have a feeling that is probably where your problem might be, if you could double check that is all configured correctly.

**Comment by moxie0** [comment] 2015-04-07 19:03
Also check and see if MMS works correctly using the stock (not hangouts) MMS app.

**Comment by alexandreboivin** [comment] 2015-04-07 19:52
Just tested it, and sending and receiving MMS work fine using the stock MMS app. Would that be the case if it was an APN issue?

**Comment by moxie0** [comment] 2015-04-07 20:31
Ok, I'm going to close this as a duplicate of #2872, you can follow along there.

**Closed by moxie0** 2015-04-07 20:31 UTC
