### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Allanitomwesh** [WhisperSystems/TextSecure#2858] opened 2015-04-02 11:16 UTC
It would be nice if you added your app to F-Droid. it is an open source repository of apps and i'd rather get apps there than play store.

**Comment by agrajaghh** [comment] 2015-04-02 11:54
Duplicate of #127

**Comment by moxie0** [comment] 2015-04-02 15:37
Please search existing issues before filing new ones.

**Closed by moxie0** 2015-04-02 15:37 UTC
