### ISSUE TITLE
option to rejoin broken group

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3420] opened 2015-06-13 07:56 UTC
It is clear that uninstalling/reinstalling is a big problem for group chats. Receiving a message from a group makes it impossible to answer or open the keyboard or update the group.
An idea to fix this could be this. You could add an "restore/ask to rejoin" option (available only when you detect that the user can't reply), which asks all the people who have written so far for the metadata of the group chat. This would be the least painful way for newbies to get around the current problem which requires an avatar update.
Do you think this is feasible?

**Comment by agrajaghh** [comment] 2015-06-13 10:36
duplicate of #2581

**Comment by oaim** [comment] 2015-06-13 10:38
It's not a duplicate. I know the bug report exists already, I am proposing a solution to see if it's feasible..

**Comment by moxie0** [comment] 2015-06-14 02:48
Thanks @oaim but this is an issue tracker, not a discussion forum.  You can check out the mailing list for discussions.

**Closed by moxie0** 2015-06-14 02:48 UTC
