### ISSUE TITLE
Quick response on call wrong number

### ISSUE THREAD

**Issue by r00tat** [WhisperSystems/TextSecure#3631] opened 2015-07-12 14:36 UTC
In Austria we are mainly using E.164 format on mobile numbers I.e. +43 664 12345678. If I receive a call and send a quick response it will be sent to the wrong number: 243664 12345678 instead of +43 664... It seem like the plus is converted to a 2.

**Comment by 2-4601** [comment] 2015-07-12 16:01
Duplicate of #3518?

**Closed** 2015-07-12 16:39 UTC
