### ISSUE TITLE
Crash when entering notification sound setting

### ISSUE THREAD

**Issue by Mangoes** [WhisperSystems/TextSecure#2513] opened 2015-02-22 16:58 UTC
Clicking on the setting option to change the notification sound always crashes textsecure.

(It isn't possible to enter the menu to change the default notification sound).

**Comment by moxie0** [comment] 2015-02-22 20:14
Please post a debug log.

**Comment by Mangoes** [comment] 2015-02-22 20:43
OS Host: iagold-desktop
App    : TextSecure 2.5.3

--------- beginning of /dev/log/system
W/ViewRootImpl( 5487): Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, id[0]=0, x[0]=280.16644, y[0]=-176.50037, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=4, eventTime=1991343, downTime=1991292, deviceId=4, source=0x1002 }
W/ViewRootImpl( 5487): Dropping event due to root view being removed: MotionEvent { action=ACTION_UP, id[0]=0, x[0]=280.16644, y[0]=-176.50037, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1991353, downTime=1991292, deviceId=4, source=0x1002 }
E/AndroidRuntime( 5487): FATAL EXCEPTION: main
E/AndroidRuntime( 5487): Process: org.thoughtcrime.securesms, PID: 5487
E/AndroidRuntime( 5487): java.lang.SecurityException: Permission Denial: getTasks() from pid=5487, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime( 5487): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime( 5487): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime( 5487): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime( 5487): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime( 5487): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime( 5487): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime( 5487): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime( 5487): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime( 5487): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime( 5487): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime( 5487): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime( 5487): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime( 5487): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime( 5487): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime( 5487): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 5487): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime( 5487): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5487): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5487): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime( 5487): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime( 5487): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(12987): FATAL EXCEPTION: main
E/AndroidRuntime(12987): Process: org.thoughtcrime.securesms, PID: 12987
E/AndroidRuntime(12987): java.lang.SecurityException: Permission Denial: getTasks() from pid=12987, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(12987): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(12987): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(12987): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(12987): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(12987): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(12987): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(12987): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(12987): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(12987): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(12987): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(12987): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(12987): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime(12987): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(12987): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(12987): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(12987): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(12987): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12987): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12987): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(12987): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(12987): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(13146): FATAL EXCEPTION: main
E/AndroidRuntime(13146): Process: org.thoughtcrime.securesms, PID: 13146
E/AndroidRuntime(13146): java.lang.SecurityException: Permission Denial: getTasks() from pid=13146, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(13146): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(13146): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(13146): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(13146): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(13146): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(13146): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(13146): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(13146): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(13146): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(13146): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(13146): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(13146): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime(13146): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(13146): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(13146): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(13146): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(13146): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(13146): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(13146): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(13146): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(13146): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(13831): FATAL EXCEPTION: main
E/AndroidRuntime(13831): Process: org.thoughtcrime.securesms, PID: 13831
E/AndroidRuntime(13831): java.lang.SecurityException: Permission Denial: getTasks() from pid=13831, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(13831): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(13831): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(13831): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(13831): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(13831): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(13831): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(13831): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(13831): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(13831): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(13831): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(13831): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(13831): 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4056)
E/AndroidRuntime(13831): 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3655)
E/AndroidRuntime(13831): 	at android.view.View.dispatchTouchEvent(View.java:7792)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2316)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2013)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
E/AndroidRuntime(13831): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
E/AndroidRuntime(13831): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2109)
E/AndroidRuntime(13831): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1541)
E/AndroidRuntime(13831): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2491)
E/AndroidRuntime(13831): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2057)
E/AndroidRuntime(13831): 	at android.view.View.dispatchPointerEvent(View.java:7983)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4429)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4273)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3819)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3869)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3838)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3945)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3846)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4002)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3819)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3869)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3838)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3846)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3819)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6313)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6293)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6247)
E/AndroidRuntime(13831): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6443)
E/AndroidRuntime(13831): 	at
E/AndroidRuntime(14038): FATAL EXCEPTION: main
E/AndroidRuntime(14038): Process: org.thoughtcrime.securesms, PID: 14038
E/AndroidRuntime(14038): java.lang.SecurityException: Permission Denial: getTasks() from pid=14038, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(14038): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(14038): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(14038): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(14038): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(14038): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(14038): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(14038): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(14038): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(14038): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(14038): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(14038): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(14038): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime(14038): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(14038): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(14038): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(14038): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(14038): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14038): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14038): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(14038): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(14038): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(14497): FATAL EXCEPTION: main
E/AndroidRuntime(14497): Process: org.thoughtcrime.securesms, PID: 14497
E/AndroidRuntime(14497): java.lang.SecurityException: Permission Denial: getTasks() from pid=14497, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(14497): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(14497): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(14497): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(14497): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(14497): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(14497): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(14497): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(14497): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(14497): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(14497): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(14497): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(14497): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime(14497): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(14497): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(14497): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(14497): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(14497): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14497): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(14497): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(14497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(14497): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(15050): FATAL EXCEPTION: main
E/AndroidRuntime(15050): Process: org.thoughtcrime.securesms, PID: 15050
E/AndroidRuntime(15050): java.lang.SecurityException: Permission Denial: getTasks() from pid=15050, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(15050): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(15050): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(15050): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(15050): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(15050): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(15050): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(15050): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(15050): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(15050): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(15050): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(15050): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(15050): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime(15050): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(15050): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(15050): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(15050): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(15050): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15050): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(15050): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(15050): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(15050): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(23152): FATAL EXCEPTION: main
E/AndroidRuntime(23152): Process: org.thoughtcrime.securesms, PID: 23152
E/AndroidRuntime(23152): java.lang.SecurityException: Permission Denial: getTasks() from pid=23152, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(23152): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(23152): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(23152): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(23152): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(23152): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(23152): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(23152): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(23152): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(23152): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(23152): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(23152): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(23152): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime(23152): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(23152): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(23152): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23152): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(23152): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23152): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(23152): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(23152): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(23152): 	at dalvik.system.NativeStart.main(Native Method)
--------- beginning of /dev/log/main
W/KeyCachingService(23512): Incrementing activity count...
W/KeyCachingService(23512): Decrementing activity count...
W/KeyCachingService(23512): Incrementing activity count...
W/KeyCachingService(23512): Decrementing activity count...
W/KeyCachingService(23512): Incrementing activity count...
D/Ringtone(23512): Successfully created local player
E/MediaPlayer(23512): Should have subtitle controller already set
E/AndroidRuntime(23512): FATAL EXCEPTION: main
E/AndroidRuntime(23512): Process: org.thoughtcrime.securesms, PID: 23512
E/AndroidRuntime(23512): java.lang.SecurityException: Permission Denial: getTasks() from pid=23512, uid=10242 requires android.permission.GET_TASKS
E/AndroidRuntime(23512): 	at android.os.Parcel.readException(Parcel.java:1472)
E/AndroidRuntime(23512): 	at android.os.Parcel.readException(Parcel.java:1426)
E/AndroidRuntime(23512): 	at android.app.ActivityManagerProxy.getTasks(ActivityManagerNative.java:2671)
E/AndroidRuntime(23512): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:776)
E/AndroidRuntime(23512): 	at android.app.ActivityManager.getRunningTasks(ActivityManager.java:812)
E/AndroidRuntime(23512): 	at android.preference.RingtonePreference.onClick(RingtonePreference.java:150)
E/AndroidRuntime(23512): 	at android.preference.Preference.performClick(Preference.java:977)
E/AndroidRuntime(23512): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime(23512): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime(23512): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1153)
E/AndroidRuntime(23512): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
E/AndroidRuntime(23512): 	at android.widget.AbsListView$3.run(AbsListView.java:4031)
E/AndroidRuntime(23512): 	at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(23512): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(23512): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23512): 	at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(23512): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23512): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(23512): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
E/AndroidRuntime(23512): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
E/AndroidRuntime(23512): 	at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm( 7760): VFY: unable to resolve virtual method 13427: Landroid/view/ViewGroup;.onNestedScrollAccepted (Landroid/view/View;Landroid/view/View;I)V
W/dalvikvm( 7760): VFY: unable to resolve virtual method 13433: Landroid/view/ViewGroup;.onStopNestedScroll (Landroid/view/View;)V
W/dalvikvm( 7760): VFY: unable to resolve virtual method 9635: Landroid/support/v7/internal/widget/ActionBarOverlayLayout;.stopNestedScroll ()V
W/dalvikvm( 7760): VFY: unable to resolve virtual method 563: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
W/dalvikvm( 7760): VFY: unable to resolve virtual method 585: Landroid/content/res/TypedArray;.getType (I)I
W/dalvikvm( 7760): VFY: unable to resolve virtual method 27071: Lcom/melnykov/fab/FloatingActionButton;.setElevation (F)V
W/KeyCachingService( 7760): Incrementing activity count...
E/        ( 7760): appName=org.thoughtcrime.securesms, acAppName=/system/bin/surfaceflinger
E/        ( 7760): 0
W/RecipientProvider( 7760): Cache miss [ASYNC]!
W/KeyCachingService( 7760): Decrementing activity count...
W/KeyCachingService( 7760): Incrementing activity count...
W/KeyCachingService( 7760): Decrementing activity count...

**Comment by moxie0** [comment] 2015-02-23 04:42
This looks like a problem with your ROM or some 3rd party weirdness like xprivacy.  What is "iagold-desktop"?

**Comment by Mangoes** [comment] 2015-02-23 09:32
I have now tried it with other applications like Textra sms, it works fine : when I click to select the notification sound option I get a popup to choose the application to select the sounds.

It only crashes with textsecure (instead of displaying the application selection popup to choose multimedia storage or ES explorer, it crashes , so this should definitely be a bug.

I don't have xprivacy installed and don't know what iagold-desktop is.

Thanks.

I am on stock rom android 4.4.2 using the ART engine.

**Comment by agrajaghh** [comment] 2015-02-23 09:56
Could you try if it's crashing with dalvik as well?

**Comment by Mangoes** [comment] 2015-02-23 10:18
With dalvik it's crashing as well.

(I have removed and reinstalled textsecure in the process).

**Comment by patcon** [comment] 2015-03-05 00:56
Ref: [`iagold-desktop`](http://forum.xda-developers.com/general/xda-assist/help-rooting-obi-s520-octopus-mobile-t2919084)

**Comment by rhodey** [comment] 2015-03-13 19:12
unable to reproduce but some research into this says the cause is usually duplicate entries for a single activity in the `AndriodManifest.xml` file or failing to set `android:exported="true"` on an activity.

http://stackoverflow.com/questions/4162447/android-java-lang-securityexception-permission-denial-start-intent
http://stackoverflow.com/questions/2974261/hellowebview-sample-java-lang-securityexception-permission-denial

**Comment by rhodey** [comment] 2015-04-24 19:42
I assigned this to myself with the intention of testing on TestObject or AppThwack but neither have the OBI S520 Octopus device available, removing assignment.

**Comment by riyapenn** [comment] 2015-10-21 23:28
Is this still an issue?

**Closed by riyapenn** 2015-10-21 23:28 UTC
Labels: bug
