### ISSUE TITLE
Make scroll to new message on send optional.

### ISSUE THREAD

**Issue by whispy** [WhisperSystems/TextSecure#1472] opened 2014-05-09 17:10 UTC
I'm referencing this issue: https://github.com/WhisperSystems/TextSecure/pull/1249

Would it be possible to make this optional via settings (enabled by default)? I often receive multiple questions spread across multiple messages and the fact that TS didn't automatically scroll every time I sent a reply was very useful. I really liked being able to answer questions one by one without having to scroll back up every time I replied to one.

**Comment by rhodey** [comment] 2015-03-17 00:01
closing as duplicate of #1211

**Closed by rhodey** 2015-03-17 00:01 UTC
Labels: defer, feature
