### ISSUE TITLE
Phantom push message notifications on text secure lock

### ISSUE THREAD

**Issue by privong** [WhisperSystems/TextSecure#2221] opened 2014-12-15 13:47 UTC
Over the past week or so, I have been getting phantom push message notifications. By phantom, I mean an "encrypted message" notification appears, but then the are no new messages after I unlock text secure. Initially there was only one phantom message, a day it two later there were two, now there are six. They seem to appear shortly after time text secure locks itself.

**Edit:** Have confirmed that the phantom notification appears immediately after (manually) locking textsecure.

```
Device : motorola XT1045 (peregrine_retus)
Android: KXB21.14-L1.56
OS Host: ilclbld72
App    : TextSecure 2.3.3

--------- beginning of /dev/log/main
W/MmsSmsDatabase(18555): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/ShortcutBadger(18555): No support for: com.android.launcher
W/KeyCachingService(18555): Incrementing activity count...
W/KeyCachingService(18555): Decrementing activity count...
W/service (18555): Broadcasting new secret...
W/KeyCachingService(18555): Starting timeout: 1800000
W/MmsSmsDatabase(18555): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/ShortcutBadger(18555): No support for: com.android.launcher
D/dalvikvm(18555): GC_EXPLICIT freed 1621K, 29% free 12218K/17188K, paused 2ms+6ms, total 57ms
W/SendReceiveService(18555): Got a MasterSecret broadcast...
W/PartProvider(18555): Got master secret: org.thoughtcrime.securesms.crypto.MasterSecret@42441aa8
W/KeyCachingService(18555): Incrementing activity count...
W/KeyCachingService(18555): Decrementing activity count...
W/KeyCachingService(18555): Starting timeout: 1800000
D/dalvikvm(18555): GC_CONCURRENT freed 833K, 22% free 13432K/17188K, paused 3ms+4ms, total 35ms
D/dalvikvm(18555): WAIT_FOR_CONCURRENT_GC blocked 14ms
D/dalvikvm(18555): GC_CONCURRENT freed 1310K, 18% free 14114K/17188K, paused 2ms+2ms, total 30ms
D/dalvikvm(18555): WAIT_FOR_CONCURRENT_GC blocked 22ms
D/dalvikvm(18555): GC_CONCURRENT freed 1082K, 13% free 14978K/17188K, paused 3ms+4ms, total 40ms
W/PhoneNumberFormatter(18555): Got local CC: US
W/MmsSmsDatabase(18555): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, 'sms' AS transport_type FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, 'mms' AS transport_type FROM mms WHERE (thread_id = 1) ORDER BY date_received ASC)
W/PhoneNumberFormatter(18555): Got local CC: US
W/MmsCommunication(18555): Getting MMSC params for apn fast.t-mobile.com
W/KeyCachingService(18555): Incrementing activity count...
W/TelephonyUtil(18555): Choosing MCC+MNC info from TelephonyManager.getSimOperator()
W/ApnDatabase(18555): Querying table for MCC+MNC 310260 and APN name fast.t-mobile.com
W/ApnDatabase(18555): Returning preferred APN Apn{ mmsc: "http://mms.msg.eng.t-mobile.com/mms/wapenc", proxy: none, port: (none), user: "none", pass: "none" }
W/CursorWindow(18555): Window is full: requested allocation 240 bytes, free space 88 bytes, window size 2097152 bytes
V/WebViewChromiumFactoryProvider(18555): Binding Chromium to main looper Looper (main, tid 1) {41fe41d0}
I/LibraryLoader(18555): Expected native library version number "",actual native library version number ""
I/chromium(18555): [INFO:library_loader_hooks.cc(116)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController(18555): Initializing chromium process, renderers=0
E/AudioManagerAndroid(18555): BLUETOOTH permission is missing!
D/dalvikvm(18555): GC_CONCURRENT freed 1402K, 9% free 15693K/17188K, paused 3ms+6ms, total 92ms
D/AudioManagerAndroid(18555): ==> onReceive: s=0, m=1, n=h2w, sb=true
D/AudioManagerAndroid(18555): reportUpdate: state=0, devices=[Speakerphone, Headset earpiece]
W/MmsSmsDatabase(18555): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/ShortcutBadger(18555): No support for: com.android.launcher
W/InputEventReceiver(18555): Attempted to finish an input event but the input event receiver has already been disposed.
W/KeyCachingService(18555): Decrementing activity count...
W/KeyCachingService(18555): Starting timeout: 1800000
W/DirectoryRefreshListener(18555): Scheduling for: 1418660925184
W/KeyCachingService(18555): Incrementing activity count...
W/MmsSmsDatabase(18555): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, 'sms' AS transport_type FROM sms WHERE (thread_id = 1) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, 'mms' AS transport_type FROM mms WHERE (thread_id = 1) ORDER BY date_received DESC) LIMIT 1
W/KeyCachingService(18555): Decrementing activity count...
W/KeyCachingService(18555): Starting timeout: 1800000
W/KeyCachingService(18555): Incrementing activity count...
W/KeyCachingService(18555): Decrementing activity count...
W/KeyCachingService(18555): Starting timeout: 1800000
```

**Comment by privong** [comment] 2015-01-15 21:32
As an update, this is still occurring with TextSecure 2.4.1.

**Comment by privong** [comment] 2015-04-06 11:19
I am still experiencing this issue with TextSecure version 2.9.3.

**Comment by moxie0** [comment] 2015-04-18 16:38
Closing as duplicate of #2358

**Closed by moxie0** 2015-04-18 16:38 UTC
Labels: bug
