### ISSUE TITLE
Is there a way to create an "incognito thread"?

### ISSUE THREAD

**Issue by ghostbar** [WhisperSystems/TextSecure#2412] opened 2015-02-05 16:13 UTC
It would be nice to have a way to create a thread that can cleans the logs automatically based on timing.

Not only that, it would be good to have a way to delete messages from the thread and affect both parties, something like Twitter does with the DMs. So a message that gets deleted in a peer-thread gets deleted on the other peer-thread.

**Comment by agrajaghh** [comment] 2015-02-05 16:22
Deleting messages from the remote party is a duplicate of #1764

**Comment by moxie0** [comment] 2015-02-05 16:52
There is not.

**Closed by moxie0** 2015-02-05 16:52 UTC
