### ISSUE TITLE
Visually combine messages that were sent shortly after each other

### ISSUE THREAD

**Issue by gartenriese2** [WhisperSystems/TextSecure#2646] opened 2015-03-11 20:37 UTC
Would it be possible to visually combine incoming and outgoing messages from the same user into one message? I think it wastes a lot of space if there is the name and icon for the user with each message. 

![screenshot_2015-03-11-21-33-38](https://cloud.githubusercontent.com/assets/4339033/6606269/9c8e8452-c836-11e4-8deb-11c7567860b1.png)

All the messages that were sent 7 minutes ago could be combined into one if no other user has sent anything inbetween. Each message in a new line.

**Comment by mcginty** [comment] 2015-03-11 20:39
dupe of #964, thanks

**Closed by mcginty** 2015-03-11 20:39 UTC
