### ISSUE TITLE
Non-chronological message order

### ISSUE THREAD

**Issue by fungs** [WhisperSystems/TextSecure#2385] opened 2015-01-25 13:35 UTC
From time to time, I'm receiving messages in non-chronological order. In rare cases, messages are not transmitted at all which is now better to control since we have the reception confirmation. IMO these things have to do with the server implementation but could be solved in the client and protocol by referencing to the last message ID or similar.

Using the latest Android client available on Google Play store.

**Comment by janvlug** [comment] 2015-01-25 23:25
Duplicate of #188?

**Comment by wp9015362** [comment] 2015-07-03 16:39
I am also affected by this. And it is extremely annoying.

I don't think it's a duplicate of https://github.com/WhisperSystems/TextSecure/issues/188.

Because:

I very often do receive new messages and they are sorted as if they would be old.

So, for example, let's say M1 is the oldest message and M5 is the latest message which has just arrived, then TextSecure very often displays the messages in an order like this:

M1
M4
M5
M2
M3

So, they are sorted as if M4 and M5 would be older than M2, even though M4 and M5 are the latest messages.

Sometimes I am receiving a message and am getting the notification preview for the message. Then I open TextSecure and want to read the message and am wondering where it has gone. Then I need to scroll up in the conversation to find them because they have been sorted way up in the conversation as if they would be old.

Could you please do something about that?

Regards

**Comment by fungs** [comment] 2015-08-18 17:05
Should be easy to fix at least when displaying by referencing the last message or introducing an incremented counter.

**Comment by riyapenn** [comment] 2015-09-24 20:27
Related to https://github.com/WhisperSystems/TextSecure/issues/937

**Closed** 2015-10-23 18:34 UTC

**Comment by JohnyM01** [comment] 2017-08-07 04:37
Hello I am using Signal 4.8.1 in an Android 5.x phone and I can still replicate the above mentioned message out of order problem. Some messages are not sent until minutes later. Some have nearly 1 hours. The replication was done within the same room but using different wifi connections (the most commonly usage scenario) from different providers.

Very annnoying and if it is like this, one cannot place too much confidence on timely dispatch of message and people cannot rely on Signal for serious usages. That could lead to misunderstanding between parties. The single tick is a great help if it sit there for a while telling me to jump onto a different messenger when it has not changed to a double ticks.

Johny

**Comment by Markkux** [comment] 2017-08-18 12:00
Same problem here. Signal 4.8.1 over Android 6 and 7. It mainly happens when the terminal recovers data connection. The messages' sending timestamp is correct but they appear disorganized 'cause they're sorted by "receiving" time, not "sending" time. At this point, the only way to trust the actual order is by reading "info" metadata.

**Comment by 2-4601** [comment] 2018-04-17 15:45
This feature request is being discussed and tracked [here](https://community.signalusers.org/t/message-ordering/2581).
