### ISSUE TITLE
Error "Some issues need your attention" after adding 10th person to a group

### ISSUE THREAD

**Issue by AltJ** [WhisperSystems/TextSecure#2820] opened 2015-03-28 18:11 UTC
After adding 10 people to a group, all sent messages are shown as "Not delivered"  When tapping on "Tap for details" all it says is "Some issues need your attention." with a list of the users in the group.

**Comment by AltJ** [comment] 2015-03-28 19:11
It looks like messages are getting through to at least some people in the group despite the "Not delivered" message coming back.

**Comment by mcginty** [comment] 2015-03-29 23:00
That's interesting. Can you post a debug log after sending a message that this happens to?

**Comment by AltJ** [comment] 2015-03-30 16:19
Here's a debug log for you...
https://gist.github.com/AltJ/b28e46d825397803098f

**Comment by moxie0** [comment] 2015-03-31 19:59
ah, one of the people in the group has uninstalled textsecure

**Comment by AltJ** [comment] 2015-03-31 20:23
Thank you!  Is there a way to identify the culprit?
(I'm in the process of testing this out this with a new group.)

I'm not sure the best way to handle a scenario like this from a functionality standpoint.   Remove the person from the group and notify everyone or just include additional information identifying the person that no longer has it installed.

I think that removing the person from the group and notifying everyone would be easiest for users.  (Is it even possible to remove someone from a group?)

Just identifying the person alone would be helpful, but it's less convenient to start a new group and exclude the culprit.

**Comment by McLoo** [comment] 2015-03-31 20:47
@moxie0 what about asking if the invalid recipient should be removed upon that exception?  Or better: do it  automatically, and send or an  info message to the group - since every member needs to remove the odd man... 

3rd thing coming to my mind,  send out an remove recipient message from the server to all it's groups, when unregistered.

**Comment by moxie0** [comment] 2015-03-31 20:51
@McLoo The server doesn't know what groups you're in.

But yeah, we should do something.

**Comment by moxie0** [comment] 2015-03-31 20:53
@AltJ The numbers in the log are obfuscated, but it looks like the offending number ends in 34. (+*********34)

Until we fix this, you'll have to ask them to reinstall or create a new group without them in it.

**Comment by AltJ** [comment] 2015-03-31 21:02
Thanks, now I know who it is and am going to scold them for uninstalling it :-)

FYI - For some reason, that person is not in the list of group members anymore, so it would have been very difficult to identify them without looking at the debug log.

**Comment by rmueller83** [comment] 2015-03-31 21:09
So it's a duplicate of https://github.com/WhisperSystems/TextSecure/issues/2408 ?

**Comment by AltJ** [comment] 2015-03-31 21:12
Looks like a duplicate to me.

**Closed** 2015-03-31 21:14 UTC
Labels: bug
