### ISSUE TITLE
Message size restriction

### ISSUE THREAD

**Issue by JeremyWW** [WhisperSystems/TextSecure#3774] opened 2015-07-23 15:42 UTC
This is a show stopper for me. Message size restriction of 280kb means I couldn't send a video to my daughter. I could , however, send it with 'that other well known messaging app'. Are you intending to address this in some way?

**Comment by 2-4601** [comment] 2015-07-23 17:09
Duplicate of #700, #2780

**Comment by JeremyWW** [comment] 2015-07-23 17:14
Seems like searching on Github is rubbish. I did look for the issue before posting!

**Comment by mcginty** [comment] 2015-07-23 18:24
Yeah, there's only so much you can do with github's search functionality.

**Closed** 2015-07-23 18:23 UTC
