### ISSUE TITLE
Allow registering with another kind of ID, no revealing phone number

### ISSUE THREAD

**Issue by RalfJung** [WhisperSystems/TextSecure#3948] opened 2015-08-15 15:05 UTC
It should be possible to register a TextSecure account without giving Whisper Systems, or my contacts, my phone number.

I think it's curious that an application with a strong focus on privacy requires the disclosure of this highly identifying piece of information - but I understand that this is caused by the origin of TextSecure as an SMS app. With that left behind, the road is now open to permit users to use another kind of identifier. A natural choice would be email addresses.

**Comment by moxie0** [comment] 2015-08-15 15:15
Duplicate of #1085.  Please check existing issues before opening new ones.

**Closed by moxie0** 2015-08-15 15:15 UTC

**Comment by RalfJung** [comment] 2015-08-15 18:03
Thanks.
I'm sorry - I did check, searching for "phone" and some other keywords, but gave up after ~4 pages of results.
