### ISSUE TITLE
something is wrong with the smilies

### ISSUE THREAD

**Issue by neo6238** [WhisperSystems/TextSecure#3709] opened 2015-07-18 11:48 UTC
Something is wrong with the latest upgrade from play store. It does not use the default smilies anymore but some boring systems default  ones (the ones from whatsapp).

**Comment by 2-4601** [comment] 2015-07-18 11:54
It's intentional. TS uses Apple emoji for consistency.
Please close this issue.
Duplicate of #3681, #3682, #3690, #3675, #3662

**Comment by tueftl** [comment] 2015-07-18 12:02
...and a partial duplicate of #3712 - I didn't see #3709 while writing it. But PLEASE do not just close it, please implement an option to have the good Android default emojis!

**Comment by neo6238** [comment] 2015-07-18 12:06
This is on purpose??? I doubt this is a popular decision...

I'll suggest for Signal to use the Google emoji then.

**Comment by 2-4601** [comment] 2015-07-18 12:17
I give up.

Here's what will happen:
1) You close this issue yourself
OR
2) You don't close it, the devs will see it, get pissed off by yet another OMG-i-hate-apple-emoji-i-will-uninstall, then they might ban you for being annoying and then close it.

Either way this will be closed.

**Closed** 2015-07-18 13:00 UTC

**Comment by neo6238** [comment] 2015-07-18 13:13
@tueftl You might try getting the "textsecure 2.21.0 apk" from the web.

Maybe even the previous one, as I did not like the "Conversation colors" either.

**Comment by Dyras** [comment] 2015-07-18 16:07
Go over to SMSSecure and ask if the guys behind that project can make another fork, with the only change being that you can choose Google's emojis. Might work.

**Comment by johanw666** [comment] 2015-07-18 19:40
SMSSecure didn't switch to Apple emoji due to unclear rights issues and the fsct that it won't run on iOas anyway.

**Comment by neo6238** [comment] 2015-07-19 09:58
Can SMSSecure handle textsecure push messages? 
Their description seems to me like it does only do the SMS encryption stuff. Is this feature going to be removed from textsecure soon? I remember hearing some annoucements a while ago, but I still find the option to use SMS and MMS in the textsecure app (although I personally neved used it)...

**Comment by Dyras** [comment] 2015-07-19 10:00
That's why I said you can go ask them to make another fork. EmojiSecure or whatever.

Encrypted SMS was removed, but you can still use it as your standard SMS app.

**Comment by johanw666** [comment] 2015-07-19 15:16
No, SMSSecure can't handle push messages. But the change back to Google emojis is trivial, just revert 2 commits and you're done. If you consider it important, do it yourself.

**Comment by 1337sup3rh4x0r** [comment] 2015-07-21 21:07
Is there by any chance already a fork that is doing that? I really like the android emojis but don't want to miss out on the real improvements from text secure development.

**Comment by gartenriese2** [comment] 2015-07-24 10:00
Which commits exactly do I have to revert to get the good smileys back?

**Comment by johanw666** [comment] 2015-07-24 18:33
None, yoyu already have them. :-)

If you want the Google emojis back, you would have to revert https://github.com/WhisperSystems/TextSecure/commit/9a18be0a6194d4dd8ef420e9b567b1d7ce69c613 and https://github.com/WhisperSystems/TextSecure/commit/282f139ee9f9483a49ac78f448d1e2d3bbb5e374
