### ISSUE TITLE
[Feature request] Animated Gifs in Conversation

### ISSUE THREAD

**Issue by alex42ka** [WhisperSystems/TextSecure#2610] opened 2015-03-07 09:55 UTC
Would be really great, if TextSecure, as other messengers, would be able to show the animation of animated gifs in the conversation.

**Comment by generalmanager** [comment] 2015-03-07 11:36
This is a duplicate of https://github.com/WhisperSystems/TextSecure/issues/643. Please close this ticket and join the conversation over there. Thanks!

**Closed** 2015-03-08 23:45 UTC
