### ISSUE TITLE
Initial avatar rendered incorrectly when opening conversation

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3136] opened 2015-05-08 15:39 UTC
TS 2.14.1, stock Android 5.1

1. Open a conversation with someone who has no contact picture (i.e. is using the new initial creation avatar bubble)
2. The top most avatar bubble is rendered bigger than the rest

Scrolling and switching apps usually makes it render correctly. But sometimes (fast) scrolling moves the issue to another bubble. However when you open the conversation again from the main list it shows up again consistently (at least on 5.1).

![initial bubble avatar](https://cloud.githubusercontent.com/assets/174176/7539699/5df40188-f5b1-11e4-9de6-d088f649bef3.png)

**Comment by volcano99** [comment] 2015-05-08 17:38
I have the same problem, I wanted to take a screenshot but it disappear within instants for me. Most of the times it happened I didn't have to scroll

**Comment by 2-4601** [comment] 2015-05-08 17:46
I don't have this issue with my 4.0.4 device.

**Comment by 2-4601** [comment] 2015-05-08 17:59
[Debug log](https://gist.github.com/62c6eabccd8a26c1ef04) from 5.1 device after
- device reboot
- open TS
- open the conversation that has the issue

**Comment by McLoo** [comment] 2015-05-08 18:07
Occurred on my Z1c KK for a convo. 
- in convo all fine 
- exit, reenter: big bubbles (all) 
- exit, reenter: correct bubbles (all) 
- worked 2 times, then all bubbles always correct for that convo

**Comment by McLoo** [comment] 2015-05-08 18:13
Just noticed: the bubbles expand on leaving the convo, only visible when images messages are visible (slower swipe out of convo?) 
Could be an cache issue when reentering?

**Comment by McLoo** [comment] 2015-05-10 11:43
Sorry, accidentally posted that in the PR:

for the record:
Lust noticed a pulsing (normal <> oversize) bubble in the conversation *list*, when upgrading an older version on a 5.0.2 device.
There where some unread messages which seemed to cause that, while the Lollipoop notifier was open.

**Comment by claenn** [comment] 2015-05-10 17:26
Confirmed, KK 4.4.4, v2.14.1

![bubble](https://cloud.githubusercontent.com/assets/8040019/7555379/5ee55b06-f74a-11e4-9958-a215c3fe34fb.gif)

**Comment by moxie0** [comment] 2015-05-10 21:13
@McLoo You're noticing that running the code in the PR or in 2.14.1?

**Comment by McLoo** [comment] 2015-05-10 21:52
@moxie0 yeah, upgraded from pre 2.14 directly to 2.14.1 but noticed that pulsing bubble only then. 

Can't reproduce with 2.14.1 having the L notifier popped up and getting messages in. Guess it was the the bunch of unread messages that were processed.

**Comment by mcginty** [comment] 2015-05-13 01:31
fix is in master

**Closed by mcginty** 2015-05-13 01:31 UTC
