### ISSUE TITLE
[RFE] Add retry button to SMS Fallback popup

### ISSUE THREAD

**Issue by gladiac** [WhisperSystems/TextSecure#2500] opened 2015-02-20 08:14 UTC
I have enabled to be asked if I want to fallback to SMS if a push message can't be sent. Sometimes just the reception is bad or I type a message in the elevator. I don't want to send it via SMS, I just want to retry to send it over PUSH after I leave the elevator for example. So the SMS fallback popup should have another options to retry via PUSH.

**Comment by agrajaghh** [comment] 2015-02-20 11:14
Kind of duplicate of #1654 

I don't think there should be a button, the message should be queued automatically for push until the user sends the fallback sms...

**Closed** 2015-02-20 11:22 UTC
Labels: feature, ux
