### ISSUE TITLE
Add support for multiple recipients (without groups)

### ISSUE THREAD

**Issue by bisam** [WhisperSystems/TextSecure#1499] opened 2014-05-16 11:36 UTC
It would be nice to be able to send a message to multiple numbers without having to use the group function. If it is just for one message I should not need to create a new group.

edit: I just realized I cannot send messages through groups at all, if there is one person not using TextSecure. My provider/contract does not support MMS. So I am not able to use TextSecure for sending multiple messages without copy and pasting the content to every person -_-

**Comment by bisam** [comment] 2015-01-16 02:39
seems like there is no interest in implementing this feature.. my provider does not support MMS so I guess I just have to stick to another app and send the sms unencrypted :(

**Comment by mcginty** [comment] 2015-02-16 06:19
dupe of https://github.com/WhisperSystems/TextSecure/issues/413

**Closed by mcginty** 2015-02-16 06:19 UTC

**Comment by daryltucker** [comment] 2015-03-23 23:23
https://github.com/WhisperSystems/TextSecure/issues/1762

**Comment by daryltucker** [comment] 2015-03-23 23:24
@mcginty They aren't dupes, but I don't think it matters too much anymore.

https://github.com/WhisperSystems/TextSecure/issues/1762

**Comment by Hnasar** [comment] 2015-03-23 23:28
@daryltucker why do you think this doesn't matter anymore? This was a big usability hurdle when I introduced TextSecure to some friends.

**Comment by daryltucker** [comment] 2015-03-26 00:03
Hey, @Hnasar 
I totally agree with your statement and I never said I don't think that this issue isn't important.  My statement about it not mattering anymore was referencing the fact that TextSecure will no longer be a 'Text'/SMS based application. See the link to issue #1762 for more information.

**Comment by moxie0** [comment] 2015-03-26 00:06
@daryltucker TextSecure still supports SMS, and will continue to.

**Comment by daryltucker** [comment] 2015-03-26 00:17
@moxie0 Great news and thank you for the clarification.

**Comment by bisam** [comment] 2015-03-26 09:36
@moxie0 good to hear, but why is there no support for this feature yet? :'( If Textsecure should be considered a replacement for the default SMS-App (unencrypted or not) IMHO it really should include the fundamental possibilty to write one message to different people, without having to use MMS. I dont want to complain too much, I simply dont understand the problem in implementing this small but essential feature.

**Comment by moxie0** [comment] 2015-03-26 15:53
@bisam We haven't implemented this one thing you care about because we're spending all our time drinking champagne in our Jacuzzi.  If it's so easy, go for it.
