### ISSUE TITLE
When being in a chat in TextSecure and then leaving TextSecure (i.e. going to home screen for example) and then going back to TextSecure, TextSecure goes to the contact list instead of going back to the chat.

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2772] opened 2015-03-24 20:53 UTC
Hello,

when being in a chat in TextSecure and then leaving TextSecure (i.e. going to home screen for example) and then going back to TextSecure, TextSecure goes to the contact list instead of going back to the chat.

That's quite annoying.

Could you please fix that and make TextSecure go back to the chat?

It would be much appreciated.

Regards

**Comment by rhodey** [comment] 2015-03-24 22:00
duplicate of #1311

**Closed by rhodey** 2015-03-24 22:00 UTC
