### ISSUE TITLE
Old messages merged with new messages

### ISSUE THREAD

**Issue by iamrekcah** [WhisperSystems/TextSecure#1071] opened 2014-03-06 21:10 UTC
I received a message which began as a SMS message that I received a long time ago. It sounded familiar. But then, somewhere in the middle, the SMS message changed (content, tone, etc). I copied the text and the sender told me that message is not what was sent by her. Somehow, the message was corrupted with an older SMS message.

Debug log: http://hastebin.com/suguwokomo

**Comment by rhodey** [comment] 2015-03-16 19:23
unable to reproduce this and no debug log available, closing because we're lacking any actionable information to resolve this. hope it's working well for you now @iamrekcah, thanks for supporting the project through these kinda tests :)

**Closed by rhodey** 2015-03-16 19:23 UTC
Labels: bug
