### ISSUE TITLE
Height of Emoji drawer does not match height of system keyboard

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3303] opened 2015-06-01 22:26 UTC
Hello,

using TextSecure 2.16.3 on an LG G2 running latest stock ROM (Android 5.0.2 Lollipop), the height of the Emoji drawer does not match the height of the system keyboard.

The Emoji drawer is higher than the system keyboard (tested with Google Keyboard from Play Store).

Could you please fix that and make the height of the Emoji drawer equal to the height of the system keyboard?

Regards

**Comment by Murazaki** [comment] 2015-06-02 08:45
Emoji size is not correct on LG G3 with 2.16.3. Please fix.

**Comment by mcginty** [comment] 2015-06-02 09:06
Yeah, this looks like a lollipop layout difference. @Murazaki if you're talking about the size of emoji themselves, that's a separate issue which has a fix out already.

**Comment by Murazaki** [comment] 2015-06-02 09:52
I was talking about the emojis being not cut correctly from the emoji grid because of a size mismatch.

**Comment by 2-4601** [comment] 2015-06-02 10:05
@Murazaki that is fixed already (3302).

This issue is probably related to #3199.

**Comment by Murazaki** [comment] 2015-06-02 10:42
Here a screenshot of how it looks. http://imgur.com/MK9ckFK

I shall create a new issue.

**Comment by Murazaki** [comment] 2015-06-02 10:46
Please see #3308

**Comment by 2-4601** [comment] 2015-06-02 12:38
@Murazaki You've been told already twice that it has been fixed already so I don't know if telling you third time will help :)

The dissected emoji problem is already reported #2957 and fixed in #3302. The reason you still see the issue is because it's not released on Play Store yet.

**Comment by Murazaki** [comment] 2015-06-02 12:56
Sorry, I just couldn't see the link between those issues. I've seen those commits but couldn't access the version tags from my smartphone. My bad.

**Comment by 2-4601** [comment] 2015-06-02 13:12
It's alright... it happens :)

To help this issue would you mind deleting the comments that are unrelated to this issue? Now most of the comments here are about something else.

It would also help the devs if you closed the duplicate issue (#3308) you opened.

Thank you :)

**Comment by Murazaki** [comment] 2015-06-02 14:39
Ok

**Comment by 2-4601** [comment] 2015-06-04 21:32
TS emoji drawer also devours the whole screen when rotating to landscape as explained in #3199

**Closed** 2015-06-11 18:16 UTC
Labels: bug, ux
