### ISSUE TITLE
Emojis Switch doesnt work / show the old ones

### ISSUE THREAD

**Issue by peterpanondrugs** [WhisperSystems/TextSecure#4125] opened 2015-09-25 14:41 UTC
Hi there, like the title tells. switching to the old ones, doesn't show me the the symbol for choosing the emoijis. Restarted phone. and switched on/off. but still not working.

https://gist.github.com/anonymous/4aefd8d17edf21a29344 <-- LOG

![textsecure-2015-09-25-162830](https://cloud.githubusercontent.com/assets/8776733/10103429/39a45dc6-63a4-11e5-84db-7633955e985b.png)

**Comment by 2-4601** [comment] 2015-09-25 15:24
Duplicate of #4101, #4105.

**Closed** 2015-09-25 16:06 UTC

**Comment by peterpanondrugs** [comment] 2015-09-25 16:29
Sorry ! i checked for the issue release date (3 days back) didnt search specificly for...
