### ISSUE TITLE
[Feature Request] More theme

### ISSUE THREAD

**Issue by Sysy1** [WhisperSystems/TextSecure#2322] opened 2015-01-10 14:29 UTC
This application could be better if we could have more theme
https://play.google.com/store/apps/details?id=com.jb.gosms.theme.getjar.glass something like that could be great !

**Comment by moxie0** [comment] 2015-01-10 14:30
Duplicate of #1283. Please check for existing issues before opening new ones.

**Closed by moxie0** 2015-01-10 14:30 UTC
