### ISSUE TITLE
"Delete thread" does not delete images

### ISSUE THREAD

**Issue by cowlicks** [WhisperSystems/TextSecure#2597] opened 2015-03-06 16:27 UTC
I had a very large TS thread with another TS user. Most messages encrypted and sent with push but some were MMS/SMS. 

After trying to delete the thread all the messages with images remained, along with their accompanying text.

**Comment by rhodey** [comment] 2015-03-06 20:35
I'm unable to reproduce this. I threw in some logging [here](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/database/PartDatabase.java#L197) and [here](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/database/PartDatabase.java#L201) and both of the file and thumbnail were deleted on thread delete.

what steps are you taking to check that the files still remain after deleting the thread?

**Comment by rhodey** [comment] 2015-03-13 18:23
closing as non-reproducible, will reopen if any debug logs or further information comes in.

**Closed by rhodey** 2015-03-13 18:23 UTC
