### ISSUE TITLE
Resend undelivered message causes havok

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [WhisperSystems/TextSecure#2724] opened 2015-03-19 17:31 UTC
Hi there, 
I just posted a message in a group that couldn't be delivered due to crapy connection on my side. So the little red exclamation mark appeared next to the message, and when I clicked it I was offered a list of all group members with a resend button next to each name. I figured I had to click each button to make sire everbody received my meaningful braindump. But it turns out that every button seams to resend the message to the entire group. So everybody received 15 times the same message. 
Could the resending not be handled automatically?

**Comment by agrajaghh** [comment] 2015-03-19 17:39
looks like a duplicate of #2639

**Closed** 2015-03-19 17:53 UTC
