### ISSUE TITLE
Receiving vcards with images crashes Textsecure and makes it unusable.

### ISSUE THREAD

**Issue by Richard-W** [WhisperSystems/TextSecure#2252] opened 2014-12-21 12:58 UTC
A contact of mine sent me a vcard that contained an image via MMS. Textsecure downloaded it and displayed the whole ASCII encoded image as text which slowed down the app to the point where it crashed.

Textsecure was not usable until i managed to delete the MMS (on the 5th try it did not crash).

This could be used as some kind of DOS attack i think. Please include some kind of safeguard.

**Comment by rhodey** [comment] 2015-04-10 00:50
closing this as resolved by (in crash, maybe not in feature) #2294 and dupe of #499

**Closed by rhodey** 2015-04-10 00:50 UTC
