### ISSUE TITLE
problem with writing long messages

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#2899] opened 2015-04-05 03:58 UTC
When writing a long message, at some point you become unable to see the conversation and scroll up. It may be my screen that is too small, though it's 4+inches so I guess a lot of people are affected

**Comment by skulumani** [comment] 2015-04-06 13:25
On a related note, with a long message the text box will scroll rather than expand show all of the content. I'm not sure if this is by design or a bug as there are other related open issues.

![2015-04-06 13 21 48](https://cloud.githubusercontent.com/assets/5266022/7004799/c7ce74bc-dc3e-11e4-9222-c010aff837bb.png)

**Comment by 2-4601** [comment] 2015-04-06 16:43
The behaviour of the input box seems to depend on the setting 'Enter key sends' (in Advanced Settings)

If enabled the input box is restricted to one line.

If disabled it can expand to fill the whole screen:
![screenshot_2015](https://cloud.githubusercontent.com/assets/174176/7007724/ecb94d82-dc94-11e4-85a1-91583b2ac8c8.png)

**Comment by volcano99** [comment] 2015-04-07 08:30
Before this last update (or maybe it was a couple of updates, I can't remember) the box would expand to a certain extent, without covering the whole screen. I think that's the behaviour users expect, and that's simply the most logical way to handle it. I would make the box slightly bigger than it used to be, but definitely not as big as to cover the whole screen

**Comment by agrajaghh** [comment] 2015-04-07 11:25
I can confrim that this depends on the "Enter key sends" option

**Comment by schmidtma1010** [comment] 2015-04-10 14:02
I can confirm that through the last update (Android) the behaviour changed, like volcano99 stated.
I usually get longer messages and answer line for line. This is a problem if the textbox grows larger.
The old behaviour to expand the textbox to e.g. half the screen (and then start 'scrolling' mode inside the textbox) was perfect.
Would be perfect if ths could be made at least switchable with an option.
Thank you very much .-)

**Comment by volcano99** [comment] 2015-04-17 15:15
Please fix this, it's really important that you can see what messages you're answering while typing.
Why was this changed in the first place? Why would you make the text box expand indefinitely...

**Comment by skulumani** [comment] 2015-04-17 15:26
I think it is fixed by using the option "Enter key sends text"?

You can have a non expanding input box, or an expanding box.

**Comment by volcano99** [comment] 2015-04-17 16:00
But I don't want to send when I hit Enter. I want to go on a new line...

**Comment by schmidtma1010** [comment] 2015-04-17 18:53
Yes exactly, I totally agree with volcano99. IMHO the option to send with enter key, should not change the input box size.
Maybe there could be a setting to have an expaning input box or to have a static (but more than one line - maybe 4, like before) input box?

**Comment by 2-4601** [comment] 2015-04-17 19:21
The input box in other popular messengers seems to work as follows:
- expand as the user enters more text
- do not expand to cover the whole screen so the user can still see previous messages

Perhaps this is how it was before. I never paid that much attention to it. Possibly because it just worked.

The _'Enter key sends'_ setting should not affect the expanding behavior.

Adding a new setting for different expanding features would just add unnecessary complexity.

**Comment by schmidtma1010** [comment] 2015-04-18 11:29
Yes, that was the behavior before.

I tried to search the commit which changed it, but could not find it. But I guess it was v2.7.1 Where it first appeared.

**Comment by schmidtma1010** [comment] 2015-04-18 11:43
Ok, I guess the following commit could have introduced it: https://github.com/WhisperSystems/TextSecure/commit/2f20bb89f3b64701d047fa3af2aa8b6e0ecfdc34
textMultiLine is removed there. I am not so into the sourcecode of TextSecure but I think that could be the problem.

**Comment by 2-4601** [comment] 2015-06-04 21:16
This issue has been resolved: ef9cc680f0d15169b70e979237e5258f611c5adc

**Closed** 2015-06-04 21:17 UTC
Labels: ux

**Comment by volcano99** [comment] 2015-06-04 21:19
(I never got the money by the way, just saying this in case any future contributor reads this. Also tried contacting moxie but got no answer)

**Comment by rhodey** [comment] 2015-06-04 21:44
@volcano99 coinbase should have sent an email to the address you use for your github account, are you sure no email came in?

**Comment by volcano99** [comment] 2015-06-05 07:35
Yes, I am sure. I also mentioned it here https://github.com/WhisperSystems/BitHub/issues/28
Not that I did it for the money, but I thought it would be fair to let people know -- especially since I got no support from moxie.

**Comment by moxie0** [comment] 2015-06-05 15:58
@volcano99 Dude, you have your commit email address set to volcano99@users.noreply.github.com.
