### ISSUE TITLE
Automatically resend undelivered messages

### ISSUE THREAD

**Issue by janvlug** [WhisperSystems/TextSecure#2098] opened 2014-11-15 18:21 UTC
Since the delivery confirmation functionality has been implemented, I sent 48 messages. For 3 of these, I did not get a confirmation that they have been delivered.

It would be nice if messages are automatically resent if no delivery confirmation is received. Especially, if later messages to the same recipient do get a delivery confirmation, indicating that the recipient is reachable again.

**Comment by rbu** [comment] 2015-01-02 19:32
@manhole11, do you have a specific other application in mind that uses GCM and does not exhibit this problem? Do you know whether they have implemented retransmissions themselves?

**Comment by manhole11** [comment] 2015-01-02 19:35
I don't know which other apps I have use GCM, the only thing I know is that textsecure is the only one having so many problems and I'll ditch it as soon as hemlis will be released. If GCM is the problem, then use something else. I mean, it's a problem of the developers. I don't care that much; all I care about is having an app that works and hemlis works :)

**Comment by devurandom** [comment] 2015-01-06 07:23
Copying my issue description from #2293:

> Currently message delivery is unreliable. It often happens that I send a message to someone, but do not get a message receipt (check-mark icon). Messages sent later get a receipt. When I talk to the person a few hours later, they tell me they did not receive the message.
>
> This issue is not limited to me sending, but also happens the other way around. It also happens for other people, as I have been told. It also happens for the message receipts themselves – sometimes a message arrives on my phone, but the sender never receives the receipt. The CyanogenMod integrated WhisperPush service is not involved. The issue happens between stock Android users, as well as with CyanogenMod users.
>
> From reading other issues I understand that GCM does not offer reliable delivery. I wonder if the equivalent of XEP-0198 section 4 "Acks" could be implemented on top of it in TextSecure.
>
> Possible duplicates: #679, #970, #1971, #2098, #2238

**Comment by janvlug** [comment] 2015-01-21 21:13
After some more investigation, I discovered that TextSecure at the recipients end crashes quite often while the app is in the background or the phone is suspend mode (see #2037). So in my case GCM is not the culprit.
However, I made also the observation that messages sent to the user where TextSecure stopped working do not arrive anymore when TextSecure is started again. I would expect that GCM would still try to deliver them.
However, whatever the cause of delivery problems is, GCM or TextSecure itself, it still would be great if additional attempts are made to resend the message until its delivery is confirmed. And yes, I understand that TextSecure cannot keep trying into eternity.

**Comment by rhodey** [comment] 2015-03-13 23:24
on second thought closing as dupe of #2015

**Comment by janvlug** [comment] 2015-03-14 14:30
@rhodey: I'm not convinced that this is a dupe of #2015. This issue is not about the unavailability of a data connection, but about the fact that a message confirmation never arrives. The absence of a message delivery notification indicates that the message could not have reached the recipient.

**Closed** 2015-10-01 21:59 UTC
Labels: feature
