### ISSUE TITLE
TextSecure marks messages as delivered before they are even sent (?)

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#2964] opened 2015-04-13 09:08 UTC
Hi, I've always wondered why this is, but just figured it may be some sort of bug. Like 80% of the time, the messages I send get the delivery receipt symbol (the check mark) "way" before they turn blue (meaning they have been sent). Basically I send a message, it is shown as pending, it gets the delivery check mark, and then it is shown as sent. And this happens all the time, way more than just half the time.
I thought messages turned blue after they'd reached the server, and got the check mark once they'd been delivered. But how is it possible that going from my phone to the recipient's phone and back takes less than going from my phone to the server and back? Sometimes I get the delivery receipt several seconds before the message is marked as sent. Is this some problem with the server being slower at some tasks than others, or is it some problem with the client?
Thank you

**Comment by wp9015362** [comment] 2015-04-13 11:27
I have the exact opposite issue...

For me messages are being marked as received way after they have been sent.

It's as if the the messages are not being delivered in real-time and take their time.

It doesn't feel like instant messaging.

In Telegram for Android for examle, everything happens instantly in compariosn. It feels more like an instant messenger than TextSecure does.

But Telegram for Android has it's own notification service and does not depend on GCM, see:

https://twitter.com/telegram/status/478487472750755840

I don't really understand why TextSecure still depends on GCM even though Telegram for Android already works beautifully without it.

**Comment by volcano99** [comment] 2015-04-13 12:20
What you're talking about is a different issue... and we get it, Telegram is better when it comes to user experience and reliability and design etc. But we're using textsecure because we care about security. Maybe though, since telegram is free software, the textsecure developers may borrow some code to fix the notification issue.
However, that was not the topic of my post.

**Comment by moxie0** [comment] 2015-04-13 16:10
@wp9015362 Your activity here is really testing the patience of TextSecure developers. Consider trying to be less verbose, staying on-topic, and only posting when you have new, concise, on-topic information that is necessary for resolving an issue. This has been a recurring problem with you, if you don't stop annoying people we'll have to ban you from the repos.

@volcano99 If the person you are communicating with has the app open, you should see the delivery receipt and the send complete actions happen almost simultaneously.  If the person you're communicating with doesn't have the app open, you should see the send complete action before the delivery receipt.

If you're sending a *group* message, it's common to see the delivery receipt come in first. That's because some people in the group have already received the message before you've finished sending to everyone in the group.

Are you referring to individual or group messages?

**Comment by volcano99** [comment] 2015-04-13 16:15
I knew that about group messages, but you're right I should have clarified.
I am talking about individual messages. Sometimes it's almost simultaneous (yet the checkmark almost always comes first), but some other times several seconds pass. Like 3 or 4 seconds. I don't know if that's considered a "long time", but it feels a bit weird. It's not a huge problem, just not what people are used to, you know?

**Comment by volcano99** [comment] 2015-04-18 08:04
It may be a problem with slow graphic. I noticed that when I send a message and press home, wait several seconds so that it is sent and delivered, and then reopen ts, I can see for a fraction of a second the message in the light blue color, before it turns blue. Maybe changing the color is slightly slower than adding the delivery check mark to the bubble? Just a guess. (maybe the two things are unrelated)
I don't know what this is all about but it gives you the feeling that textsecure is way slower than it actually is. Assuming both sender and receiver are online, it should take the changing of color half the time it takes for the delivery check mark to be displayed. Correct? So that means that textsecure is pretty fast, despite the messages being colored as sent after several seconds.
Do you know what the problem could be?

**Comment by devurandom** [comment] 2015-05-26 09:13
Same issue here. It persists for at least nine minutes. http://i.imgur.com/aZ9pfEm.jpg

**Comment by devurandom** [comment] 2015-05-26 09:14
P.S. Both messages were sent at the same time.

**Comment by volcano99** [comment] 2015-05-26 09:20
Was the first message delivered though?

**Comment by devurandom** [comment] 2015-05-26 11:35
My peer confirmed that both messages arrived by now, and both are now marked as sent on my phone, but the second message lost the received checkmark: http://i.imgur.com/uzgivZY.jpg

**Comment by volcano99** [comment] 2015-05-26 11:37
So this seems related to #3014, interesting

**Comment by devurandom** [comment] 2015-05-26 14:18
It happened only once so far. At least it was the first time I noticed it.

**Comment by oaim** [comment] 2015-06-30 11:49
This should be fixed in 2.21, as the delivered icon replaces the sent one. However only the graphic problem has been fixed, don't know about what's happening "under the hood"

**Comment by riyapenn** [comment] 2015-09-24 22:17
See also #2238

**Closed** 2015-10-22 19:40 UTC
