### ISSUE TITLE
When taking an image using embeded photo taker it gives me an image with a lot of green vertical line

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/TextSecure#4368] opened 2015-11-04 00:43 UTC

**Comment by mcginty** [comment] 2015-11-04 00:44
Hey @TheNain38, please remember to include more verbose debugging information otherwise we can't act on these kinds of reports.

https://github.com/WhisperSystems/TextSecure/wiki/Submitting-useful-bug-reports

Thanks!

**Comment by mcginty** [comment] 2015-11-04 00:45
Likely a dupe of #3752

**Closed by mcginty** 2015-11-04 00:44 UTC

**Comment by TheNain38** [comment] 2015-11-04 00:47
Oh, thanks, didn't seen that issue
