### ISSUE TITLE
Option to change vibrate pattern and length

### ISSUE THREAD

**Issue by karlhedderich** [WhisperSystems/TextSecure#3923] opened 2015-08-10 20:10 UTC
I have a friend that complained about the length of how long textsecure vibrates the phone when he gets a new message.  He wanted an option to change the pattern and length of the vibration.

**Comment by moxie0** [comment] 2015-08-10 20:16
duplicate of #230, please check existing issues before opening new ones

**Closed by moxie0** 2015-08-10 20:16 UTC
