### ISSUE TITLE
Recieved picture thumbnails differ from send ones

### ISSUE THREAD

**Issue by bvorak** [WhisperSystems/TextSecure#2689] opened 2015-03-14 21:38 UTC
2.7.0-B1 on a Galaxy S2 - Android 4.1.2

Could be somehow related to #2676 and  #2678 ?

When I send a picture it looks quite good with the new thumbnail view in a conversation.
All of the pictures I recieve on the other hand have way to less width in conversation and detail view.

An example with a picture sent to myself:
![screenshot_2015-03-14-10-18-00](https://cloud.githubusercontent.com/assets/7289329/6653650/9e5ca110-ca57-11e4-81de-8c0a5f20ecaa.jpg)

Would you like to have a debug log on this?

**Comment by mcginty** [comment] 2015-03-15 01:24
Yep, dupe of https://github.com/WhisperSystems/TextSecure/issues/2676. Thanks for your well-formatted issue though :).

**Closed by mcginty** 2015-03-15 01:24 UTC
