### ISSUE TITLE
Copy text copies incorrect message.

### ISSUE THREAD

**Issue by garrettgrimsley** [WhisperSystems/TextSecure#508] opened 2013-12-24 20:02 UTC
This bug only appears to be present when the Android OS opens a dialog. 
Using a long-press, I try to select a phone number that someone text me, but KitKat opens the "Complete action using" dialog. 
After dismissing the KitKat dialog the TextSecure dialog
* Copy text.
* Delete message.
* Message details.
* Forward message.  

appears.
I select "copy text" and it copies text that wasn't even on my screen.  
If I select a part of the message that doesn't open the KitKat dialog this bug does not occur.

**Comment by rhodey** [comment] 2015-03-16 20:51
I'm unable to reproduce this on my Nexus 5 running stock Lollipop and TS 2.6.4, anyone else still having this issue?

**Comment by dhermosillo** [comment] 2015-03-16 22:33
Yes, it's even worse in the newest release of TS.  Now the copy function blinks away before the user has time to select it.

**Comment by rhodey** [comment] 2015-04-10 21:47
the issue described by @dhermosillo is documented in #2333, closing this issue as resolved.

**Closed by rhodey** 2015-04-10 21:47 UTC
