### ISSUE TITLE
Export of key was removed when you removed encrypted backups

### ISSUE THREAD

**Issue by Waboru** [WhisperSystems/TextSecure#3264] opened 2015-05-27 16:29 UTC
Hello,

I'm not able to export my key anymore since you removed the encrypted backup.

My friends are really annoyed by this. I'm flashing a lot of Custom Roms and every few weeks my key is gone and every of my 20+ contacts has to verify again that this is me and no MITM attack.

Could you please add the export of the key again?

**Comment by moxie0** [comment] 2015-05-27 21:14
Duplicate of #1705.  Please check existing issues before creating new ones, it's a lot of work for us to clean these up.

**Closed by moxie0** 2015-05-27 21:14 UTC
