### ISSUE TITLE
Please add status and Photo to Userprofile

### ISSUE THREAD

**Issue by LuPiToX** [WhisperSystems/TextSecure#3367] opened 2015-06-07 20:56 UTC

**Comment by 2-4601** [comment] 2015-06-07 21:17
status: duplicate of #3252 
profile photo: duplicate of #706, #916

**Comment by moxie0** [comment] 2015-06-08 05:20
@LuPiToX Please check for existing issues before opening new ones.  Cleaning these up takes a lot of our time.

**Closed by moxie0** 2015-06-08 05:20 UTC
