### ISSUE TITLE
CrashBrowser: CursorWindow IllegalStateException

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2759] opened 2015-03-23 20:59 UTC
Pretty common, been happening for a while.

`````
java.lang.IllegalStateException: Couldn't read row 1768, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java:511)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
at android.support.v4.widget.CursorAdapter.getItem(CursorAdapter.java:213)
at org.thoughtcrime.securesms.ConversationAdapter.getItemViewType(ConversationAdapter.java:129)
at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:6494)
at android.widget.AbsListView.obtainView(AbsListView.java:2343)
at android.widget.ListView.makeAndAddView(ListView.java:1864)
at android.widget.ListView.fillUp(ListView.java:732)
at android.widget.ListView.layoutChildren(ListView.java:1654)
at android.widget.AbsListView.onLayout(AbsListView.java:2148)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
at android.view.View.layout(View.java:15606)
at android.view.ViewGroup.layout(ViewGroup.java:4968)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1077)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5884)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
`````

**Comment by moxie0** [comment] 2015-04-16 23:55
Still happening in 2.11.1

**Comment by rhodey** [comment] 2015-04-20 17:15
@moxie0 can you determine in which version this began?

[this blog post](http://blog.tapreason.com/2014/03/02/how-to-resolve-java-lang-illegalstateexception-couldnt-read-row-0-col-y-from-cursorwindow-make-sure-the-cursor-is-initialized-correctly-before-accessing-data-from-it/) describes how it could be an issue with default values on primitive typed columns.

the [couchbase-lite-android](https://github.com/couchbase/couchbase-lite-android/issues/210) project has some stacktraces that look very similar to ours and a lot of discussion on the topic. I think the `row > 0 && col == 0` is a key trait which both issues share.

**Comment by moxie0** [comment] 2015-04-20 17:21
Looks like its been happening for a while

**Comment by rhodey** [comment] 2015-04-20 17:23
@moxie0 also, are you seeing anything eluding to high memory consumption in these stack traces? If we also found that in our traces I think it is a pretty strong match to the couchbase 210 issue. They documented their bug very specifically [in this android issue](https://code.google.com/p/android/issues/detail?id=68344), are we also only seeing this on 4.1 - 4.2.2?

**Comment by rhodey** [comment] 2015-04-23 22:49
update, not limited to Android 4.1 - 4.2.2, so no good leads on this yet.

**Comment by rhodey** [comment] 2015-04-24 18:14
closing as duplicate of #2507

**Closed by rhodey** 2015-04-24 18:14 UTC
