### ISSUE TITLE
Feature Request: Back up & sync services

### ISSUE THREAD

**Issue by aesahaettr** [WhisperSystems/TextSecure#3952] opened 2015-08-17 00:18 UTC
I think it would be great to allow us to back up & sync our messages using services like Dropbox, Google Drive, etc. so that when we log into another device they are there. This is also useful even if you only use one device so that important information you use TextSecure for isn't lost if your device breaks or is stolen. Always good to have a backup!

**Comment by moxie0** [comment] 2015-08-17 01:39
Duplicate of #339.  Please check existing issues before opening new ones.

**Closed by moxie0** 2015-08-17 01:39 UTC
