### ISSUE TITLE
Ancient unsent messages sent after update

### ISSUE THREAD

**Issue by coofercat** [WhisperSystems/TextSecure#818] opened 2014-02-27 10:00 UTC
Yesterday morning my phone auto-updated TextSecure. I noticed the icon had just changed to the circular one, so clicked it, and authenticated. I followed the one-time process of registering on the server, and all seemed normal.

Later, i found out that a message I'd sent on the 18th december (to two recipients) had just been received by them. I presume it had failed to send back in december due to bad signal or some such, and the software update had just tried it again (I know where I was when I sent the message has little or no signal a lot of the time).

Seeing as the message was "I'm in the pub" and was sent at 8.15am, it lead to a few probing questions about my drinking habits ;-)

Anyway, I doubt this is the sort of thing we can track down and "fix", but I thought I'd mention it and see if anyone else was affected.

TextSecure is showing version 2.0.2 right now, although I think it updated again during the night, so I'm not sure exactly which version sent the ancient unsent messages.

**Comment by rhodey** [comment] 2015-03-16 20:02
closing as unable to reproduce and no debug log. also in the case of SMS and MMS it is entirely possible that messages will be delivered late, this is a function of the cell network and there isn't much we can do from the app to prevent this.

**Closed by rhodey** 2015-03-16 20:02 UTC
