### ISSUE TITLE
Opening video fails

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#2889] opened 2015-04-04 07:21 UTC
Hi, I am using TextSecure on Android (2.10.1). A friend of mine has sent me a video through the Signal app for iOS (via push), but I don't seem to be able to open it. All I can see is a bubble with the video icon (not a preview of the video, just an icon saying it's a video). When I click on it, I am asked if I want to temporarily copy it to the disk etc, I say 'yes', the default video player loads and then closes itself in a couple of seconds, saying that "an error occurred". This may have something to do with the fact that when my friend sent the video my connection was really bad/absent, though one would expect the application to retry until the attachment has been properly downloaded (but maybe this is not the point).
Thank you

**Comment by McLoo** [comment] 2015-04-04 07:35
Try different video players?

**Comment by volcano99** [comment] 2015-04-04 08:02
I don't have any other video players... but I have an update. Saving the video to the unencrypted storage and then opening it works fine, so at least I was able to see it.

**Comment by agrajaghh** [comment] 2015-04-04 08:40
I can reproduce this on Android 5 and Android 2.3.7 (wasn't easy to find a video below 280KB :smile:)

**Comment by oholika** [comment] 2015-04-04 09:43
Duplicate of https://github.com/WhisperSystems/TextSecure/issues/2706

**Closed** 2015-04-04 16:17 UTC
