### ISSUE TITLE
Feature request: Bigger attachments

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/TextSecure#2780] opened 2015-03-25 14:56 UTC
I hope I die not oversaw something Ehen searching after the same request.

The attachments can't be bigger than 280 KB, but that's not much for a Video file.
Even 3 seconds from my front facing camera produce a bigger file.

Are there ans reasons for this limit?

Regards

**Comment by agrajaghh** [comment] 2015-03-25 15:35
duplicate of #700

The 280 KB are a size limit for MMS, but increasing the attachment size for push messages is on the roadmap as far as I know...

**Comment by mawed** [comment] 2015-03-25 15:38
Oh sorry, I searched general for attachments, not Video only.

Thanks for the repsond

**Closed** 2015-03-25 15:38 UTC
