### ISSUE TITLE
In-thread Notification incorrectly applied when screen is locked but conversation still open

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/TextSecure#1965] opened 2014-10-01 15:18 UTC
First of all, the technical details:
Nexus S (Crespo) with CyanogenMod 11-20140916-SNAPSHOT-M10-crespo, Android 4.4.4

Now the problem:
It seems, that TextSecure doesn't notify me about new received Messages when i lock the Phone while keeping the Conversation open, even if the Option "In-thread notifications" is checked.
No Vibration, no Sound and no Icon in the status Bar.

**Comment by mcginty** [comment] 2015-02-16 06:46
dupe of #1371

**Comment by mcginty** [comment] 2015-02-16 07:59
Reopening and changing title to not re-confuse myself :)

**Comment by TWfromSWD** [comment] 2015-02-17 14:05
Since some time had passed since i created this issue, i tried to reproduce the bug. With my current Phone, Nexus 5, Cyanogenmod Snapshot M11, the notifications worked fine, even when the thread was still open when locking the Phone.
So maybe the bug disappeared due to changes in the notifications or its because of the new System and Phone.

**Comment by mreppen** [comment] 2015-02-17 14:19
I have had the problem (I believe fairly recently) with stock Nexus 5. It could have been fixed in one of the latest updates, but I'll try to see if I can reproduce as soon as I meet someone to test with.

**Comment by rhodey** [comment] 2015-05-29 22:40
I've also been trying and unable to reproduce this bug for sometime with no success, closing as resolved. if someone is still having this issue please comment here and I will reopen.

@mreppen :3 hope you found a TextSecure or Signal friend.

**Closed by rhodey** 2015-05-29 22:40 UTC
