### ISSUE TITLE
SMS fallback

### ISSUE THREAD

**Issue by TurkeyMan** [WhisperSystems/TextSecure#3075] opened 2015-04-28 15:23 UTC
TextSecure should attempt to send a message securely. If it can't, a popup informs the user it failed to send, and the user has an option to retry later, or send insecurely (via SMS) immediately.
There should also be a "remember my choice" checkbox, and an option in the settings.

**Comment by moxie0** [comment] 2015-04-28 16:36
Duplicate of #2847. Keep doing this and we'll ban you from the organization.

**Closed by moxie0** 2015-04-28 16:36 UTC
