### ISSUE TITLE
extremely high battery/power usage

### ISSUE THREAD

**Issue by graingert** [WhisperSystems/TextSecure#1357] opened 2014-04-13 20:29 UTC
TextSecure seems to have extremely high battery/power usage on my Nexus 5, the greatest of any other app on my phone.

![Gsam power usage](http://i.imgur.com/rM9yMgW.png)

**Comment by mcginty** [comment] 2015-03-10 19:29
Closing as dupe of #2498. If someone is still having this issue and can dump battery stats that don't match the root cause of #2498, please open another issue. Thanks!

**Closed by mcginty** 2015-03-10 19:29 UTC
Labels: performance
