### ISSUE TITLE
Please add blacklist support at least

### ISSUE THREAD

**Issue by bonedriven** [WhisperSystems/TextSecure#3243] opened 2015-05-23 09:34 UTC
A commercial ad sms kept coming through to textsecure although I blocked the number with android blacklist. It seems textsecure needs to have it blocked as well? But I found no option for blacklist numbers. As it is used as the default sms app, blacklist is a must.

**Comment by 2-4601** [comment] 2015-05-23 10:24
Duplicate of #222.

**Closed** 2015-05-23 12:22 UTC
