### ISSUE TITLE
search messages

### ISSUE THREAD

**Issue by bntspcht** [WhisperSystems/TextSecure#3598] opened 2015-07-10 10:52 UTC
when you click at the magnifier in the main screen textsecure should search all messages instead of searching a contact.

why?

(1) because it is an inbox of messages and most email-programs behave like this
(2) when you compose a new message then you already got a contact search
(3) nearly every android smartphone has a contact manager where you can search for contacts and open the corresponding chat from there (if you've set ts as the standard messenger you'll be redirected to ts..)

**Comment by moxie0** [comment] 2015-07-10 15:35
dupe of #1232

**Closed by moxie0** 2015-07-10 15:35 UTC
