### ISSUE TITLE
Some images fail to send every time (Like #3028)

### ISSUE THREAD

**Issue by turion** [WhisperSystems/TextSecure#3070] opened 2015-04-27 15:34 UTC
I reported a similar issue in https://github.com/WhisperSystems/TextSecure/issues/3028, and it seemed to be fixed at first when I updated, but the issue is occurring again. I'm a bit confused as to whether this should be fixed in 2.12 or 2.13, so if it's fixed in 2.13, I'll be happy to close (and reopen if the issue persists).

Can I test 2.13 without joining Google+?

**Comment by rhodey** [comment] 2015-04-27 20:17
It should be fixed in 2.13 which has yet to be released on Google Play. I was not able to find a way into the beta testers group without using google+ -__- the only working instructions that I'm aware of are in the README.md in this repo.

I feel that it makes sense to keep this issue open until we have a confirmed fix, wanna check back in once you get the 2.13 update and let us know?

**Comment by rhodey** [comment] 2015-05-07 23:23
@turion did you get a chance to update to 2.13? are you still experiencing this issue?

**Comment by turion** [comment] 2015-05-08 07:58
I updated, but I'm still "testing". I had one crash so far after sending an image, but the image was sent afterwards. I'll have to test with more images, then I'll report back, thanks!

**Comment by turion** [comment] 2015-05-08 21:23
There are still problems. Here is a log from my girlfriends phone: https://gist.github.com/anonymous/98218362f3cee36df5b5
She is having trouble with sending the same image, some other images work, though.

**Comment by turion** [comment] 2015-05-10 08:03
I got hold of the unsendable image, and there seems nothing wrong with it (except possibly that it's 4.8 MB big). I tried to send it from my phone and it fails as well. Here is my log: https://gist.github.com/107eec3db4f58dd06b0e

**Comment by mcginty** [comment] 2015-05-10 08:14
@turion thanks for your investigative work! `java.io.IOException: Unable to scale image below: 335787` - is this image particularly complex? It looks like the resizer can't compress it to 280k and that's the problem. We may need to revisit those limits if regular pictures can't be compressed correctly.

**Comment by turion** [comment] 2015-05-10 08:32
No, it's just a picture of a dog in the grass. It's in a high
resolution, but still just from a phone camera, so a regular usecase.
280k seems quite small. I can understand you want to save server data
volume, but I think increasing the limits would do good.

**Comment by turion** [comment] 2015-05-17 10:23
Issue persists in version 2.14: https://gist.github.com/5f9f2cb53126078ed1dd

**Comment by jeremymasters** [comment] 2015-05-17 22:37
Grass has a lot of detail and is harder to compress than say blue sky.

**Comment by turion** [comment] 2015-05-18 07:59
True. And since grass is present in a lot of photos taken daily, TextSecure should be able to handle it. In the worst case, one could apply a Gaussian blur whenever the image doesn't compress enough. That should reduce the detail.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2015-06-03 18:19 UTC
