### ISSUE TITLE
duplicate message causes ciphertext to be shown in preview snippet

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/TextSecure#2390] opened 2015-01-26 21:22 UTC
In the Conversation view, you see "duplicate message," but the summary in the conversation list is displaying garble.

**Comment by KommX** [comment] 2015-03-03 21:47
Seems to be a duplicate of #2269.
But I also would like to know what causes this problem.

**Closed** 2015-03-04 20:27 UTC
