### ISSUE TITLE
Support for multiple recipients without creating groups or support for local groups 

### ISSUE THREAD

**Issue by uiken** [WhisperSystems/TextSecure#3845] opened 2015-07-30 16:04 UTC
In TextSecure, if I want to send the same message to multiple persons I can create a group first and send the message to the group. However then everyone in the group becomes aware that it is a group message -- in other words groups are always global. It would be nice to either send to multiple recipients without the need for creation of groups (I think this has already been requested) or allow the creation of groups which are local, so that we can send the same message to multiple people without the recipients being aware of the fact.

**Comment by 2-4601** [comment] 2015-07-30 17:01
Broadcast lists duplicate of #3301.
I don't understand the difference to "local groups"?

**Closed** 2015-07-30 17:04 UTC

**Comment by uiken** [comment] 2015-07-31 02:09
By "local groups", I meant "broadcast lists" exactly. But I didn't know the terminology. sorry!
