### ISSUE TITLE
Some images fail to send every time (OOM)

### ISSUE THREAD

**Issue by turion** [WhisperSystems/TextSecure#3028] opened 2015-04-21 17:44 UTC
There are some images that I just can't get to send over TextSecure push. No matter whether on WiFi, no matter whether I hit retry or create a new message with the same image, it's always "Failed to send". Here is the log:
https://gist.github.com/anonymous/f74e7b419ecd8f692935
Strangely, other images work fine. Are the images that I want to send to large or something like that? Is there a size limit on images over PUSH? If yes, it would be helpful to say that in the error message and even offer to send a compressed version.

**Comment by turion** [comment] 2015-04-21 20:04
Maybe it helps if I give you the link to one of the images: http://83.169.45.231/owncloud/index.php/s/1gG4o44fkepmY1I
Have a look whether you can send it from your phones.

**Comment by rhodey** [comment] 2015-04-21 21:36
thanks for the extra context @turion. the debug log you included in your issue report is great, it shows that this bug is caused by an out of memory error while attempting to scale down your image. so as you expected, this is related to the size of your image. @mcginty is working on a change that will improve TextSecure's bitmap processing, I expect it will solve your problem when complete. I think we have all the info we need with this bug for now :) thanks for the detailed report.

**Comment by mcginty** [comment] 2015-04-23 00:28
@turion we have some changes coming out in the next version that may help this memory issue. I'm going to close this, but please reopen if you get v2.12.0 of TextSecure and this is still happening!

**Closed by mcginty** 2015-04-23 00:28 UTC
Labels: bug

**Comment by agrajaghh** [comment] 2015-04-23 05:00
v2.13.0, no?

**Comment by rhodey** [comment] 2015-04-23 05:50
v2.13.0 for sure :) f42d100f153c50ce19709767233af6f0e9795e46

**Comment by mcginty** [comment] 2015-04-23 06:02
excuse the typo!

**Comment by turion** [comment] 2015-04-23 10:37
So far it seems to work :) good job! This is how open source should work.
