### ISSUE TITLE
Verified Contact

### ISSUE THREAD

**Issue by Ste4thOverride** [WhisperSystems/TextSecure#2990] opened 2015-04-14 23:08 UTC
Please add an indicator to show contacts that you have manually verified. An example would be something similar to the way Threema shows one red dot for unverified contacts, two yellow dots for contacts synced using address book matching ,and three green dots for contacts verified in person.

**Comment by Ste4thOverride** [comment] 2015-04-14 23:12
https://threema.ch/en/faq under what do the three dots under a contact mean.

Security is great and all but verifying the person on the other is is actually the person on the other end is just as important,and an indicator of such would be great.

**Comment by mcginty** [comment] 2015-04-15 01:43
dupe of #910

**Closed by mcginty** 2015-04-15 01:43 UTC
