### ISSUE TITLE
Self sends get notified after some time 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#4089] opened 2015-09-19 01:53 UTC
Bit in a hurry, so short :
Send self non sms 
Leave TS 
After some time the self send is notified

**Comment by McLoo** [comment] 2015-09-19 19:31
Ahh, the notification rides along with another,  regulations one or seems. 
Thread is shown as unread  but once notified, the self sent notification waits for being tapped...

**Comment by Dyras** [comment] 2015-09-21 14:36
https://github.com/WhisperSystems/TextSecure/issues/3877

**Comment by mcginty** [comment] 2015-09-21 20:34
we'll call this a dupe of #3877

**Closed by mcginty** 2015-09-21 20:34 UTC
