### ISSUE TITLE
no way to override old/wrong key by scanning

### ISSUE THREAD

**Issue by ThomasWaldmann** [WhisperSystems/TextSecure#1523] opened 2014-05-22 20:00 UTC
it should be possible to override a stored key by scanning a new one.
but it just says "warning, the scanned key does not match!".

if the user knows that the old key is outdated/gone, it should be possible to say "use the scanned key" at this place.

**Comment by rhodey** [comment] 2015-03-16 18:31
unable to reproduce, lacking debug log, and rather old. closing.

**Closed by rhodey** 2015-03-16 18:31 UTC
