### ISSUE TITLE
Barcode verified users should be marked as "verified"

### ISSUE THREAD

**Issue by mr-gosh** [WhisperSystems/TextSecure#2965] opened 2015-04-13 09:43 UTC
In the icon of the user in the list view should be some kind of marker thats visualises that the user was verified some time in the past by the barcode scanner...

So we could add more trust into "verified user"
or we can even filter for "trusted users" only...

**Comment by 2-4601** [comment] 2015-04-13 09:59
Duplicate of many issues. Most notably #910

**Comment by mr-gosh** [comment] 2015-04-13 12:54
sorry - searched for the wrong stuff i think :-(

**Closed** 2015-04-13 16:11 UTC
