### ISSUE TITLE
f-droid distribution

### ISSUE THREAD

**Issue by strk** [WhisperSystems/TextSecure#3954] opened 2015-08-17 13:36 UTC
I was surprised by not finding TextSecure available via f-droid.org, which is to my knowledge the best service to manage free software packages for android. It would be nice to be able to install TextSecure using that channel.

**Comment by oaim** [comment] 2015-08-17 13:52
Man, there have been hundreds of issues like this. Everywhere. I'll paste a link I found in about 10 seconds, but I'm sure you can find many many more. http://support.whispersystems.org/customer/portal/articles/1476204-why-do-i-need-google-play-installed-to-use-textsecure-on-android-

**Comment by strk** [comment] 2015-08-17 14:14
I wanted to add my own voice to the others... not willing to have
a google account in order to use "secure" software.

**Comment by agrajaghh** [comment] 2015-08-17 14:57
duplicate of #127 (found in >10s as well) including reasons why its not there....)

**Comment by moxie0** [comment] 2015-08-17 15:43
@strk So you're saying you've intentionally opened a duplicate issue, thanks for wasting our time.

**Closed by moxie0** 2015-08-17 15:43 UTC
