### ISSUE TITLE
Fake Password

### ISSUE THREAD

**Issue by Basti420** [WhisperSystems/TextSecure#2683] opened 2015-03-14 11:19 UTC
Sometimes you maybe forced to hand out your password to people like government agencies. In this case it would be really nice to have a second fake password. This fake password will only give acces to some fake messages which dont contain any informations that you try to keep secret. Basically like an hidden truecrypt volume.

**Comment by agrajaghh** [comment] 2015-03-14 12:08
related to #175 and #1512 
I thought there was a real duplicate of this isse too, but couldn't find it anymore...

**Comment by moxie0** [comment] 2015-03-14 16:31
Thanks but we're not going to do this.

**Closed by moxie0** 2015-03-14 16:31 UTC
