### ISSUE TITLE
How do I send a message to several people WITHOUT creating a group?

### ISSUE THREAD

**Issue by sicofante** [WhisperSystems/TextSecure#3495] opened 2015-06-30 00:42 UTC
I'm not interested in groups. It's the very feature why I run away from Whatsapp. It creates too much noise. I'm not interested in having a chat room, which is what groups seem to be like (yes, I'm *that* old).

But I do want to send messages to several people at once in many occasions. Is that possible at all with Textsecure? How do I do that?

**Comment by moxie0** [comment] 2015-06-30 01:02
Duplicate of #3301

**Closed by moxie0** 2015-06-30 01:02 UTC
