### ISSUE TITLE
Swipe to change conversations

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3043] opened 2015-04-23 17:32 UTC
Hello, it would be really nice if it was possible to swipe left/right in conversations to reach the next/previous conversation in the list. It would be like having a tab-like system, similar to (but not the same as) what surespot does.
For example, if I opened the second conversation in the list, swiping right would take me to the first one and swiping left would take me to the third one. This would make it easier to text 2+ people at the same time.
Of course it's not a priority, just a thought.

**Comment by rhodey** [comment] 2015-04-23 17:38
thanks for the suggestion @volcano99 but closing this as a dupe of #584, I'd like to see it too :)

If you have any suggestions to how the UX of this should work please do discuss them in 584.

**Comment by volcano99** [comment] 2015-04-23 17:39
My apologies!

**Closed by rhodey** 2015-04-23 17:38 UTC
