### ISSUE TITLE
Cannot paste into empty text field

### ISSUE THREAD

**Issue by Sweater-Baron** [WhisperSystems/TextSecure#2523] opened 2015-02-25 06:52 UTC
When I'm composing a text, I'm not able to access the copy/paste context menu if the text field is empty. I'll hold down my finger in the text box, and the copy/paste dialog will either not pop up at all, or it will appear briefly, but disappear before it can be used. However, it works just fine if the text field has any text in it.

Can anybody reproduce this on their model?

My device info:
Model: LG G3 (model no: LGLS990)
OS: Android 5.0.1
TextSecure version: 2.5.3

**Comment by McLoo** [comment] 2015-02-25 08:54
Works for me on Android 5.0.2 and 4.4.4.
Does this also happen when you copy text from another *text only* message and try to insert?

**Comment by moxie0** [comment] 2015-02-25 17:31
We've seen a few reports of this, but can't reproduce it on any of our devices.

**Comment by JavaJens** [comment] 2015-02-25 18:18
I can reproduce this problem, but not reliably and I don't know a way to debug this.

**Comment by moxie0** [comment] 2015-02-25 18:19
@JavaJens do you also have an LG device?

On 02/25/2015 10:18 AM, JavaJens wrote:
> I can reproduce this problem, but not reliably and I don't know a way to
> debug this.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/2523#issuecomment-76022190>.
> 

-- 
http://www.thoughtcrime.org

**Comment by JavaJens** [comment] 2015-02-25 18:22
Nope, Sony on Stock 4.4.4

**Comment by mcginty** [comment] 2015-02-25 18:32
I've got a Z3 Compact on stock 4.4.4 and I can't reproduce :/

**Comment by JavaJens** [comment] 2015-02-25 18:37
Me too; as I said I can't reliably reproduce this. I just checked when I saw the issue and noticed the same thing. Maybe it was something else.

**Comment by mcginty** [comment] 2015-02-25 18:39
Perhaps it's just the fact that the EditText's click area is smaller due to the AppCompat padding bug.

**Comment by JavaJens** [comment] 2015-02-25 18:48
Maybe you can use the developer tools to see exactly where you clicked? I tried a couple of times now and have the feeling that there could be a small difference in where a click is registered. But I guess my observation before was just a bad coincidence.

**Comment by BienquistaBromista** [comment] 2015-02-25 23:49
Maybe this debug log will help : https://gist.github.com/420b2067eebf219bc031

Line 100 and the next several lines look like they might have something to do with it.

**Comment by mcginty** [comment] 2015-02-28 01:23
Yesssss, thank you @BienquistaBromista! That was really helpful. That looks like another AppCompat bug. Found someone who reported it already: https://code.google.com/p/android/issues/detail?id=80647

**Comment by mcginty** [comment] 2015-02-28 01:27
Correction: this is actually a Lollipop bug: https://code.google.com/p/android/issues/detail?id=80647

**Comment by rhodey** [comment] 2015-04-10 00:02
The issue @mcginty referenced above in the google issue tracker notes that is has now been resolved in Lollipop 5.1, so this bug should only ever occur in Android Lollipop 5.0.

Looking into the debug log, the cause of this bug is a problem with rendering of the drawable `android:drawable/text_select_handle_middle_material`, which I find no reference to in our codebase. I believe that if we wanted to provide a workaround for this bug we'd have to somehow specify our own cursor styles to the extent that Android never tries to access `android:drawable/text_select_handle_middle_material`.

**Closed** 2015-05-08 01:10 UTC
Labels: bug
