### ISSUE TITLE
Cannot send any photos via push

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [WhisperSystems/TextSecure#3941] opened 2015-08-14 11:41 UTC
Dear all,

when I try to send a photo via push, it won't be delivered and I receive an error message. This happens when I try to send it via direct capture as well as when I try to attach a photo from the gallery.
I have submitted a debug log if that helps: https://gist.github.com/16f41ab75cf6b0954c04

**Comment by AlfonsoMuskedunder** [comment] 2015-08-14 11:45
In fact, I can't send any messages anymore...

**Comment by JavaJens** [comment] 2015-08-14 12:01
Probably a duplicate of #3940

**Closed** 2015-08-14 12:42 UTC
