### ISSUE TITLE
Mobile Numbers Only

### ISSUE THREAD

**Issue by JeremyWW** [WhisperSystems/TextSecure#3745] opened 2015-07-22 00:19 UTC
Could we have the option to display only mobile numbers / contacts with mobile numbers in the contact list.

Thanks.

**Comment by mcginty** [comment] 2015-07-22 01:14
Hey @JeremyWW, welcome to the TextSecure repo! Please search our open and closed issues before posting - it saves us some overhead from filtering.

Closing as dupe of https://github.com/WhisperSystems/TextSecure/issues/1011.

**Closed by mcginty** 2015-07-22 01:14 UTC

**Comment by JeremyWW** [comment] 2015-07-22 07:21
Apologies. It was done late last night from my phone. Not as easy to search as it is from the desktop.
