### ISSUE TITLE
smilies shifted

### ISSUE THREAD

**Issue by filatovsp** [WhisperSystems/TextSecure#3098] opened 2015-05-02 19:22 UTC
smilies shifted on the LG G3 android version 4.4.2
![img_20150502_135125](https://cloud.githubusercontent.com/assets/12213123/7442406/89f1b79a-f119-11e4-922c-52aa3f891432.jpg)

**Comment by wp9015362** [comment] 2015-05-02 19:53
Duplicate of:

https://github.com/WhisperSystems/TextSecure/issues/2957

**Closed** 2015-05-02 23:47 UTC
