### ISSUE TITLE
MMS slideshows: only 1 image displayed

### ISSUE THREAD

**Issue by privong** [WhisperSystems/TextSecure#1740] opened 2014-07-25 03:08 UTC
I imagine this is a feature request, but when receiving MMS messages with multiple images, only a single image is displayed and there is no (apparent) way to access the other images or any indication that the MMS contained multiple slides. Future support for MMS slideshows would be great.

**Comment by xortim** [comment] 2015-01-02 02:04
I can confirm this behavior. This is a must have feature.

**Comment by rhodey** [comment] 2015-03-16 22:31
closing as duplicate of #1300

**Closed by rhodey** 2015-03-16 22:31 UTC
Labels: mms
