### ISSUE TITLE
Notification includes ghost message if TS is not running/unlocked

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#2522] opened 2015-02-25 05:44 UTC
If TS is not running/unlocked, e.g., after restarting the phone, and a new message arrives, the notification days that two messages have been received. But only one actually is. The ghost message appears to be always from the same contact.

**Comment by McLoo** [comment] 2015-02-25 08:44
Pretty sure this is an abandoned entry in the push table, like discovered in #2358 
You know when this first occurred (what happened / what did you do)?

**Comment by merkste** [comment] 2015-02-25 08:52
This happened the first time quite some time ago. I am afraid I cannot  
remember when and under which circumstances. Is there another way how I  
could help to verify this hypothesis?


Am .02.2015, 09:44 Uhr, schrieb McLoo <notifications@github.com>:

**Comment by McLoo** [comment] 2015-02-25 09:02
You would need to open (a copy of) messages.db from TextSecure's data directory in some SQLite Manager/Browser and check the table called `push` for an entry from that contact. It's normally quite empty :)

**Comment by graingert** [comment] 2015-02-25 13:50
I'm getting a single phantom notification (1 message recieved) whenever TextSecure is locked (eg timeout or manually) When I unlock TextSecure with my passphrase the notification dissapears only to re-appear after locking.

Interestingly this doesn't trigger the notification LED

**Comment by merkste** [comment] 2015-02-25 15:25
@McLoo: It happened many times before the #2518 startup crash occurred.

**Comment by bisam** [comment] 2015-03-26 08:47
I have the same problem here, but instead of one ghostmessage I have 12 of them. I deleted the whole thread, and also ended the encrypted session, but the problem persists..

**Comment by McLoo** [comment] 2015-03-26 10:27
@bisam only workaround right now is to delete all app data, as those ghosts can't be busted from the UI. Sorry.

**Comment by graingert** [comment] 2015-03-26 10:37
@McLoo how long do the gosts stay busted after deleting all the app data?

**Comment by McLoo** [comment] 2015-03-26 10:52
@graingert once busted they won't come back. 
Though, if for any reason TS gets killed or gets updated while a message comes in, new ghosts **could** appear.

**Comment by graingert** [comment] 2015-03-26 10:58
@McLoo I'll wait for the code to be fixed, deleting all the app data sounds a bit drastic for a temporary fix

**Comment by privong** [comment] 2015-04-06 11:19
FWIW, this bug and #2221 appear to be related / the same.

**Comment by volcano99** [comment] 2015-04-18 16:10
Still present in 2.12, do we know the cause at least? Or how to reproduce?

**Comment by moxie0** [comment] 2015-04-18 16:37
Closing as duplicate of #2221

**Closed by moxie0** 2015-04-18 16:37 UTC
Labels: bug
