### ISSUE TITLE
Display app version in settings dialogue

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3324] opened 2015-06-03 09:20 UTC
The version number is not displayed within the TextSecure app. I suggest to display it at the bottom of the settings dialogue.

Please let me know if I have missed something.

**Comment by 2-4601** [comment] 2015-06-03 09:49
I usually check the version number from _Settings --> Advanced --> Submit Debug Log_

**Comment by Norbert80** [comment] 2015-06-03 11:49
Thanks. But I still prefer my suggestion. :-)

**Comment by claenn** [comment] 2015-06-04 20:39
+1

**Comment by Mihahn** [comment] 2015-06-07 18:05
Duplicate of #1356 #1501 #2053  #2742
But I'd love to see that feature, too!

**Comment by RiseT** [comment] 2015-06-10 16:41
The fork SMSSecure has already completed this. One possibility is just pulling their code.

**Closed** 2015-06-18 17:03 UTC
Labels: feature
