### ISSUE TITLE
yet another fatal exception

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/TextSecure#4269] opened 2015-10-21 21:09 UTC
Tapped on notification and Signal crashed.

Moto G Android 4.4.4 with Xposed
Signal 3.0.3

https://gist.github.com/anonymous/86e53a5a4e7f1466378c

```
W/dalvikvm( 345): threadid=1: thread exiting with uncaught exception (group=0x41673d40)
D/RedPhoneService( 345): Uncaught exception - releasing proximity lock
D/RedPhoneService( 345): java.lang.NullPointerException
D/RedPhoneService( 345): at org.thoughtcrime.securesms.ConversationActivity.onNewIntent(ConversationActivity.java:237)
D/RedPhoneService( 345): at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1184)
D/RedPhoneService( 345): at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2329)
D/RedPhoneService( 345): at android.app.ActivityThread.performNewIntents(ActivityThread.java:2342)
D/RedPhoneService( 345): at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2351)
D/RedPhoneService( 345): at android.app.ActivityThread.access$1600(ActivityThread.java:139)
D/RedPhoneService( 345): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
D/RedPhoneService( 345): at android.os.Handler.dispatchMessage(Handler.java:102)
D/RedPhoneService( 345): at android.os.Looper.loop(Looper.java:136)
D/RedPhoneService( 345): at android.app.ActivityThread.main(ActivityThread.java:5086)
D/RedPhoneService( 345): at java.lang.reflect.Method.invokeNative(Native Method)
D/RedPhoneService( 345): at java.lang.reflect.Method.invoke(Method.java:515)
D/RedPhoneService( 345): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
D/RedPhoneService( 345): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
D/RedPhoneService( 345): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
D/RedPhoneService( 345): at dalvik.system.NativeStart.main(Native Method)
D/LockManager( 345): Entered Lock State: SLEEP
D/AccelerometerListener( 345): enable(false)
--------- beginning of /dev/log/system
E/AndroidRuntime( 345): FATAL EXCEPTION: main
E/AndroidRuntime( 345): Process: org.thoughtcrime.securesms, PID: 345
E/AndroidRuntime( 345): java.lang.NullPointerException
E/AndroidRuntime( 345): at org.thoughtcrime.securesms.ConversationActivity.onNewIntent(ConversationActivity.java:237)
E/AndroidRuntime( 345): at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1184)
E/AndroidRuntime( 345): at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2329)
E/AndroidRuntime( 345): at android.app.ActivityThread.performNewIntents(ActivityThread.java:2342)
E/AndroidRuntime( 345): at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2351)
E/AndroidRuntime( 345): at android.app.ActivityThread.access$1600(ActivityThread.java:139)
E/AndroidRuntime( 345): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
E/AndroidRuntime( 345): at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 345): at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 345): at android.app.ActivityThread.main(ActivityThread.java:5086)
E/AndroidRuntime( 345): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 345): at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 345): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 345): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 345): at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
E/AndroidRuntime( 345): at dalvik.system.NativeStart.main(Native Method)
```

**Comment by moxie0** [comment] 2015-10-21 21:11
duplicate of #2971, thanks for the stack trace

**Closed by moxie0** 2015-10-21 21:11 UTC
