### ISSUE TITLE
Smiles choice on participant phone

### ISSUE THREAD

**Issue by GAS85** [WhisperSystems/TextSecure#2183] opened 2014-12-04 09:18 UTC
Hi All,
 I do not know where are smiles in TextSecure coming from , but on Android <4.4 they are brilliant!

![screenshot_2014-12-04-09-57-22](https://cloud.githubusercontent.com/assets/6813635/5295797/ecfc8b28-7b9c-11e4-80c3-b46da11f632a.png)

 My wife got a new Phone with Android 4.4.x and she was so upset, almost crying when she find out that smiles now are simple rounded as everywhere.
 Is there is a way to collect smile set from the Android <4.4 versions like on a screenshot and add to a newer release as option "Use classic smiles" or similar? This can be also feature request.
Thanks you.

P.S. how it looks now:
![screenshot_2014-12-04-14-54-55](https://cloud.githubusercontent.com/assets/6813635/5305633/b1fc7806-7bfd-11e4-937a-9949c03b167a.jpg)
![screenshot_2014-12-04-14-55-04](https://cloud.githubusercontent.com/assets/6813635/5305636/b6d88234-7bfd-11e4-9946-2154096a98af.png)

**Comment by wp9015362** [comment] 2015-02-16 20:04
> mcginty wrote:
>
> Yeah, might not bad to transition to using our emoji pane for all Android versions.

+1

**Comment by moxie0** [comment] 2015-02-16 20:07
@wp9015362 Please only post in issues or PRs if you have new information to add.  You just sent us three emails with no content about the same thing, which only makes me less likely to want to work on this issue.

**Comment by wp9015362** [comment] 2015-02-16 21:25
@moxie0 :

Didn't really know where to post in because #2138 and #2300 both are still open, so posted in both, that's all.

Might as well mark one of them as a duplicate of the other then...

And since when is expressing an opinion "no content"?

Well..., what am I wondering about after having seen what has been done to my post over there:

https://github.com/WhisperSystems/TextSecure/issues/1509

Thanks (to whomever) for being so rude. I've deleted it now...

**Closed** 2015-04-01 17:24 UTC
Labels: ux

**Comment by GAS85** [comment] 2015-04-10 17:15
Hi All,
 half of the job is done, thanks a lot! My wife was very happy to see that emotions are back. But they are still wrongly shown in a chat window. Is there is a way to change it?
![screenshot_2015-04-10-19-08-45](https://cloud.githubusercontent.com/assets/6813635/7092958/c8503a4a-dfb5-11e4-85b6-0ae6889defeb.png)

**Comment by moxie0** [comment] 2015-04-10 18:07
@GAS85 Can you open a new issue for this?

**Comment by wp9015362** [comment] 2015-04-10 20:05
> @GAS85 wrote:
> 
> Hi All,
half of the job is done, thanks a lot! My wife was very happy to see that emotions are back. But they are still wrongly shown in a chat window. Is there is a way to change it?

I have already reported this, see:

https://github.com/WhisperSystems/TextSecure/issues/2936

> @moxie0 wrote:
> 
> @GAS85 Can you open a new issue for this?

See above.

Regards

**Comment by GAS85** [comment] 2015-04-11 20:40
@moxie0 It looks more like a bug now, so @wp9015362 already opened a ticket and I believe we can close this one.
Thanks and Regards!
