### ISSUE TITLE
Add sms: uri schema handler

### ISSUE THREAD

**Issue by michalgm** [WhisperSystems/TextSecure#2578] opened 2015-03-04 18:55 UTC
If I click on an sms hyperlink in a web browser (such as
```html
<a href='sms:555-555-5555'>Call me, maybe?</a>
```
textsecure does not come up as an option.
Since you can only send sms from your default sms app, this makes it so these links essentially are unusable when textsecure is your default sms app.

Note: smsto: does not work either.

**Comment by rhodey** [comment] 2015-03-12 06:42
able to reproduce on my Nexus 5 running stock Lollipop and TS 2.5.3

**Comment by rhodey** [comment] 2015-03-12 06:51
Some doc on what it takes to get this working in KitKat

http://android-developers.blogspot.com/2013/10/getting-your-sms-apps-ready-for-kitkat.html

The TS manifest has a few discrepancies, will check it out.

**Comment by rhodey** [comment] 2015-03-23 21:49
some helpful test vectors http://jsbin.com/itama4/15

**Comment by rhodey** [comment] 2015-03-25 00:21
Just tested on my Nexus One running stock Android 2.3.6, also not working. Instead of being presented with a chooser my phone instead just selects the default messaging app.

**Comment by rhodey** [comment] 2015-04-21 18:32
The action resulting from clicking on the first of the four URIs (`sms:+437722735932?body=hello%20there`) found at http://jsbin.com/itama4/15 is as follows

```
I/ActivityManager﹕ START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=sms:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx flg=0x10000000 cmp=android/com.android.internal.app.ResolverActivity (has extras)}
```

Currently the section of our `AndroidManifest` intended to handle this reads as follows

```
<activity android:name=".SmsSendtoActivity">
    <intent-filter>
        <action android:name="android.intent.action.SENDTO" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:scheme="sms" />
        <data android:scheme="smsto" />
        <data android:scheme="mms" />
        <data android:scheme="mmsto" />
    </intent-filter>
</activity>
```

I expected that adding the action `android.intent.action.VIEW` and the category `android.intent.category.BROWSABLE` would resolve this bug, these changes result in TextSecure being displayed as an option however TextSecure fails to parse the intent correctly and the recipient ends up as `437722735932?body=hello there`.

Working on resolving this in a pull now but wanted to document cause in the issue report.

**Closed** 2015-04-30 18:55 UTC
Labels: bug

**Comment by jpsingleton** [comment] 2015-07-11 13:40
Would it be possible to have this support SMS URIs with no number (aka no path or `data` in the code)?

The use case is you have a message but want to choose who to send it to. Like you can with `mailto:?subject=xxx&body=xxx` and `whatsapp://send?text=xxx`. I've made [a mobile web app](https://instabail.uk/) that generates messages but the SMS doesn't work with TextSecure. It does work with other SMS apps and if I add a number to test with then it does work with TextSecure, but this isn't a solution.

I'm not sure if it's just as simple as not throwing the `URISyntaxException` and returning an empty path.

Maybe there could be a custom `textsecure:` URI like WhatsApp uses or would just selecting a secure contact result in the message going over the secure data connection anyway for an SMS link?
