### ISSUE TITLE
Missing ability to send PDF

### ISSUE THREAD

**Issue by Wblw** [WhisperSystems/TextSecure#3544] opened 2015-07-07 11:34 UTC
I wanted to send a PDF to one of my contacts, which isn't possible at the moment. I estimate this missing feature as really important due to the fact that it might be relevant to security measures being able to send documents encrypted.

**Comment by mawed** [comment] 2015-07-07 11:48
I'm not sure, but there is a big media update soon to come: #520 milestone 2.22
Maybe pdf is included there together with bigger videos.

**Comment by Mihahn** [comment] 2015-07-07 13:13
@mawed the milestone is updated with every new release. I'm not sure if this tells us anything :cry:

**Comment by McLoo** [comment] 2015-07-07 16:53
duplicate of #993

**Closed** 2015-07-07 17:03 UTC
