### ISSUE TITLE
Feature request: Search in conversation

### ISSUE THREAD

**Issue by j0lt** [WhisperSystems/TextSecure#2849] opened 2015-04-01 14:15 UTC
I would like to see a function in textsecure to search for keywords in an existing conversation like it is possible in WhatsApp for Android. Maybe it would be even nicer to be able to search over all conversations as well. 

Hope I'm doing this right since I am new to Github and stuff :)

**Comment by manhole11** [comment] 2015-04-01 14:53
I'm pretty sure someone must have opened a similar issue at some point, but +1 for you

**Comment by moxie0** [comment] 2015-04-01 14:57
Duplicate of #1232.

**Closed by moxie0** 2015-04-01 14:57 UTC
