### ISSUE TITLE
Send new foto

### ISSUE THREAD

**Issue by fajabird** [WhisperSystems/TextSecure#2797] opened 2015-03-26 14:37 UTC
All popular messengers have the Option to open the camera to capture a photo and send directly it without the need to leave the APP and without the need to save it first somewhere. Is this something already on your list? I find threemas implementation oft this nice. They added "camera" to the list of of file types.

**Comment by agrajaghh** [comment] 2015-03-26 15:12
looks like a duplicate of #520

**Closed** 2015-03-26 15:58 UTC
