### ISSUE TITLE
Feature Request - Remove gapps deps

### ISSUE THREAD

**Issue by swordsteel** [WhisperSystems/TextSecure#2752] opened 2015-03-22 20:05 UTC
Kill the gapps (google) dependancies. Folk with hardened roms like to be gapps free, and those who have hardened roms are gapps free for a very good reason. By making your app gapps free, both types of user can use your app, those who "trust" google, and those who trust themselves.

**Comment by agrajaghh** [comment] 2015-03-22 20:06
duplicate of #1000 and #127

**Closed** 2015-03-22 20:15 UTC

**Comment by swordsteel** [comment] 2015-03-28 17:43
Thank you
