### ISSUE TITLE
Sort Messages by send time, not by receive time

### ISSUE THREAD

**Issue by Deccoy** [WhisperSystems/TextSecure#1084] opened 2014-03-07 19:47 UTC
Please sort Messages by send time, not by receive time (and show send instead of recieve time under the messages). Sometimes I have lots of problems to follow discussions in larger group chats, when I power on my phone and recieve lots of messages with the same timestamp under a message with no time break between the topics.

This is a very annoying bug...

**Comment by rhodey** [comment] 2015-03-17 00:02
duplicate of #188

**Closed by rhodey** 2015-03-17 00:02 UTC
Labels: feature
