### ISSUE TITLE
Group chat broken after switch to a new phone

### ISSUE THREAD

**Issue by KommX** [WhisperSystems/TextSecure#4177] opened 2015-10-02 08:53 UTC
I recently switched to a new android phone. I installed textsecure from scratch (same phone number) and everything except for groups is fine again.

The first thing I noticed:
I can't see the groups I'm in, so I can't send messages to these groups.

But the more annoying bug is the following:
I received a message from a group I'm in. I can read it and I see who wrote it.
BUT:
1. I can't respond. When I touch the field for text input nothing happens.
2. The name is simply "Unnamed group".
3. I can't see the group members.

![screenshot_2015-10-02-10-30-40_neu](https://cloud.githubusercontent.com/assets/7859245/10242787/b572b99e-68f3-11e5-835d-637ebfa24e67.png)
![screenshot_2015-10-02-10-30-52_neu](https://cloud.githubusercontent.com/assets/7859245/10242788/b919a814-68f3-11e5-89db-0fae77f932a2.png)

**Comment by AlfonsoMuskedunder** [comment] 2015-10-02 09:46
Sounds very much like https://github.com/WhisperSystems/TextSecure/issues/4113.

**Comment by KommX** [comment] 2015-10-02 09:54
But keep in mind that I didn't change my phone number, just the device.

**Comment by 2-4601** [comment] 2015-10-02 09:56
Duplicate of many issues such as #1048.

**Comment by oaim** [comment] 2015-10-02 12:55
Ask someone to update the group, either by readding you or updating the group avatar or whatever. That will fix the issue and then you can close this.

**Comment by jeremymasters** [comment] 2015-10-02 13:48
I just did this  the other day.  Messaged one of the group members to update the group. They updated the group by dropping and then re- adding me and it worked perfectly.

**Closed** 2015-10-02 14:22 UTC
