### ISSUE TITLE
Let user select SIM on dual-sim devices when sending text messages (5.1+)

### ISSUE THREAD

**Issue by bgalileo** [WhisperSystems/TextSecure#3139] opened 2015-05-08 20:01 UTC
On my Moto G, I can select the SIM I want to use when I send the text messages via the default text message app. I'd love to use Textsecure as my default text messaging app, but for that it'd need to support that feature as well.

**Comment by bgalileo** [comment] 2015-05-08 20:02
Related to #555.

**Comment by moxie0** [comment] 2015-05-08 23:34
duplicate of #555

**Closed by moxie0** 2015-05-08 23:34 UTC
