### ISSUE TITLE
Adding Group Member with multiple phone numbers

### ISSUE THREAD

**Issue by ichEben** [WhisperSystems/TextSecure#3245] opened 2015-05-23 14:03 UTC
I experienced the following today:

I have two phones with two separate numbers, both with textsecure installed and push enabled.
A friend started a new groupchat and tried to invite me.
He only has the option to invite on of my numbers, since my contact only appears once in the list, with one number.

The same happens when he tries to start a new 1-to-1 chat.
He only has the option to start a conversation with one of my numbers, since the second one ist never shown in the list.

He has my two numbers safed in "one" contact.

Device: HTC One, stock android Lollipop, Latest TextSecure 2.14.5
App state: Push registered, incoming SMS disabled, outgoing SMS fully disabled

**Comment by 2-4601** [comment] 2015-05-24 11:32
Duplicate of #2257, #2531?

**Comment by moxie0** [comment] 2015-05-26 00:48
closing as duplicate

**Closed by moxie0** 2015-05-26 00:48 UTC
