### ISSUE TITLE
Please add optional read receipt feature

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3251] opened 2015-05-24 11:36 UTC
Hello,

this is a follow up to:

https://github.com/WhisperSystems/TextSecure/issues/957

Delivery receipts are implemented now.

But read receipts are still missing.

Could you please add an optional read receipt feature (turned on by default)?

Popular messengers like WhatsApp for Android and Telegram for Android do have this feature and it can be quite useful or even quite essential to say the least.

Those users who wouldn't like it could simply disable it.

Regards

**Comment by agrajaghh** [comment] 2015-05-24 11:50
duplicate of #2667 and others

**Comment by moxie0** [comment] 2015-05-26 00:50
*please* check existing issues before opening new ones.

**Closed by moxie0** 2015-05-26 00:50 UTC
