### ISSUE TITLE
Can't receive encrypted MMS over regular (non-push) channel

### ISSUE THREAD

**Issue by rfugger** [WhisperSystems/TextSecure#2316] opened 2015-01-10 03:12 UTC
When I receive an encrypted MMS over the regular non-push channel, the received message says "downloading..." and within a few seconds, the entire app crashes and ends with an error message "app closed unexpectedly" or the like. When I restart the app, it crashes again within 5 seconds and unless I have quickly deleted the thread containing the offending MMS, it will continue to crash immediately upon app start.

**Comment by agrajaghh** [comment] 2015-01-10 11:26
could you post a debug log please?

**Comment by rfugger** [comment] 2015-01-11 05:45
Debug log after receiving encrypted MMS, and then crashing about 4-5 times before successfully deleting the offending message in the 5 second window:

https://gist.github.com/7ecf1dc20ee337088453

**Comment by McLoo** [comment] 2015-01-11 10:20
Seems to be the same as #2315

**Comment by tavianator** [comment] 2015-01-11 17:21
Dupe of https://github.com/WhisperSystems/TextSecure/issues/2194?

**Comment by rhodey** [comment] 2015-03-13 21:01
closing as duplicate of #2194 which should have been resolved by dbd8a4083cc379a00bacfccbc8a3c2dc0ef42d71, thanks for the issue report! :)

**Closed by rhodey** 2015-03-13 21:01 UTC
Labels: mms
