### ISSUE TITLE
S6 Edge - Quick Reply not working when Textsecure is default Message App

### ISSUE THREAD

**Issue by benoitne** [WhisperSystems/TextSecure#3185] opened 2015-05-18 17:19 UTC
S6 Edge has a functionality to Reject an incoming call and send a preset message by placing a finger on the heart rate sensor.
When using Textsecure as a the default message app it is not working (using the default message everything is working)

**Comment by moxie0** [comment] 2015-05-18 18:40
duplicate of #483

**Closed by moxie0** 2015-05-18 18:40 UTC
