### ISSUE TITLE
Random freezing, followed by a crash

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/TextSecure#3669] opened 2015-07-15 14:23 UTC
Hello. Ever since updating to 2.22.1 I've had problems with TextSecure freezing. This almost always leads to a box that says "TextSecure isn't responding" and regardless of what I do at that point, it crashes 8-10 seconds later. At first I thought https://github.com/WhisperSystems/TextSecure/issues/3624 might still be spooking, but I don't think it's related. The camera crashing was always instantaneous, and usually happened when I flipped my phone. Now it happens out of the blue. Yesterday it happened while writing a message to a person who wasn't even writing back at the moment, which means it can't be https://github.com/WhisperSystems/TextSecure/issues/3642

Samsung Galaxy Nexus
Kitkat 4.4.4 Paranoid Android
TextSecure 2.22.1
Started happening with latest update. Never happened before.
![2015-07-15 00 53 12](https://cloud.githubusercontent.com/assets/12563436/8700652/682ea568-2b0d-11e5-8b5f-6f5b1a1782b9.png)
The picture shows what happened right before it crashed. I was about to add an emoji and then everything freaked out.

https://gist.github.com/d145fd936f2ebda89015
https://gist.github.com/514168cd604f1ead7faf

**Comment by mcginty** [comment] 2015-07-15 17:23
OutOfMemoryError - will see if there are new leaks caused by 2.22.1...

**Comment by Dyras** [comment] 2015-07-15 17:53
Do you want me to do anything specific to help you with this? Keep posting logs? Or have I done all I can for now?

/Guy with no programming skills whatsoever

**Comment by mcginty** [comment] 2015-07-15 17:57
Can you explain a bit more about what you do to make it begin to lag heavily? After it crashes, do you click on a conversation, load it, and try to insert an emoji?

Thanks so much for the bug report.

**Comment by Dyras** [comment] 2015-07-15 18:08
Usually I'm just writing something. It happened earlier today, but it didn't crash, it just froze for 10 seconds. It has happened at least once after I clicked on a conversation, and I didn't do anything at all after that.

I send quite a lot of pictures, taken directly in the app if that could be the issue.

**Comment by mcginty** [comment] 2015-07-15 20:17
@Dyras can you send me an email to me@jake.su, and I'll send you a debug build to install? I have a potential fix but also put in some more diagnostic memory output to try to work out the culprit.

**Comment by Dyras** [comment] 2015-07-16 15:44
Happened just now, even with the debug build you sent me. It didn't crash, but it froze for a good 15 seconds.

https://gist.github.com/anonymous/bb0750f6d7492ac19dbd

**Comment by Dyras** [comment] 2015-07-16 18:50
So, what do I do? Do I update to 2.22.2 and see if that helps?

**Comment by mcginty** [comment] 2015-07-16 19:10
@Dyras 2.22.2 has the fix that's in your build as well. If haven't yet upgraded, can you do one more favor? Can you force stop TextSecure (not swipe it out of the recent apps, you have to go to your system settings -> applications -> TextSecure -> Force Stop), then re-open it (entering password if you have one) and send me a debug log right after it opens? I'm wondering what your initial memory usage is and if it's above normal.

**Comment by Dyras** [comment] 2015-07-16 19:17
I haven't updated yet. Here you go:
https://gist.github.com/anonymous/b241ca7df5c2b021eadb

**Comment by Dyras** [comment] 2015-07-16 19:26
What would you say is normal memory usage while chatting with someone, sending emojis and pictures, etc?

**Comment by mcginty** [comment] 2015-07-21 20:10
@Dyras I think the next step is to email me a memory heap dump (as long as you're still experiencing slowness, it doesn't matter what TS you're running now). That way I can see what has leaked and is causing the memory issues. You'll need ADB:

```
adb shell am dumpheap org.thoughtcrime.securesms /sdcard/textsecure.hprof
adb pull /sdcard/textsecure.hprof
```

and then if you email me the textsecure.hprof file you pulled from the device I can take a look at what's occupying so much of the heap.

**Comment by Dyras** [comment] 2015-07-21 20:13
I've updated to the latest beta. I haven't noticed any slowness since the latest beta version by the way.

Is there a way to use the terminal to do that? I'm rooted.

**Comment by mcginty** [comment] 2015-07-21 21:06
@Dyras yep, you should be able to just do
```
am dumpheap org.thoughtcrime.securesms /sdcard/textsecure.hprof
```

from a terminal on your phone.

**Comment by RupertPaulson** [comment] 2015-07-24 15:38
I'm pretty sure that I have the same issue.
Nexus 5

**Comment by Dyras** [comment] 2015-07-24 16:16
For a while I thought it might just be my phone being really old, but apparently not. It has happened a lot less for me lately since I updated to 2.22.2. I'm on 2.22.3 now, and it has only happened once. I couldn't get the stupid Terminal to work, but I'll make sure to dumpheap next time it happens.

**Comment by Dyras** [comment] 2015-07-24 16:32
https://github.com/WhisperSystems/TextSecure/issues/3780#issuecomment-124561679
This man has it all figured out.

**Comment by mcginty** [comment] 2015-07-27 23:19
closing assuming the root cause is the same one mentioned in that comment

**Closed by mcginty** 2015-07-27 23:19 UTC
Labels: bug
