### ISSUE TITLE
[Feature Request] Vibrate Patern

### ISSUE THREAD

**Issue by Sysy1** [WhisperSystems/TextSecure#2320] opened 2015-01-10 14:21 UTC
Can you add an option to change the vibrate pattern, for example : 
-Normal (one time)
-Long vibrate
-Multiple Short
-Multiple Long
-and a custom option

**Comment by moxie0** [comment] 2015-01-10 14:27
Duplicate of #230

**Closed by moxie0** 2015-01-10 14:27 UTC
