### ISSUE TITLE
Ability to Lock Messages

### ISSUE THREAD

**Issue by tatwater** [WhisperSystems/TextSecure#3247] opened 2015-05-23 23:56 UTC
Many texting apps provide users with the ability to lock messages so that they cannot be deleted. It would be very useful to see this functionality come to the app, because after I imported all of my messages I began to clean them out and noticed that my locked messages were being deleted as well! Thank you!

**Comment by moxie0** [comment] 2015-05-26 00:44
Duplicate of #283.  *Please please please* check existing issues before opening new ones.

**Closed by moxie0** 2015-05-26 00:44 UTC
