### ISSUE TITLE
crash before it even unlocks

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3130] opened 2015-05-08 03:54 UTC
I'm trying to unlock textsecure but it only crashes after I type the password.  https://gist.github.com/9470cc7e2cd6011b0c77

**Comment by volcano99** [comment] 2015-05-08 04:03
I read somewhere to unlock it while in airplane mode. But it doesn't work

**Comment by mcginty** [comment] 2015-05-08 04:10
dupe of #3127

**Closed by mcginty** 2015-05-08 04:10 UTC

**Comment by volcano99** [comment] 2015-05-08 04:15
How is this a duplicate?  It doesn't open at all. and now I'm not able to even type the password, pleasefix asap I have to answer some important messages

**Comment by mcginty** [comment] 2015-05-08 04:16
@volcano99 same crash source. a single-character pull request is out, waiting for @moxie0 to get back and release since I don't have the ability to do that.

**Comment by volcano99** [comment] 2015-05-08 04:20
Great, thanks! I hope we get an update soon, because EVERYONE is texting me now that I can't read messages lol

**Comment by volcano99** [comment] 2015-05-08 04:23
Is there a way to downgrade?
