### ISSUE TITLE
Vanishing emoji button after activating system emoji 

### ISSUE THREAD

**Issue by sweah** [WhisperSystems/TextSecure#4105] opened 2015-09-22 05:44 UTC
Start app, emoji button there, change to system emoji, no emoji button... No changes after restart. 

https://gist.github.com/3fa758cf4c03401b814b

**Comment by moxie0** [comment] 2015-09-22 05:48
That's the way it works. Duplicate of #4101. Please check existing issues before opening new ones.

**Closed by moxie0** 2015-09-22 05:48 UTC
