### ISSUE TITLE
Attachments - "Quick Capture" audio/video recording and playback  (Google's  "Messenger" Android app style)?

### ISSUE THREAD

**Issue by RanceJustice** [WhisperSystems/TextSecure#3355] opened 2015-06-06 10:49 UTC
Those who have used Google's "Messenger" application for Android in its more recent iterations may have noticed a new feature for attachments. Clicking the "paperclip" for Attachments , besides the usual  options to attach a file, gives the user the option a number of "Quick, in-app, in-line" media capture options. 

For instance, choosing Picture (or alternately, Video) allows the user to capture the picture or video right from Messenger (a camera window is opened below the text entry box ) which is then added to the message to form the outgoing MMS.  Likewise, if the user chooses the Audio tab  there is a "Microphone button" and instructions to "press and hold to record". Doing so allows the user to speak a message which is then encoded as an audio file and added to the outgoing MMS.    

From what I can tell, TextSecure lacks these options. While a user can send a picture,  video, or audio  file that has already been saved elsewhere, I believe it would benefit TextSecure to enable these "Quick Capture" options, both for traditional SMS/MMS and Secure(Data) messaging.  Many users find these options alluring (particularly the audio quick capture, which allows the sending of a short audio message that can be played by the recipient at their leisure) and TextSecure supporting these features would mean users who enjoy them currently on other platforms could switch and enjoy better privacy/security  without having to lose said features

Please let me know if this seems feasible. Thank you.

**Comment by agrajaghh** [comment] 2015-06-06 10:53
duplicate of #520 

Its also already possible to take a picture within TextSecure. Just click the attachment button and select "Take Photo"

**Comment by RanceJustice** [comment] 2015-06-06 14:22
Ah, I didn't see that one when I searched prior to making the thread, only some of the closed entries.   Thank you. As that thread is limited to collaborators on the project I am unable to add my own support for the feature within, so please feel free to move/link my post here to be appended upon in support.

I do indeed see the "Take Photo" option and I am glad it is present.  Last I used the feature it seemed to call an external camera program, but as I inspect it in greater detail it does seem to now be completely from within TextSecure.

**Comment by agrajaghh** [comment] 2015-06-06 14:32
yes, you should close it. Btw, there is another improvement in development: #3018

**Closed** 2015-06-06 15:59 UTC
