### ISSUE TITLE
Open groups from contact list

### ISSUE THREAD

**Issue by Jens14L** [WhisperSystems/TextSecure#2628] opened 2015-03-09 00:28 UTC
If you delete the chat history of a group, you cannot access the group anymore. So the groups have to be listed in the contact list. (TextSecure 2.5.3)

**Comment by mcginty** [comment] 2015-03-09 00:56
dupe of https://github.com/WhisperSystems/TextSecure/issues/2628

**Closed by mcginty** 2015-03-09 00:56 UTC

**Comment by JavaJens** [comment] 2015-03-09 07:28
@mcginty you looped the reference here. 
Did you mean #1064?

**Comment by mcginty** [comment] 2015-03-09 08:23
Yep, copy paste error. Thanks @JavaJens.
