### ISSUE TITLE
Alternatives to Google's emojis

### ISSUE THREAD

**Issue by Thunderpig72** [WhisperSystems/TextSecure#3445] opened 2015-06-19 19:54 UTC
Me and my friends all completely despise the Google emojis. I don't really know why, but the fact still remains that we do. With that said, I think a lot of people would be happy to see alternatives. Twitter's emojis are open source and look quite nice. Of course I would prefer Apple's, but those aren't open source at all so that might be a problem. I don't really see how WhatsApp could get away with using them though. With Signal for Iphone and Signal soon coming to Android, I think it's quite important that both people see the same thing. That's the way Telegram does it, and it makes sure both people see the exact same emojis. Some Apple/Google emojis are so different that it's not even funny. Yeah, I know Samsung for example has their own emojis, but that doesn't exactly make things easier.

Is this being worked on? Is it even being considered? I even tried using Emoji Switcher to get Apple's emojis, but it just isn't working.

**Comment by wp9015362** [comment] 2015-06-19 21:11
Yeah, please use the open source "Emoji One" Emoji set:

http://emojione.com/
https://github.com/Ranks/emojione

The "Emoji One" Emoji set looks a heck of a lot better than the Google "Noto Color Emoji" Emoji set IMHO.

And it looks much more similar to the Apple set, which in turn would result in a much better interoperability with Signal-OS.

And the Emoji One developers even already said that they will release a Unicode 7.0 update soon, see:

https://github.com/Ranks/emojione/issues/68#issuecomment-93861096
https://github.com/Ranks/emojione/issues/68#issuecomment-93880415
https://github.com/Ranks/emojione/issues/105#issuecomment-106951709

Regards

**Comment by Thunderpig72** [comment] 2015-06-19 21:52
The question on my mind is: What will Signal use when the browser extension is out? Clearly they can't/shouldn't use the Android emojis on a Windows computer.

**Comment by agrajaghh** [comment] 2015-06-19 23:11
duplicate of #2892 #2894

**Comment by rainerzufall** [comment] 2015-06-28 19:46
+1
it should be the same set across platforms

**Comment by Thunderpig72** [comment] 2015-06-28 19:57
I think Emoji One looks great, and I think it would be a wonderful alternative to Apple's emojis.

**Comment by philgood** [comment] 2015-07-02 23:30
Or possibly have a setting in TextSecure to change emoji icon sets between currently running emoji set on phone and default Google's emojis...

**Comment by wp9015362** [comment] 2015-07-03 16:22
> @rainerzufall wrote:
> +1
> it should be the same set across platforms

I agree.

>  philgood@ wrote:
> 
> Or possibly have a setting in TextSecure to change emoji icon sets between
> currently running emoji set on phone and default Google's emojis...

No, please don't do this.

This would lead to a big confusion issue, where Emojis can easily get lost in translation, which is described in the following article, see:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

Currently TextSecure is using it's own built-in Emoji set and overwrites native Emojis to make sure that all TextSecure users are seeing the same Emojis.

This is very good! And it should stay like that IMHO!

But please use Emoji One as the built-in Emoji set.

The Emoji One Emoji set looks way better than the Google "Noto Color Emoji" Emoji set and it looks much more similar to the Apple set, which in turn would result in a much better interoperability with Signal-iOS.

Regards

**Comment by mcginty** [comment] 2015-07-08 06:55
in 2.22.0

**Closed by mcginty** 2015-07-08 06:55 UTC
Labels: emoji

**Comment by Thunderpig72** [comment] 2015-07-08 18:22
I still wish we had an open source emoji alternative though. Like Emoji One.

**Comment by jellium** [comment] 2015-07-16 08:08
Alright, I still wish we have the choice between sets of Emojis. And also it is not true that TextSecure makes sure that the Emojis seen on emitter and recipient phones are the same. Just tried with 2.22.2 version to my lady who didn't update: she sees the Google Emojis while I have the ugly Apple ones. 

The look of Emojis can be a determining choice for the use of such or such App. In order not to despise users with that can of update, you should let us choose in the App which set of Emojis to use. No confusion could exist since everyone could chose. And at least you wouldn't focus any critics towards futile questions such as Emojis.
