### ISSUE TITLE
Sending mssages to this specific contact almost always crashes textsecure

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#3911] opened 2015-08-07 14:40 UTC
I have a conversation with this friend of mine that recently has been causing a lot of problems. (This happened on 2.24 too, so it shouldn't be 2.25-related)
So basically:
1. I type a message
2. Hit send
3. Wait...
4. Sometimes the message bubble appears, sometimes it crashes before it does
5. I reopen ts, unlock it, go to the conversation and the message bubble is there. The message is also correctly marked as send and delivered

debug log: https://gist.github.com/a3061a1f4b7edfcfdcab

**Comment by moxie0** [comment] 2015-08-07 17:40
QuickAttachmentDrawer onLayout?

`````
--------- beginning of /dev/log/system
E/AndroidRuntime(28147): FATAL EXCEPTION: main
E/AndroidRuntime(28147): java.lang.IllegalStateException: Couldn't read row 1461, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
E/AndroidRuntime(28147): 	at android.database.CursorWindow.nativeGetLong(Native Method)
E/AndroidRuntime(28147): 	at android.database.CursorWindow.getLong(CursorWindow.java:511)
E/AndroidRuntime(28147): 	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
E/AndroidRuntime(28147): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
E/AndroidRuntime(28147): 	at android.support.v4.widget.CursorAdapter.getItem(CursorAdapter.java:213)
E/AndroidRuntime(28147): 	at org.thoughtcrime.securesms.ConversationAdapter.getItemViewType(ConversationAdapter.java:132)
E/AndroidRuntime(28147): 	at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:6893)
E/AndroidRuntime(28147): 	at android.widget.AbsListView.obtainView(AbsListView.java:2445)
E/AndroidRuntime(28147): 	at android.widget.ListView.makeAndAddView(ListView.java:1775)
E/AndroidRuntime(28147): 	at android.widget.ListView.fillUp(ListView.java:712)
E/AndroidRuntime(28147): 	at android.widget.ListView.layoutChildren(ListView.java:1609)
E/AndroidRuntime(28147): 	at android.widget.AbsListView.onLayout(AbsListView.java:2300)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at org.thoughtcrime.securesms.components.camera.QuickAttachmentDrawer.onLayout(QuickAttachmentDrawer.java:186)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1641)
E/AndroidRuntime(28147): 	at android.support.v7.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1630)
E/AndroidRuntime(28147): 	at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1405)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
E/AndroidRuntime(28147): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
E/AndroidRuntime(28147): 	at android.view.View.layout(View.java:13856)
E/AndroidRuntime(28147): 	at android.view.ViewGroup.layout(ViewGroup.java:4424)
E/AndroidRuntime(28147): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1992)
E/AndroidRuntime(28147): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1813)
E/AndroidRuntime(28147): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1113)
E/AndroidRuntime(28147): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4481)
E/AndroidRuntime(28147): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
E/AndroidRuntime(28147): 	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
E/AndroidRuntime(28147): 	at android.view.Choreographer.doFrame(Choreographer.java:525)
E/AndroidRuntime(28147): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer
`````

**Comment by mcginty** [comment] 2015-08-07 18:51
seems sqlite related?

`E/AndroidRuntime(28147): java.lang.IllegalStateException: Couldn't read row 1461, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
`

**Comment by oaim** [comment] 2015-08-07 18:55
Don't know if it's useful information but I experience a fair lag when texting this contact -- I've talked about it in other threads. So it's always been slow, but only recently started crashing frequently

**Comment by mcginty** [comment] 2015-08-08 00:23
Hey @oaim, I noticed that Android is saying your cursor window is full. I think these problems are due to you having a very large conversation with this contact, and will be resolved when LargeSQLiteCursor gets merged if all goes well. Should make your TS experience much snappier :).

**Comment by oaim** [comment] 2015-08-08 03:00
Yeah I had the same feeling but reported it anyway. Thanks! :) By the way the conversation has less than 5k messages because I have the trim activated, so there are definitely people with longer conversations than that.
One thing remains unexplained: why does it happen only with this contact? I have other conversations of the same length

**Comment by oaim** [comment] 2015-08-11 13:45
Update: On a slow connection it crashes 100% of the time. I don't know how this is related to the database, but it is a lot of work to insert my long password every time I want to send a message... :(

**Comment by merkste** [comment] 2015-08-20 20:18
I reported a similar crash in #3971. It happened in two different conversations. One is rather lengthy but the other one isn't. However, the crashes are reproducible on a bad connection. Firstly, I sent a picture message which did not finish send but got stuck with the spinning animation. Secondly, I deleted that message which was still not sent. Crash.

**Comment by oaim** [comment] 2015-09-02 19:09
I'm getting this problem with more and more contacts. However, not all the contacts with >5k messages are affected (yet?). TextSecure is becoming impossible to use for me

**Comment by oaim** [comment] 2015-09-05 07:54
(Just writing to notify everyone that I am unsubscribing, so I won't be able to help any more. TextSecure had become impossible for me to use (it crashed all the time and I had to type a huge password every time) so I plan on moving to a different app. I might consider checking the repository out when Signal comes, if ever. Thank you and bye!)

**Comment by mcginty** [comment] 2015-09-16 23:58
after talking about implementation there's no way this is going to make it into 2.27.0, pushing.

**Comment by mcginty** [comment] 2015-10-15 18:22
in 3.1.0

**Closed by mcginty** 2015-10-15 18:22 UTC
