### ISSUE TITLE
keyboard type predictions not shown in landscape mode

### ISSUE THREAD

**Issue by arnschi** [WhisperSystems/TextSecure#3737] opened 2015-07-21 07:24 UTC
Hi,

When I write a message in landscape orientation, the keyboard does not show its text prediction suggestions. Even worse, the keyboard automatically corrects words it does not know, without giving me the possibility to chose or add them to the dictionary.

This only occurs when writing a message in landscape mode. In portrait mode, the keyboard works like it is supposed to be. Also in other apps, writing in landscape mode shows the prediction suggestions.

System: HTC Desire, cyanogenmod 7.2.0.1-bravo, textsecure: 2.21.0, stock keyboard (german)

Attached some screenshots:
01: textsecure app in landscape mode (predictions are missing)
02: textsecure app in portrait mode (predictions are shown)
02: note taking app in landscape mode (predictions are shown)

![01_textsecure_landscape](https://cloud.githubusercontent.com/assets/13430625/8795030/699fb178-2f89-11e5-9a91-fefc97bd7bb1.png)
![02_textsecure_portrait](https://cloud.githubusercontent.com/assets/13430625/8795028/6995c956-2f89-11e5-9e64-9a91ce3c26e7.png)
![03_notes_landscape](https://cloud.githubusercontent.com/assets/13430625/8795029/699f02be-2f89-11e5-92db-4d082fbdd2f4.png)

Please let me know if you need any further information. And after all: Thanks for providing textsecure!

**Comment by 2-4601** [comment] 2015-07-21 11:08
Unable to reproduce:
TS 2.23.0
Nexus 4, stock 5.1.1 keyboard
Huawei U8800, 4.0.4 keyboard

**Comment by mcginty** [comment] 2015-07-21 18:55
This should be fixed when you update your textsecure to the newest released version. We follow the same UI pattern as that note taking app you showed as an example.

**Closed by mcginty** 2015-07-21 18:55 UTC
