### ISSUE TITLE
NPE crash on tapping notification

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3466] opened 2015-06-25 08:39 UTC
received notification, tapped it, (don't know if I passed passphrase dialog), crash

````
Device  : Sony D5503 (D5503)
Android : 5.0.2 (3750474323, 14.5.A.0.270)
App     : TextSecure 2.19.1 (PlayStore!)
````
https://gist.github.com/anonymous/09be24e2934d58ea3ff0

Edit: was a plain text TS message. So, no attachment ...
````
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.thoughtcrime.securesms.mms.AttachmentManager.isAttachmentPresent()' on a null object reference
````

**Comment by moxie0** [comment] 2015-06-25 16:53
Duplicate of #2971

**Closed by moxie0** 2015-06-25 16:53 UTC
