### ISSUE TITLE
Double Login Screen

### ISSUE THREAD

**Issue by plaguedemons** [WhisperSystems/TextSecure#2441] opened 2015-02-10 18:30 UTC
At least the last 2 versions, 2.5.1 and 2.50, have required 2 logins, even when password is copied and pasted into the password textbox. Machine is Samsung Note 3, carrier Verizon, Android version 4.4.4. The bug is intermittent, but occurs a majority of the time.

**Comment by mindlessroman** [comment] 2015-02-10 19:27
I've experienced the same behavior, and have found that if you close out of the app and reopen after the first prompt, the app will open correctly. Galaxy S5, ATT, 4.4.2.

**Comment by plaguedemons** [comment] 2015-02-10 19:34
Excellent.  I will try that out, too, and update the status on GitHub if it works.  I have rebooted my machine a number of times since the updates, which seems like it would have the same effect.

Eric

**Comment by plaguedemons** [comment] 2015-02-10 22:44
I tried killing the app after the 1st login and not entering the password for the 2nd login screen, and the app still asked for a 2nd login/password.  So that workaround did not work for me.

**Comment by shaaati** [comment] 2015-02-11 17:59
I can confirm the issue on a Nexus 5 running Android 5.0.1.
As @mindlessroman, I don't really need to type in the 2nd password. Minimizing and then reopening TextSecure also works which indicates that the second lockscreen is shown by error and not because the login somehow didn't work.

**Comment by mindlessroman** [comment] 2015-02-11 18:11
@plaguedemons are you completely closing out the app (killing the app)? I find that sometimes that needs to be done after the first login screen.

**Comment by shaaati** [comment] 2015-02-11 18:14
Issue is a duplicate of #2360, so the problem exists at least since version 2.4.2.

**Comment by moxie0** [comment] 2015-02-11 18:17
Duplicate of #2360

**Closed by moxie0** 2015-02-11 18:17 UTC

**Comment by gabrielbauman** [comment] 2015-02-13 21:55
Strangely, the app is unlocked after the first login screen. Pressing 'back' at the second screen takes you into the app.

**Comment by plaguedemons** [comment] 2015-02-18 06:47
Yes, this worked for me, also. This is a good workaround until the bug is found and fixed.
