### ISSUE TITLE
Feature Request: Time Based Message Deletion

### ISSUE THREAD

**Issue by bkerensa** [WhisperSystems/TextSecure#3258] opened 2015-05-25 20:17 UTC
I love the trim after x messages but also wish I could have messages older than x days be deleted.

Please support this as a feature.

**Comment by volcano99** [comment] 2015-05-25 20:29
duplicate of #3047, please close :)

**Comment by moxie0** [comment] 2015-05-26 01:10
@bkerensa *please* check existing issues before opening new ones. It's a huge drag for us to have to constantly clean these up.

**Closed by moxie0** 2015-05-26 01:10 UTC
