### ISSUE TITLE
view images from exported backup

### ISSUE THREAD

**Issue by cowlicks** [WhisperSystems/TextSecure#2243] opened 2014-12-19 08:33 UTC
TextSecure kept crashing when I would open text message threads. So I'm trying backup all my data to my laptop and delete all threads from my phone to start fresh. But I'm not sure how to view the images or messages in the "plaintext backup" on my phone. How do you do this? It is a mixture of mms, sms, and push messages.

**Comment by rhodey** [comment] 2015-03-16 21:54
closing as duplicate of #1619, to do a full backup use the `adb backup` and `adb restore` method.

**Closed by rhodey** 2015-03-16 21:54 UTC
