### ISSUE TITLE
Searching within conversation?

### ISSUE THREAD

**Issue by cbarnsdale** [WhisperSystems/TextSecure#3586] opened 2015-07-09 15:21 UTC
How difficult would it be to implement a search function on a per conversation basis? Personally, I've had many times where I've wanted to look up a particular detail that I've forgotten, such as an address, and have had to scroll back through all the messages to find it.

Thoughts?

**Comment by agrajaghh** [comment] 2015-07-09 15:52
duplicate of #1232

**Closed by agrajaghh** 2015-07-09 15:52 UTC
