### ISSUE TITLE
Calling then aborting right away still calls, and recipient is forever stuck "Connecting"

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/TextSecure#4356] opened 2015-11-03 18:16 UTC
Hi, my mom is clumsy and calls me by accident fairly regularly. Every damn time it rings for me, so I answer. Then I'm always stuck at "Connecting". Regardless of how long I wait it never goes away, because there is no one to connect to.

In my opinion, for starters, there should be a sound indicating connecting. You know when you make a real call, it makes a beep occasionally while connecting you? Signal could totally use that to make this less confusing.

Second and more importantly, I think Signal should send a message to the server or whatever indicating the call was cancelled, to prevent me from sitting there waiting for a call that is never going to connect.

How to reproduce
1. Person A calls person B
2. Person A hangs up a second or so after pressing the call button
3. Person B answers the call
4. Person B sits around and waits, wondering why he can't connect to grandma
5. Person B gets irritated and manually aborts the call.

**Comment by agutl** [comment] 2015-11-03 19:25
#4172

**Comment by mcginty** [comment] 2015-11-03 20:30
yeah, i think this is a dupe of #4172

**Closed by mcginty** 2015-11-03 20:30 UTC
Labels: redphone
