### ISSUE TITLE
make GCM for wakeup events optional

### ISSUE THREAD

**Issue by wngstr** [WhisperSystems/TextSecure#2685] opened 2015-03-14 13:13 UTC
I really dislike your latest decision to stop support for encrypted SMS/MMS.
Not because I don't like push messages - I simply do not want to install google services.
In my opinion it makes your whole effort for encrypted communications a farce - but this is just my point of view.

Now I read in your blog that you are going to handle message delivery by yourselves. This is really nice. One thing though: You want to go for GCM for wakeup events - That means GCM would be mandatory for TextSecure. What about using a different mechanism - a periodically check, manual check, whatever. As long as GCM would be optional I would be very glad, lot's of other ppl possibly as well and this would be a good compromise for the gone encrypted SMS.

So, would you please consider making GCM for wake up events optional while providing encrypted push through your own services without the need of google services?

Would really appreciate that. Thanks.

**Comment by brumsoel** [comment] 2015-03-14 13:22
Dupe of #1000. Official support for non-GCM push will probably be added sometime in the future, but I don't think it is a high priority task as it only affects a small fraction of the user base.

**Closed** 2015-03-14 16:33 UTC
