### ISSUE TITLE
Images are sent with wrong orientation

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#2364] opened 2015-01-18 10:26 UTC
How to reproduce the problem:
1. take a photo
2. rotate it using the gallery app
3. send it with textsecure
It will be sent with the original orientation, and not the desired on.

**Comment by agrajaghh** [comment] 2015-01-18 10:44
I can't reproduce this. Can you upload the picture you tried to send somewhere? Which version are you running?

**Comment by manhole11** [comment] 2015-01-18 21:07
I'm running 2.4.2 on a samsung galaxy s3. I used the gallery app to rotate the picture, so maybe that's the "problem".
The best thing would be implementing the option to rotate images within TS once they've been uploaded, before sending...

**Comment by agrajaghh** [comment] 2015-01-18 21:36
they are rotated before sending (regarding exif information)... 
We need the file to see what the problem is.. Can you upload it somewhere?

**Comment by rhodey** [comment] 2015-04-24 18:18
non-reproducable, no debug log, and OP is gone. closing.

**Closed by rhodey** 2015-04-24 18:18 UTC
