### ISSUE TITLE
Cannot delete message with error / issues

### ISSUE THREAD

**Issue by aurisnoctis** [WhisperSystems/TextSecure#3009] opened 2015-04-17 10:29 UTC
When a message doesn't get delivered - marked by the red exclamation mark icon - it is not possible to delete it.

Case:
- Send a message
- doesn't get delivered
- I only see non-delivery much later, message is irrelevant now
- do not want to resend that message, want to delete it instead
- unable to delete that message

**Comment by agrajaghh** [comment] 2015-04-17 10:37
the issue is that you can't select it right?

**Comment by aurisnoctis** [comment] 2015-04-17 11:37
@agrajaghh No, that is not my issue. Yes, sometimes, the selection doesn't work as described in other issues, but I work around that by keeping a message pressed with one finger, and then pressing the appearing trash can at the top with the other finger. Problem here is that in contrast to messages that were successfully sent, no trash can appears at the top at all.

**Comment by agrajaghh** [comment] 2015-04-17 11:48
You can use multiselect: select another (normal) message and afterwards select the failed one and deselect the normal message. But ofc thats just a workaround...

**Comment by aurisnoctis** [comment] 2015-04-17 13:04
@agrajaghh Thank you, that works.

Would be nice if I could select the error-ridden message directly, though.

**Comment by agrajaghh** [comment] 2015-04-17 13:12
yes, I guess you can close this issue, its a duplicate of #2764

**Closed** 2015-04-17 14:20 UTC
