### ISSUE TITLE
Change action bar icons to the new shape

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#2838] opened 2015-03-31 15:11 UTC
The several /res/drawable-*dpi/actionbar_icon_holo_dark.png and actionbar_icon_holo_light.png need to be updated to the shape of the new icon. They still have the TextSecure <= 2.4 shape.

**Comment by agrajaghh** [comment] 2015-03-31 16:23
duplicate of #2732

**Comment by manhole11** [comment] 2015-04-01 09:50
duplicate of #2732 ?

**Comment by rhodey** [comment] 2015-04-03 00:41
thanks @ghost, closing as dupe

**Closed by rhodey** 2015-04-03 00:41 UTC
