### ISSUE TITLE
Old Android emoji still visible in message preview

### ISSUE THREAD

**Issue by em77** [WhisperSystems/TextSecure#3844] opened 2015-07-30 15:24 UTC
The emoji in the message preview are still the old Android emoji, then when you tap on it and go into TextSecure, it changes over to the new iPhone emoji.

The message previews are making me long for the superior Android emoji and allowing me to have it both ways. Please help me cut the cord and forget that digital life used to be more expressive.

**Comment by 2-4601** [comment] 2015-07-30 15:28
Duplicate of #3278, #3625

**Closed** 2015-07-30 15:42 UTC
