### ISSUE TITLE
text line not visible in landscape mode on 3 inch display for TS >=2.5.0

### ISSUE THREAD

**Issue by Txtscr** [WhisperSystems/TextSecure#2528] opened 2015-02-25 15:44 UTC
Since version 2.5.0 the text line is not visible in landscape mode on my 3 inch xperia mini. The head line and keyboard are too close together. For <2.5.0 everything was fine.

**Comment by agrajaghh** [comment] 2015-02-25 16:14
duplicate of #2491

**Closed** 2015-02-25 17:42 UTC
