### ISSUE TITLE
Share / Send to...

### ISSUE THREAD

**Issue by JeremyWW** [WhisperSystems/TextSecure#3808] opened 2015-07-26 23:06 UTC
Tried to share a contact in my address book today via TextSecure which I couldn't do as, although TextSecure is set as the default text messaging app, it doesn't appear on the 'Send To' menu when using 'Share' in the Address Book. The stock Android messaging app is there which of course I couldn't use as it's not the default. I did try searching for this as an issue here so hopefully it's not a dupe.

**Comment by moxie0** [comment] 2015-07-27 17:23
duplicate of #535

**Closed by moxie0** 2015-07-27 17:23 UTC

**Comment by JeremyWW** [comment] 2015-07-27 23:34
Doesn't look like a duplicate to me. This is about the missing option to share contact information from the address book via text message regardless of format. The other issue appears to be about importing vCards.
