### ISSUE TITLE
Crash on unlocking - all the time

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#4016] opened 2015-09-04 08:42 UTC
2.26
https://gist.github.com/a45c8bfd62aee5721179

Tested ~~serious~~ self (stupid auto correct)  send mms 
Had phone & TS locked 

Unlocked. Crash.

**Comment by McLoo** [comment] 2015-09-04 08:50
very first time i didn't backup before updating :/

**Comment by moxie0** [comment] 2015-09-04 16:50
`````
E/AndroidRuntime( 9530): FATAL EXCEPTION: JobConsumer-3
E/AndroidRuntime( 9530): Process: org.thoughtcrime.securesms, PID: 9530
E/AndroidRuntime( 9530): java.lang.NullPointerException: Attempt to get length of null array
E/AndroidRuntime( 9530): 	at java.lang.String.<init>(String.java:206)
E/AndroidRuntime( 9530): 	at org.thoughtcrime.securesms.util.Util.toIsoString(Util.java:125)
E/AndroidRuntime( 9530): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.createAttachmentPointer(AttachmentDownloadJob.java:120)
E/AndroidRuntime( 9530): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrievePart(AttachmentDownloadJob.java:98)
E/AndroidRuntime( 9530): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(AttachmentDownloadJob.java:72)
E/AndroidRuntime( 9530): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
E/AndroidRuntime( 9530): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
E/AndroidRuntime( 9530): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
`````

**Comment by mcginty** [comment] 2015-09-04 17:37
Caused by media self-sends since there's a separate bug where the incoming copy is marked as a pending part. Change to fix both out soon after I test it.

**Comment by McLoo** [comment] 2015-09-04 18:10
@mcginty good to read! Thanks!

**Closed** 2015-09-04 18:43 UTC

**Comment by McLoo** [comment] 2015-09-04 19:35
Just for the record, I don't think the self send MMS mentioned above was pending, but the old push media messages. MMS came in the regular way...
