### ISSUE TITLE
Sending picture indicator never stops spinning

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#3578] opened 2015-07-09 08:33 UTC
I sent a picture message including text. It seems to be successfully delivered, both checkmarks appeared. However, the progress indicator overlay never stops spinning, even after restarting the phone.

https://gist.github.com/0f7cd369a31ea4feeeb5

**Comment by 2-4601** [comment] 2015-07-09 09:28
Duplicate of #3546?

**Closed** 2015-07-09 15:33 UTC

**Comment by merkste** [comment] 2015-07-10 08:10
Most likely. My connection was too bad to double check the issue list =)
