### ISSUE TITLE
Android 5.0 Lock Screen TextSecure is unlocked notification

### ISSUE THREAD

**Issue by maxperron** [WhisperSystems/TextSecure#2538] opened 2015-02-26 14:25 UTC
Hi,

I saw this issue: [#1858](https://github.com/WhisperSystems/TextSecure/issues/1858) but I don't believe it's the same thing.

I got updated to Android Lollipop this morning on my LG G3. The setup for my lock screen is a PIN. With lollipop, I now see notifications on the lock screen which is good, but I also have the "TextSecure is unlocked" notification always there. Is there a way to remove it aside from silencing all notification for the app ?

Thanks,

Maxime

**Comment by mcginty** [comment] 2015-02-26 19:36
Hey Maxime - I can't reproduce this on stock Lollipop. I'm guessing your carrier/LG may have a custom lock screen that shows low-priority notifications when it shouldn't? Sounds kind of like a ROM bug.

**Comment by mcginty** [comment] 2015-02-27 22:21
closing with that assumption unless we hear otherwise

**Closed by mcginty** 2015-02-27 22:21 UTC

**Comment by maxperron** [comment] 2015-03-02 15:03
Thanks, when I removed the priority notification settings for TextSecure on the LG G3, the notification disappeared from the lock screen.
