### ISSUE TITLE
TextSecure SMS sent to previous Signal user now keep defaulting to encrypted

### ISSUE THREAD

**Issue by lrobeson** [WhisperSystems/TextSecure#4221] opened 2015-10-07 17:31 UTC
I use TextSecure and my friend has an iPhone that at one point had Signal installed (she didn't want to use it for some reason). Now TextSecure keeps defaulting to sending her encrypted SMSs even though she doesn't have Signal installed anymore.

So I'll send her texts and get no reply, not always realizing they were all encrypted and she didn't get any of them. Then I have to copy them, hold down the button to switch to unencrypted, and resend them all.

**Comment by RiseT** [comment] 2015-10-07 17:36
Duplicate of #1026

**Comment by justin-** [comment] 2015-10-07 18:05
https://whispersystems.org/textsecure/unregister/

**Comment by moxie0** [comment] 2015-10-09 13:24
Please contact support@whispersystems.org for support questions, thanks!

**Closed by moxie0** 2015-10-09 13:24 UTC
