### ISSUE TITLE
Feature Request: Archiving Messages

### ISSUE THREAD

**Issue by aesahaettr** [WhisperSystems/TextSecure#3951] opened 2015-08-17 00:15 UTC
Right now, Text Secure only allows you to either keep your messages in your inbox or else permanently delete them. I'd like to be able to archive them so that I can look back on past conversations if I need to.

**Comment by moxie0** [comment] 2015-08-17 01:38
Duplicate of #1141.  Please check existing issues before opening new ones.

**Closed by moxie0** 2015-08-17 01:38 UTC
