### ISSUE TITLE
Unregister TextSecure service upon uninstalling

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/TextSecure#3457] opened 2015-06-23 05:09 UTC
My problem is that I have several contacts that tried TextSecure but uninstalled it after a short time without unregistering. Unfortunately they're also unwilling to use the unregister function on the Website and so I'm stuck with several phone numbers still shown as TextSecure Contacts and whenever I try to send a Message it automatically uses the push service instead of the normal SMS system.
It would be helpful if there was a possibility to permanently deactivate push messages for certain contacts or even better, to automatically unregister contacts that have uninstalled the app.

**Comment by moxie0** [comment] 2015-06-23 05:53
Duplicate of #1026

**Closed by moxie0** 2015-06-23 05:53 UTC
