### ISSUE TITLE
TextSecure without Gapps

### ISSUE THREAD

**Issue by inktrap** [WhisperSystems/TextSecure#4276] opened 2015-10-22 17:17 UTC
TextSecure won't work without Google Play or the underlying Google Play services. I think this is a bad situation: IMHO **the** secure **open-source** messenger app, with strong **open** crypto relies on a proprietary (right? It's not open source, or is it?) library from a US based company. If the whatsapp client uses the TS-protocol, why should I use TS?

There are quite some gappless phones and honestly, it is either Gapps and TS or no Gapps and no Messenger-App at his point. :)

Also compare for #725.

**Comment by moxie0** [comment] 2015-10-22 17:22
This is an issue tracker, not a discussion forum.  Also, duplicate of a thousand issues.

**Closed by moxie0** 2015-10-22 17:22 UTC
