### ISSUE TITLE
Custom alerts for different contacts.

### ISSUE THREAD

**Issue by JacobHenner** [WhisperSystems/TextSecure#291] opened 2013-08-01 04:52 UTC
Prior to using TextSecure, I'd use another app to play a custom sound when certain contacts would send me an SMS. TextSecure blocks this functionality, but would it be possible to incorporate a similar feature so different contacts can have different tones/vibrate patterns?

**Comment by rhodey** [comment] 2015-03-17 00:13
closing as duplicate of #213

**Closed by rhodey** 2015-03-17 00:13 UTC
Labels: feature
