### ISSUE TITLE
soft menu button not working

### ISSUE THREAD

**Issue by Joesen1** [WhisperSystems/TextSecure#2437] opened 2015-02-10 07:51 UTC
Hi all!

I have an issue with the just released version 2.5.1.
The soft menu button of my LG G2 on Android 4.2.2 isn't working anymore, so i have no access to the settings. Nothing happens on a button push!

Thanks for developing this great app!

**Comment by mcginty** [comment] 2015-02-10 22:59
@Joesen1 since I can't seem to reproduce the menu not coming up (this is related to an LG-specific ROM bug), would you be willing to run a diagnostic build of TextSecure I send you and post the logcat output?

Thanks much for posting the issue, and sorry you're running into this. Hope to get this fixed soon :)

**Comment by Joesen1** [comment] 2015-02-11 08:26
Yes, of course! Just give me a link. Thank you!

**Comment by moxie0** [comment] 2015-02-11 21:43
@mcginty Did you want to close this with #2445 or are you waiting for diagnostic APK feedback from @Joesen1 ?

**Comment by mcginty** [comment] 2015-02-11 22:25
Let's keep this open since the problem of the hardware options menu opening still exists. @Joesen1 will post an APK for you in a sec :)

**Comment by mcginty** [comment] 2015-02-12 00:08
@Joesen1 https://www.pixelapse.com/openwhispersystems/projects/signal-android/diag/TextSecure-LGE-menu-debug.apk

You shouldn't have to overwrite your existing TextSecure since I changed the package name. Instead, you'll get a second copy installed. All you should have to do is run it, skip the registration, hit the menu button, then submit a debug log which will contain a bit more information about what's happening on your device :).

**Comment by Joesen1** [comment] 2015-02-12 10:16
http://pastebin.com/zRiKQ92T
I hope that helps and i didn't clean up lines which have important information.
Btw, the issue still exists on current 2.5.2 release.

**Comment by moxie0** [comment] 2015-02-12 18:37
@Joesen1 In 2.5.2 do you see the "soft menu" in the actionbar?  It's a vertical "..." that will show you what the hardware menu button would have.

**Comment by Joesen1** [comment] 2015-02-12 21:04
@moxie0 No, soft menu isn't visible in the action bar! (2.5.2)

**Comment by mcginty** [comment] 2015-02-12 23:16
@Joesen1 2.5.3 is coming out soon with another attempted resolution. Let me know when you get that, and update if you still can't access the menu!

**Comment by Joesen1** [comment] 2015-02-13 07:23
@mcginty With 2.5.3 the soft menu button in the navigation bar is working again! Thank you!

**Closed** 2015-02-13 17:57 UTC
