### ISSUE TITLE
Replace (No subject) with (Picture)

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2402] opened 2015-01-31 10:02 UTC
If I send a photo to one of my contacts and then go to the home screen, the preview of the conversations displays a "(No subject)" string. It would be cool to display a "(Picture)" string, or even better, show the icon of a pic.

**Comment by mcginty** [comment] 2015-02-04 22:01
pretty much dupe of #1934

**Closed by mcginty** 2015-02-04 22:01 UTC
