### ISSUE TITLE
TextSecure v3.0.0 Signal

### ISSUE THREAD

**Issue by Smurph82** [WhisperSystems/TextSecure#4189] opened 2015-10-02 21:13 UTC
[Debug log](https://gist.github.com/anonymous/860bc5f7462f97d21a49)

Using a Nexus 6 with stock Android 5.1.1 the new Signal 3.0.0 does not make the secure calls. Clicking the option menu item call opens the native dialer. However my wife's S6 does make the secure calls.

**Comment by csantiviago** [comment] 2015-10-02 21:18
Mine too.

Nexus 5 with Marshmallow preview 3.

Can't make secure calls but can receive them from iOS.

Debug: https://gist.github.com/3dff9452318f3f78c4ab

**Comment by csantiviago** [comment] 2015-10-02 21:21
Please note that when I try to initiate a secure call from Android, I receive a "Server failed!" Message, but the destination keeps ringing.

**Comment by moxie0** [comment] 2015-10-02 22:03
@csantiviago Your directory will update in the next 6-12 hours, or you can do a manual pull-to-refresh on your contact list.
@csantiviago Duplicate of #4182, fixed in 3.0.1

**Closed** 2015-10-02 22:03 UTC
