### ISSUE TITLE
Old emojis show in notification

### ISSUE THREAD

**Issue by derfasthirnlosenick** [WhisperSystems/TextSecure#3625] opened 2015-07-12 05:42 UTC
The old emojis (Google) appear in the notifications, but are displayed correctly in the conversation activity and/or the quick reply.
Restart of phone didn't help.

Steps to reproduce: Get somebody to send you an emoji while you are not in the app.

**Comment by 2-4601** [comment] 2015-07-12 10:40
Duplicate of #3278.

**Closed** 2015-07-20 18:12 UTC
