### ISSUE TITLE
Wrong image in chat preview

### ISSUE THREAD

**Issue by yendar28** [WhisperSystems/TextSecure#840] opened 2014-02-27 17:58 UTC
Hello, 

when I send an image, in the chat there is shown an image I sent before instead of the right one I just have sent. When it is clicked, the right one is shown in full screen.

Even when I delete the conversation and I send a new image, the old wrong picture is shown in chat. (Fullscreen shows the right image). Does Deletion of conversation not delete data of the conversation?

Greets

**Comment by manhole11** [comment] 2015-02-01 14:50
Still present :/

**Comment by rhodey** [comment] 2015-03-10 21:05
The basics of this problem is that it is possible for both message and part IDs to be reused. `ImageSlide` has its own internal cache that is used for image previews and the index to this cache is the part URI which is derived from the part ID. `MmsDatabase` contains a `SlideDeck` cache which uses message IDs for indexes.

Potential fixes that I'm aware of:
1) migrate the `_id` columns in the `part` and `mms` tables to be `INTEGER PRIMARY KEY AUTOINCREMENT`.
2) implement proper cache expiration by expiring cache for parts and messages on insert.

Migrating the `part` and `mms` tables is not possible unless the user had enough free storage space, checking for and working around that is pretty complicated. Fixing the cache expiration should be easier but requires a refactoring of how ImageSlide and PartDatabase access cache.

**Comment by Mihahn** [comment] 2015-04-12 20:25
I notice quite the same thing on the latest version (2.11.0) on my Nexus 4 (Android 5.0.2). 
How to reproduce:
(1.? I have many images in this chat, but am not sure if this is important to reproduce)
2. Open a chat and click on 'all images'
3. Scroll down to the bottom of all the images
4. Click on any image 
5. The preview is different than the actual picture you open

If I wait a few seconds and click on the preview and go back and scroll a bit and click on it again it's the right one but not on the first/second click... I guess that's related to this issue or should I open another one? :)

**Comment by rhodey** [comment] 2015-04-13 21:48
@Mihahn haven't noticed that one before -__- could you open a new issue for that? And debug log would be much appreciated :)

I wouldn't be surprised if the cause of these issues was related but I think it is correct for them to be recorded as separate bugs.

**Comment by aurisnoctis** [comment] 2015-04-29 15:56
TextSecure version 2.12.0
I confirm preview in chat is different from actual picture

Steps to reproduce:

1. send picture in chat
2. sending fails because of bad internet reception, don't send again
3. delete message (if direct marking of erroneous message doesn't work, use workaround by marking message without error, then additionally marking erroneous message with picture that didn't get sent, then unmark message without error again)
4. wait until someone else sends a message containing a picture to me
5. see the picture I originally wanted to send as thumbnail in other person's message
6. click ("wrong") thumbnail in other person's message; full image shows correct image other person sent, but thumbnail in chat remains my own picture that never got sent in step 1)

**Comment by jawsdog** [comment] 2015-05-08 06:58
It's a little concerning that deleting an image (or message containing the image) doesn't actually delete the image immediately. If the image was removed from the cache at the time of deletion, reusing the messageId and part IDs wouldn't be an issue...if I understand the problem correctly. Has there been consideration for disabling disk caching completely? Given the nature of the app, disabling disk caching would seem to offer more pros than cons. http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/load/engine/DiskCacheStrategy.html#NONE

**Comment by rhodey** [comment] 2015-05-11 23:14
post-glide-refactor update:

I thought I'd give this bug another shot now that the `ImageSlide` cache is gone and we've moved onto using [Glide](https://github.com/bumptech/glide). As before, we are still caching bitmaps by ID (specifically a URI derived from ID) and since IDs can be reused this bug is still around. Unlike before, it no longer makes sense to expire cache on insert of new parts or mms records because Glide recycles bitmaps and we don't want to take away from that cool performance improvement.

For cache expiration, Glide has this idea of [signatures](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation) which can basically exist to decorate a key with identifying information. My thought was to decorate the bitmap key with the message send timestamp thus creating an actually unique key. However, without an sql `JOIN` parts have no associated timestamp so we still can't create a unique key.

Currently Glide gets used in two places `ConversationItem` and all images view, the latter of the two happens to have access to timestamp through the `PartDatabase.IMAGES_QUERY` but definitely not the former. If we added a timestamp to the part database and incorporated it into the part URI this issue would be resolved without having to leave `PartDatabase`, what do you think @moxie0?

**Comment by moxie0** [comment] 2015-05-12 22:56
if you're doing a schema change, is there a reason to add a timestamp column instead of an auto increment column?

**Comment by rhodey** [comment] 2015-05-12 23:08
@moxie0 nope, that's a better idea. it's not really a timestamp column as much as it is a cache key column, auto increment is the proper way to do this for sure. after the schema change I'd patch `PartDatabase` to include this cache key as a query parameter when building PDU URIs so our usage of Glide would remain unchanged (`key = Uri.toString()`).

**Comment by rhodey** [comment] 2015-05-13 00:04
@moxie0 forget that, seems sqlite only allows `AUTOINCREMENT` on columns with type `INTEGER PRIMARY KEY` https://www.sqlite.org/autoinc.html

```
Any attempt to use AUTOINCREMENT on a WITHOUT ROWID table or
on a column other than the INTEGER PRIMARY KEY column results
in an error.
```

I only discovered this after crashing TS on my DB migration alter table statement, so I'm pretty sure I'm interpreting the doc correctly. We'll have to set a value on insert, makes most sense to me to use `System.currentTimeMillis()` instead of `SecureRandom.getInstance("SHA1PRNG").nextDouble()` or something else.

**Comment by rhodey** [comment] 2015-05-13 02:24
I greatly overestimated how much work Glide is actually doing for us. the fix for this is non-trivial and better fit for our glide expert so I'm removing assignment from myself.

As far as I can tell, the only thing we're using Glide for is the recycling of bitmaps, like it keeps bitmaps around and we pass in input streams. The Glide doc talks a lot about a key value bitmap cache but we don't seem to take advantage of that. The whole [Glide signatures API](https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation#custom-cache-invalidation) doesn't apply in our use case.

@mcginty am I understanding this correctly now? after a bunch of debugging I think that we read from an input stream every time we need to set an image on a view-- so this Glide stuff is better than the static cache we had in `ImageSlide` because it recycles bitmaps, but worse because we're always reading from disk ie no actual cache.

**Comment by moxie0** [comment] 2015-05-13 21:36
@mcginty does that explain why glide seems to have made scrolling performance worse?

**Comment by rhodey** [comment] 2015-05-13 22:28
upon further inspection it seems that maybe we are getting cache from Glide. however, when I tried to mix a unique value into the Uris the problem was not resolved, I confirmed that the Uris were in fact unique via Log.d, and then noticed another strange behavior: when rotated landscape the image previews would change, when rotated portrait they'd change back.

still of the strong belief that I don't understand this so still keeping assignment off myself :|

**Closed** 2015-05-20 20:38 UTC
Labels: bug
