### ISSUE TITLE
Emojis appear dissected / cut off / stretched

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2957] opened 2015-04-12 00:27 UTC
Hello,

the Emojis randomly appear dissected / cut off / stretched on the TextSecure Emoji drawer.

It happens [regardless of the system font size](https://github.com/WhisperSystems/TextSecure/issues/2937), as you can see in the following screenshots:

System font size @ minimum:

![Image](https://cloud.githubusercontent.com/assets/7558360/7103834/727411a4-e0ba-11e4-9382-91056aab0c5e.png)

System font size @ medium:

![Image](https://cloud.githubusercontent.com/assets/7558360/7103835/7d612dcc-e0ba-11e4-9580-16cf076dba49.png)

System font size @ maximum:

![Image](https://cloud.githubusercontent.com/assets/7558360/7103837/87a1490c-e0ba-11e4-80bb-f27ac7f088a1.png)

So, I don't know what triggers it.

It actually even happened the very first time I opened the Emoji drawer after having upgraded from TextSecure 2.9.3 to TextSecure 2.10.2.

Closing TextSecure via the task manager and then reopening it seems to solve it at first, but the issue seems to randomly reappear.

Happening on LG G2 with stock 4.4.2 KitKat.

Could you please fix it?

Regards

**Comment by justinian** [comment] 2015-04-12 18:58
I get this as well on a Samsung Galaxy S6 running 5.0.2, but killing TextSecure and reopening it does not change it for me.

**Comment by agrajaghh** [comment] 2015-04-12 19:33
@justinian its not appearing randomly like this for you? You always have this distorted view?

**Comment by justinian** [comment] 2015-04-12 19:43
@agrajaghh Correct, I just switched phones and have only seen the bugged version on this phone.

Checking my old phone, a Nexus 5, it looks like the keyboard itself is providing the emoji button, and the emoji drawer there is fine. (Stock google keyboard on that phone.) On the S6, the emoji drawer is triggered from the input line, and comes up with the split/stretched images. (Samsung keyboard)

**Comment by wp9015362** [comment] 2015-04-12 19:56
@agrajaghh & @mcginty :

The issue is permanent for me as well now.

I can no longer get it right by restarting TextSecure.

I have also tried to reboot the device, but that doesn't help either.

I have not tried to uninstall and reinstall TextSecure, yet, but I also don't really want to do that [since it would apparently result in data loss](https://github.com/WhisperSystems/TextSecure/issues/2944).

> @justinian wrote:
> 
> Checking my old phone, a Nexus 5, it looks like the keyboard itself is providing the emoji button, and the emoji drawer there is fine. (Stock google keyboard on that phone.) On the S6, the emoji drawer is triggered from the input line, and comes up with the split/stretched images. (Samsung keyboard)

You need to update to TextSecure 2.10.2 to see the Emoji drawer toggle button in the message input box.

You probably are using a TextSecure version older than 2.10.x on the Nexus 5?

Regards

**Comment by justinian** [comment] 2015-04-12 20:02
@wp9015362 Ah, you're correct, I hadn't updated on the Nexus 5 yet. I updated and it looks to be working as expected on the Nexus 5, no split/stretched emoji.

**Comment by wp9015362** [comment] 2015-04-12 20:04
@justinian :

Can you trigger the issue on the Nexus 5 by changing the system font size?

**Comment by justinian** [comment] 2015-04-12 20:07
@wp9015362 Looks like I'm not able to, no. I tried several variations - not killing TextSecure, killing before switching font sizes, and killing after switching font sizes, and it continued to look correct in all cases.

**Comment by jimtoll** [comment] 2015-04-13 21:52
I am seeing this same issue on my Verizon Droid Turbo.    I tried kill the app and then restarting and the emoji drawer is still messed up.

**Comment by snue** [comment] 2015-04-18 18:00
I got the same issue on my Oppo Find 7 (Android 4.4.4, PA 4.6-BETA6).
It looks like the affected models mostly have QHD (2560x1440) display resolution (Find7, Galaxy S6, Droid Turbo).

**Comment by wp9015362** [comment] 2015-04-18 20:12
> @snue wrote:
> 
> It looks like the affected models mostly have QHD (2560x1440) display resolution

No, it's also happening at full HD (1080x1920) resolution.

**Comment by jimbudarz** [comment] 2015-05-02 17:13
This problem occurs on my LG G3 as well, which is QHD resolution.

**Comment by justinian** [comment] 2015-05-02 17:39
I have not experienced the bug on my S6 for about a week.

**Comment by vaviary** [comment] 2015-05-08 13:53
I get this issue on my LG G3, using TextSecure 2.13.0 under Android 5.0.

**Comment by sbaum** [comment] 2015-06-01 19:16
I'm experiencing the same problem on Nexus 6 after updating to TextSecure 2.16.3. The emojis are rendered faulty in the messages and in the drawer.  See attached screenshot. This is unusable... 
![tmp_5694-screenshot_2015-06-01-21-00-30-picsay82190837](https://cloud.githubusercontent.com/assets/5242678/7921010/d183dd7c-08a2-11e5-8cd0-7c1c72117c17.png)

**Comment by jimbudarz** [comment] 2015-06-01 19:30
This latest update has caused a regression for me as well.

**Comment by mcginty** [comment] 2015-06-01 21:51
Thanks so much for posting your device information, everyone. I could now reproduce it in an emulator and a fix is in PR now.

**Comment by wp9015362** [comment] 2015-06-01 22:20
Same here.

Since updating TextSecure to 2.16.3 on an LG G2 running stock Android 5.0.2 Lollipop, the Emojis now appear dissected / cut off / stretched everywhere.

Previously they only appeared dissected / cut off / stretched on the Emoji drawer.

Now they are also appearing dissected / cut off / stretched in the text input box and in the messages.

Regards

**Comment by oaim** [comment] 2015-09-04 10:02
I have this problem with TextSecure 2.26.0, Android 4.1.2, Samsung Galaxy s3 mini. Please reopen

**Comment by boehan** [comment] 2015-09-04 11:48
Same for me with TS 2.26.0, cm12, Sony Xperia P

**Closed** 2015-09-04 19:48 UTC
Labels: bug
