### ISSUE TITLE
failed group messages get sent to all again

### ISSUE THREAD

**Issue by gartenriese2** [WhisperSystems/TextSecure#3339] opened 2015-06-04 20:24 UTC
if a message in a group chat failed to be received by one of the members of the group chat and I send it again at the message info window, the message will be sent to all members of the group chat, meaning some people will get the message more than once

**Comment by agrajaghh** [comment] 2015-06-04 20:31
duplicate of #2639

**Closed** 2015-06-04 20:56 UTC
