### ISSUE TITLE
Search field finds unrelated contacts

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3065] opened 2015-04-27 07:06 UTC
I'm not sure how the search algorithm works, but when I am searching for a name, it finds all sorts of contacts. Like, even if I type "ca", it would still find contacts like "john smith", where no "ca" occurs. I've always wondered why that is. Searching contacts is *very* confusing.

**Comment by McLoo** [comment] 2015-04-27 07:42
duplicate of #1414

**Closed** 2015-04-27 07:43 UTC
