### ISSUE TITLE
Cutting off long SMS/MMS with "null"

### ISSUE THREAD

**Issue by blocman** [WhisperSystems/TextSecure#2292] opened 2015-01-04 03:58 UTC
This has happened a number of times.. but long messages get cut off with no rhyme or reason, and the word "null" is at the end of the now-cut-off message. Seems to be sms or mms. Has happened multiple times in a single conversation, or waited 3 months to happen again. 

Device info: Nexus 5, rooted stock ROM 4.4.4, Textsecure 2.3.3
debug log: https://gist.github.com/aacfab6b864770cbc53b
Note that this log was generated a couple hours after the latest instance.

**Comment by blocman** [comment] 2015-01-06 05:08
I haven't used anything other than textsecure in months, not sure if another text app would do the same. I only ever message with one person infrequently using encrypted/push/secure conversation, so the fact that this has only happened to me during regular SMS/MMS isn't exactly confirmation that it WOULDN'T happen during push/encrypted.. but so far it hasn't. 
Since I'm so wordy, in order of your questions.. Yes, no, unencrypted SMS. 

And it has happened across multiple updates of the app, including the current version.

**Comment by JasonCEC** [comment] 2015-02-05 04:54
I am also having certain long sms messages (200+ characters) truncated with the word `null` at the end. It only happens with sms messages sent to my phone by Twillio.

**Comment by rhodey** [comment] 2015-03-16 21:47
messages being truncated with `null` has been documented on the web in contexts that do not involve TextSecure, seems that the cause of this problem is not TextSecure, closing.

https://support.t-mobile.com/message/390729

**Closed by rhodey** 2015-03-16 21:47 UTC
