### ISSUE TITLE
Tapping on groupchat notifocation opens wrong conversation

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/TextSecure#3458] opened 2015-06-23 07:20 UTC
In a groupchat a person sends a message but TextSecure is locked. The notification says that this person sent a message and when I tap on it and unlock TextSecure, the conversation with this person will be displayed but not the group conversation.

**Comment by McLoo** [comment] 2015-06-23 09:57
duplicate of #3064

**Closed** 2015-06-23 10:08 UTC
