### ISSUE TITLE
picture/MMS sending problem to other users?  bug?

### ISSUE THREAD

**Issue by bigdogJW** [WhisperSystems/TextSecure#3641] opened 2015-07-13 01:40 UTC
When attaching a picture to a text and sending, the sending icon/circle remains on the picture and spins endlessly without disappearing.  Recipients sometimes do receive the picture, but the sending icon never stops spinning and wears the battery down unless it is forced to quit.  It seems to work a little better with other textsecure users, but not at all with non-textsecure users.

I notice the same behavior/problem on a Nexus 6 and HTC One M7 GPE - both with latest version of lollipop.

**Comment by jeremymasters** [comment] 2015-07-13 03:00
This is fixed in the next version when it's released, which is probably pretty soon.

**Comment by ChaoticMind** [comment] 2015-07-13 08:35
Duplicate of #3546

**Closed** 2015-07-13 21:42 UTC
