### ISSUE TITLE
Can't verify phone number

### ISSUE THREAD

**Issue by zerokes** [WhisperSystems/TextSecure#3490] opened 2015-06-29 15:36 UTC
Hi, i'm having the same issue in both RedPhone and TextSecure while verifying the phone number.
I receive the SMS "Your TextSecure verification code 821-XXX" but the app doesn't detect it since is missing the semicolon. I'm running Cyanogenmod hammerhead build and i'm in Argentina.
Logs:
 W/SMSListener( 6204): Got broadcast...
W/SMSListener( 6204): Got SMS message...
V/Mms     ( 7267): onStart: #2 resultCode: -1 = Activity.RESULT_OK
W/SMSProcessor( 6204): Not a verifier challenge...
W/SMSListener( 6507): Got SMS broadcast...
V/BlacklistProvider( 2965): Query uri=content://blacklist/bynumber/%2B541157251897, match=2
D/Mms     ( 7267): cancelNotification

Regards,
Joaquín

**Comment by moxie0** [comment] 2015-06-29 15:59
Does your mobile provider remove colons or something?

**Comment by zerokes** [comment] 2015-06-29 16:52
I can send colons and semi colons from another phone so I guess it doesn't.

**Comment by zerokes** [comment] 2015-06-29 18:03
Well, changing the mobile provider seems to work. Perhaps it removes semicolon from some numbers and not from others? Anyways, I got it working using another number. Thanks.

**Comment by rhodey** [comment] 2015-07-06 20:56
closing this as strange, unable to reproduce, hopefully wont-see-again-weirdness.

**Comment by rhodey** [comment] 2015-07-06 20:57
@zerokes for historical purposes, could you let us know what mobile provider you were using when you experienced this issue?

**Closed by rhodey** 2015-07-06 20:56 UTC

**Comment by zerokes** [comment] 2015-07-06 21:01
The mobile provider is called Tuenti.
