### ISSUE TITLE
Quick reply / emojis UI issue: keyboard moves to quick reply screen upon tapping emoji entry icon

### ISSUE THREAD

**Issue by saltthefries** [WhisperSystems/TextSecure#3594] opened 2015-07-09 22:46 UTC
This is a minor UI bug in the quick reply screen:
Version: TextSecure 2.21.0
Device: LG Nexus 5 / Hammerhead
Android version: 5.1.1 (stock, not rooted or otherwise modified)
Keyboard: Google (stock)

Issue: shown in screenshot - emoji selection takes up the quick reply screen
Steps to recreate: Tap reply in push notification, tap the emoji face in the "Send TextSecure Message" box
Workaround: press back button, returns keyboard to bottom of screen and text entry

![screenshot_2015-07-09-09-12-42-red](https://cloud.githubusercontent.com/assets/7686346/8608453/ef0d6334-264f-11e5-8657-fe29bba683fa.png)

Than you all so much for making a great crypto app that doesn't require users to be technical experts! Let me know if you need more screenshots or details.

**Comment by moxie0** [comment] 2015-07-10 01:30
duplicate of #3485

**Closed by moxie0** 2015-07-10 01:30 UTC
