### ISSUE TITLE
Bug - cannot forward message with phone numbers

### ISSUE THREAD

**Issue by edent** [WhisperSystems/TextSecure#1215] opened 2014-03-22 07:23 UTC
* Long press on a message containing a link / phone number.
* Click "forward".
* Actual result - uses the text from the most recent message - not the one that I have selected.
* Expected result - use the message I have selected.

Take this example:
![screenshot_2014-03-22-06-03-20](https://f.cloud.github.com/assets/837136/2490107/bfcce3bc-b191-11e3-91e7-6f5cac54154b.png)
If I long press on "Join LOL Chat" and select "forward" TextSecure uses the message text from the last SMS ("DFS").  The same happens if I try to select "Opera Thursdays" - the "DFS" message is the one which is forwarded.

This happens whether I'm the recipient or whether I'm the sender.

If I send a message saying "Alice's phone number is +447700900289" I am then unable to select that message for forwarding *if* there is another message sent or received after it.

Hope that makes sense.  I just want the message I long press to be the one which gets forwarded :-)

**Comment by mcginty** [comment] 2015-03-10 19:10
dupe of bug prohibiting long-clicking a url

**Closed by mcginty** 2015-03-10 19:10 UTC
