### ISSUE TITLE
problems with nondefault textsecure

### ISSUE THREAD

**Issue by karlhedderich** [WhisperSystems/TextSecure#2090] opened 2014-11-12 14:50 UTC
I have two friends who both say that when textsecure is not set to be the default messenger it will intercept normal group messages.  Both friends do use non standard texting apps as the default.  Does anyone know if this behavior happens when textsecure isn't the default and the standard messaging app is the default?

**Comment by riyapenn** [comment] 2015-09-24 23:18
Dupe of https://github.com/WhisperSystems/TextSecure/issues/1931

**Closed** 2015-09-25 00:05 UTC
Labels: mms
