### ISSUE TITLE
Multiple Audible Notifications for Single Message

### ISSUE THREAD

**Issue by nwdev** [WhisperSystems/TextSecure#2310] opened 2015-01-08 18:09 UTC
For some reason lately upon receiving a message my device will give two audible notifications for a single message, meaning the Incoming text sound happens twice.

This happens on both devices I own that have TextSecure installed.

**Comment by jeremymasters** [comment] 2015-01-08 18:55
I am currently experiencing the same thing.

**Comment by bisam** [comment] 2015-01-16 12:00
Same here, but it seems you can fix it by setting the alarm to silent and after that switching back to whatever ringtone you chose...

**Comment by manhole11** [comment] 2015-02-17 08:05
Same here. Sounds twice or vibrates twice.

**Comment by rhodey** [comment] 2015-03-13 21:07
are any of you able to reproduce this reliably? can you provide steps?

**Comment by rhodey** [comment] 2015-03-13 22:47
seems to be a duplicate of #2148, moving discussion to there.

**Closed by rhodey** 2015-03-13 22:47 UTC
