### ISSUE TITLE
Unable to upgrade or install due to "invalid package" error 

### ISSUE THREAD

**Issue by mnahkola** [WhisperSystems/TextSecure#2881] opened 2015-04-03 19:50 UTC
For some reason it's apparently not uncommon to get the generally well-known "invalid package" error ONLY with TextSecure, recently.

I can seemingly install/update any other applications marked as compatible in the Google Play Store (that I've tried so far) on my devices just fine.

Both myself and another user have reported this on support.whispersystems.com, in http://support.whispersystems.org/customer/portal/questions/11557972-version-mismatch-messages-unreadable-with-automatic-updates-from-google-play-at-both-ends and http://support.whispersystems.org/customer/portal/questions/11567106-invalid-package-error-on-install .

I have three Android 2.3.x devices exhibiting this behaviour, two Samsung GT-S5690 and one HTC Desire HD A9191, with latest updates applied to each.
Android 2.3.6 / GINGERBREAD.XXNA1 on the S5690s
Android 2.3.5 / 3.12.405.1 on the A9191.

User "DM4N" only reported "HTC Desire HD" and "latest updates", I don't know if there exist different variants of this model name.

My main phone is still running a 2.5 series TextSecure due to this. Wife's on 2.9.3 as of today, she has a newer phone with a 4.something Android...

**Comment by moxie0** [comment] 2015-04-03 21:51
Thanks, duplicate of #2753. Should be fixed in 2.10.0 that's in beta right now.

**Closed by moxie0** 2015-04-03 21:51 UTC
