### ISSUE TITLE
Attaching/Sending contact info should attach a contact record, rather than a number

### ISSUE THREAD

**Issue by Hooloovoo** [WhisperSystems/TextSecure#4205] opened 2015-10-04 21:03 UTC
Using Signal 3.0.1 (beta) for Android on a Nexus 5. Debug log (though I doubt you'll want it) is https://gist.github.com/526f0bbf1de80801e008

On WhatsApp, when I attach a contact, it brings up the contact's record with checkboxes next to each item of information that you have for him/her (e.g. numbers and email addresses) and you can choose which you want to include. You then click send and it sends them all together as a record, formatted specially. Clicking on it in the WhatsApp chat then allows you to add that information to your contacts (giving you the option to add it to an existing contact, or create a new contact, as is normal for receiving a contact). It also has a clever little message icon under the contact record that allows you to send a WhatsApp message to that contact straight away without adding them to your address book.

The interface in Signal is much less developed. When you select attaching contact information on the same contact, it only shows me the phone numbers for the contact (rather than the email addresses) and selecting one just inserts the number alone (with no name or formatting). I would like to see Signal send a proper contact record with a similar flow to that described above for WhatsApp, at least if the recipient is also a Signal/TextSecure user and the message is being sent over the data channel.

**Comment by mcginty** [comment] 2015-10-06 15:59
closing as dupe of #535, since both as sending and receiving requires vcard support which android doesn't give us for free.

**Closed by mcginty** 2015-10-06 15:59 UTC
