### ISSUE TITLE
New message notifications shown whenever TextSecure is locked, no messages received when opened.

### ISSUE THREAD

**Issue by joshproehl** [WhisperSystems/TextSecure#3444] opened 2015-06-19 15:48 UTC
(Creating new story from thread in #970)

I'm seeing an alert that I have two new messages whenever TS is *locked*. Upon unlocking no message is received, and the alert disappears, but when TS is re-locked I once again get an alert for two "Encrypted Message". (There are two messages from this contact that were sent to me but which I have still never received. This problem began immediately after these were sent.)

I've uploaded a [capture from logcat -v long](https://gist.github.com/joshproehl/e07c3f2008307ca11f96) while locking and unlocking to reproduce this.

This problem has been ongoing for a week now. Re-initiating secure session does not help, restarting the phone does not help. Currently using the latest Play Store version: 2.18.2.

**Comment by Mihahn** [comment] 2015-06-19 15:54
This is a duplicate of #2287 #2221 #2522 #2404 just to mention a few of them... But I have the same problem since the f...ing missing comma bug... :disappointed:

**Comment by McLoo** [comment] 2015-06-20 14:35
@Mihahn maybe a duplicate. But the mentioned issues should be fixed.

**Comment by joshproehl** [comment] 2015-06-23 22:46
Some of the linked issues mention that the notification is "Incorrect, because I have already read all the messages"

Just clarifying that in this case I *know* that I did not receive the messages from the sender. In their history there are two messages which were sent just before this began, which do NOT appear in my history. (So besides the phantom notifications, I'm actually missing messages as well.)

**Comment by moxie0** [comment] 2015-06-23 23:45
I finally figured out what's causing this, fix is non-trivial but I'll try to get it in soon.

**Comment by Mihahn** [comment] 2015-06-27 13:00
This is solved for me in TS 2.20.0 :+1:

**Comment by moxie0** [comment] 2015-06-27 22:02
Oh yeah forgot to tag this. c920146bff9bba9f71adcf0a2ade6472e42dc246

**Closed by moxie0** 2015-06-27 22:02 UTC
