### ISSUE TITLE
Feature request: pre-populate the "Your Phone Number" dialog at install time

### ISSUE THREAD

**Issue by mx4** [WhisperSystems/TextSecure#904] opened 2014-03-01 13:34 UTC
When someone first launches the app, he quickly gets to the dialog "Connect with TextSecure". That dialog asks for:
 - your country,
 - your country code and phone number.

It would be great if:
- if we got rid of the "country" or "country code". One of the 2 should be enough.
- these could be automatically populated so that one just needed to confirm that these were correct. I believe that Android provides a way to query for the local phone number.

**Comment by rhodey** [comment] 2015-03-16 19:52
the phone number field should be populated automatically, if this is not happening it is a bug. any updates @phenx-de, @mx4

**Comment by rhodey** [comment] 2015-03-16 20:09
closing as duplicate of #779

**Closed by rhodey** 2015-03-16 20:09 UTC
Labels: bug
