### ISSUE TITLE
Increase text input box size as message grows

### ISSUE THREAD

**Issue by aibaraiduas** [WhisperSystems/TextSecure#3125] opened 2015-05-08 00:26 UTC
When typing a message longer than a single line, TextSecure allows the user to scroll the input box left and right in order to see the whole input.

It would be nice if instead of this scrolling function the box simply gained another line as the length of the message increased. This would allow the user to always see the entire message without scrolling. 

While this would take up slightly more vertical space, this would be especially useful when reviewing the message before sending (say, to make sure nothing was autocorrected incorrectly). Plus, TextSecure already increases the input area, though only to show the number of characters when they go past the 160 character mark. 

Thanks.

**Comment by 2-4601** [comment] 2015-05-08 01:18
By the power of Grayskull duplicate of #2899

**Closed** 2015-05-08 03:16 UTC
