### ISSUE TITLE
Group message reports error if it fails to deliver to one group member

### ISSUE THREAD

**Issue by gladiac** [WhisperSystems/TextSecure#2747] opened 2015-03-22 11:02 UTC
Hello,

If you send a group message and a member of the group is not valid, is fails with an error but doesn't show any details. The message has a "flag" Tap for details. I guess it shows the users it has the message delivered to but not the error.

The log shows:

```
W/PushReceiveJob( 5086): Received receipt: (XXXXX, 1427021453000)
W/MmsDatabase( 5086): org.whispersystems.textsecure.api.util.InvalidNumberException: No valid characters found.
W/MmsDatabase( 5086): 	at org.whispersystems.textsecure.api.util.PhoneNumberFormatter.formatNumber(PhoneNumberFormatter.java:82)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.util.Util.canonicalizeNumber(Util.java:141)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.util.Util.canonicalizeNumberOrGroup(Util.java:148)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.database.MmsDatabase.incrementDeliveryReceiptCount(MmsDatabase.java:230)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.database.MmsSmsDatabase.incrementDeliveryReceiptCount(MmsSmsDatabase.java:139)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.jobs.PushReceiveJob.handleReceipt(PushReceiveJob.java:92)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.jobs.PushReceiveJob.handle(PushReceiveJob.java:73)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.service.MessageRetrievalService$1.onMessage(MessageRetrievalService.java:89)
W/MmsDatabase( 5086): 	at org.whispersystems.textsecure.api.TextSecureMessagePipe.read(TextSecureMessagePipe.java:80)
W/MmsDatabase( 5086): 	at org.thoughtcrime.securesms.service.MessageRetrievalService.run(MessageRetrievalService.java:82)
W/MmsDatabase( 5086): 	at java.lang.Thread.run(Thread.java:841)
W/MmsSmsDatabase( 5086): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 3) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 3) ORDER BY date_received ASC)
W/MessageRetrievalService( 5086): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService( 5086): Reading message...
W/TextSecureMessageSender( 5086): org.whispersystems.textsecure.api.push.exceptions.UnregisteredUserException: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:243)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessage(TextSecureMessageSender.java:322)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.getEncryptedMessages(TextSecureMessageSender.java:304)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:244)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:221)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:149)
W/TextSecureMessageSender( 5086): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.deliver(PushGroupSendJob.java:159)
W/TextSecureMessageSender( 5086): 	at org.thoughtcrime.securesms.jobs.PushGroupSendJob.onSend(PushGroupSendJob.java:81)
W/TextSecureMessageSender( 5086): 	at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
W/TextSecureMessageSender( 5086): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/TextSecureMessageSender( 5086): Caused by: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:460)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:423)
W/TextSecureMessageSender( 5086): 	at org.whispersystems.textsecure.internal.push.PushServiceSocket.getPreKeys(PushServiceSocket.java:212)
W/TextSecureMessageSender( 5086): 	... 11 more
```

**Comment by gladiac** [comment] 2015-03-22 11:16
I can provide more details, but I don't want to post phone numbers here which are part of the log. Contact me via email with your gpg key if you need the full log. Key and mail at https://cryptomilk.org

**Comment by gladiac** [comment] 2015-03-27 14:23
This happens also with TextSecure 2.9.0. I don't really understand why you labeled this UX. It reports it could not deliver the message but all people in the group got the message.

**Comment by rmueller83** [comment] 2015-03-28 16:00
See https://github.com/WhisperSystems/TextSecure/issues/2408

**Comment by gladiac** [comment] 2015-04-22 11:31
Ping!

**Comment by mammuth** [comment] 2015-10-30 10:18
Related to (and probably duplicate of) #2408

**Closed** 2015-11-02 22:43 UTC
Labels: ux
