### ISSUE TITLE
crash in 2.14

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3129] opened 2015-05-08 03:41 UTC
Whenever I try to open a conversation with one of my contacts (always the same one) and scroll up a bit I get a crash.  https://gist.github.com/c01e82308ff25e8d35e8

**Comment by volcano99** [comment] 2015-05-08 03:43
May be related to #3128

**Comment by mcginty** [comment] 2015-05-08 04:10
dupe of #3127

**Closed by mcginty** 2015-05-08 04:10 UTC
