### ISSUE TITLE
Communicationg is with some persons not possible anymore (Key Exchange failing)

### ISSUE THREAD

**Issue by mr-gosh** [WhisperSystems/TextSecure#2018] opened 2014-10-20 09:28 UTC
We have a group of Contacts - but some can't see the messages of some others anymore - once it was working.

So if I write to the group, I get immediately a response of the problematic person that looks like a key exchange - but itg cant be clicked or anything:

![screenshot_2014-10-20-11-15-25](https://cloud.githubusercontent.com/assets/3028703/4698971/54dcef2e-583b-11e4-8ec1-b8eacfd7f689.png)

If I directrly Contact that person it even looks stranger:

![screenshot_2014-10-20-11-15-40](https://cloud.githubusercontent.com/assets/3028703/4698975/632a1822-583b-11e4-9b6c-4ce5f1c61545.png)

Nothing can be activated here... :(

others can communicate with him...

**Comment by asdil12** [comment] 2015-01-07 12:01
So this issue seems to be about having a group where one user got a new key.
All group members will get an error message when posting to the group (but the msg will still be delivered), and a key verification message (with the group itself as the sender).
Accepting that key won't work (that is IMHO a bug) and there is no indication which user caused the issue (that is even worse).

To fix the issue you will need to find out, which user is causing the issue.
Then you can:
- Ask all users in the group to send a private msg to that user and perform the key exchange
- Ask the user that causes the issue to send a msg to the group. For me this triggered a private key exchange between this user and all other users. This might show up as a private dialog for the users where they need to accept the new key.

**Comment by mr-gosh** [comment] 2015-01-15 10:23
That sums everything up right!

**Comment by patzi** [comment] 2015-01-22 12:15
I had the same problem today.
My message got a green background and it was stated it was send via MMS. Almost all users got the message some got it two or even more times. One got nothing.
After i figured out witch user was the cause, I wrote that user a message, I had no direct chat to that user before.
I first got again an error, saying that there was a significant change in the key.
I checked to trust it. And could than send a direct message to that user.
Now i can use the group chat again and don't get weired errors.
Sadly I have no log anymore.

**Comment by McLoo** [comment] 2015-01-22 13:42
what @patzi pointed out seems to be related to #1882

**Comment by manhole11** [comment] 2015-02-10 17:33
My contacts are having the same problem as described by Fanch3n, with the only difference that we haven't found a fix. Plus whatever group I create they get this error, so deleting/creating a new group didn't work either. This is very annoying. Plus group chat isn't even that fast, and this is discouraging my friends a lot.

**Comment by rhodey** [comment] 2015-04-10 18:43
commit b9f4fba98ae4f3da3c6232599fdce4ad123185a2 and others more recent should have improved key verification / conflict flow for group messages greatly. closing for now as resolved, please reply if you still experience this issue while using an updated version of TS, thanks :D

**Closed by rhodey** 2015-04-10 18:43 UTC
