### ISSUE TITLE
Completely disable SMS sending

### ISSUE THREAD

**Issue by legovini** [WhisperSystems/TextSecure#3987] opened 2015-08-26 21:45 UTC
As I don't use TextSecure for sending or receiving SMS messages, I would like to be able to completely disable this functionality. In this way I won't be allowed to send unencrypted messages using TextSecure, not even by error.

Currently if I long press the send button, or if I specify a phone number that is not using TextSecure, I am allowed to send a plain text SMS. Especially in the latter case it is not immediate to realize that this is happening.

I think that the average user expects to disable any kind of SMS operation when setting "SMS and MMS" to Off.

Thanks!

**Comment by BrokenPhysics** [comment] 2015-08-31 08:53
This looks like a duplicate of #2161.

Would be nice to have this, though.

**Closed** 2015-08-31 15:09 UTC
