### ISSUE TITLE
Image database

### ISSUE THREAD

**Issue by alex42ka** [WhisperSystems/TextSecure#2499] opened 2015-02-19 12:01 UTC
I had some problems with the MMS settings of my provider so I tried some of the settings of TextSecure. 
Thereby I discovered that when I'm deleting an MMS (a picture) I wanted to send and receiving a message with an included picture,TextSecure shows me the deleted picture in the stream.  Clicking on the image opens the right image.

**Comment by agrajaghh** [comment] 2015-02-19 12:19
seems like a duplicate of #840

**Closed** 2015-02-19 19:18 UTC
