### ISSUE TITLE
Core concept, TextSecure Identity

### ISSUE THREAD

**Issue by johnrandolph** [WhisperSystems/TextSecure#2992] opened 2015-04-15 15:33 UTC
Hi TextSecure volunteers,

thanks for your work. 

since moving to an IP-based protocol I have wished I could leave my phone number entirely behind and use an alternative identity uid/token for myself.  phone numbers themselves are a private token that users may wish to not reveal.

is this something that is being considered? it would be fine if TextSecure refused to handle conventional sms/mms in this configuration.

**Comment by agrajaghh** [comment] 2015-04-15 16:16
duplicate of #1085

**Closed** 2015-04-15 16:36 UTC
