### ISSUE TITLE
"411 Length Required" response from server crash application

### ISSUE THREAD

**Issue by romuald** [WhisperSystems/TextSecure#3829] opened 2015-07-28 09:33 UTC
TextSecure application is currently unusable due to a crash that seems related to an unhandled exception in a communication with WhisperSystem servers.

Here is the traceback from logcat:

```
07-28 11:13:32.904    9317-9343/? W/PushServiceSocket﹕ Push service URL: https://textsecure-service.whispersystems.org
07-28 11:13:32.904    9317-9343/? W/PushServiceSocket﹕ Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+336999
07-28 11:13:32.916    9317-9366/? W/BitmapUtil﹕ rough scale 375x377 => 375x377
07-28 11:13:32.916    9317-9366/? W/BitmapUtil﹕ fine scale 375x377 => 191x192
07-28 11:13:32.932    9317-9366/? W/BitmapUtil﹕ rough scale 720x720 => 360x360
07-28 11:13:32.932    9317-9366/? W/BitmapUtil﹕ fine scale 360x360 => 192x192
07-28 11:13:32.985    9317-9369/? W/WebSocketConnection﹕ onConnected()
07-28 11:13:33.185    9317-9343/? W/PushServiceSocket﹕ PUT  --  {"destination":"+336999","messages":[{"body":"Iwj****=","content":null,"destinationDeviceId":1,"destinationRegistrationId":0,"type":3}],"relay":"cyanogen","timestamp":1438074366771}
07-28 11:13:33.589    9317-9343/? W/JsonUtil﹕ com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: <html>
    <head><title>411 Length Required</title></head>
    <body bgcolor="white">
    <center><h1>411 Length Required</h1></center>
    <hr><center>nginx/1.1.19</center>
    </body>
    </html>
    ; line: 1, column: 2]
            at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
            at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1462)
            at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
            at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576)
            at org.whispersystems.textsecure.internal.util.JsonUtil.fromJson(JsonUtil.java:41)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:523)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:465)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:169)
            at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:300)
            at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:123)
            at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:115)
            at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:62)
            at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
            at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
            at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
            at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
07-28 11:13:33.590    9317-9343/? W/JobConsumer﹕ org.whispersystems.textsecure.internal.util.JsonUtil$JsonParseException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: <html>
    <head><title>411 Length Required</title></head>
    <body bgcolor="white">
    <center><h1>411 Length Required</h1></center>
    <hr><center>nginx/1.1.19</center>
    </body>
    </html>
    ; line: 1, column: 2]
            at org.whispersystems.textsecure.internal.util.JsonUtil.fromJson(JsonUtil.java:44)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:523)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:465)
            at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:169)
            at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:300)
            at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:123)
            at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:115)
            at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:62)
            at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:40)
            at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
            at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
            at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
     Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
            at [Source: <html>
    <head><title>411 Length Required</title></head>
    <body bgcolor="white">
    <center><h1>411 Length Required</h1></center>
    <hr><center>nginx/1.1.19</center>
    </body>
    </html>
    ; line: 1, column: 2]
            at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
            at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
            at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1462)
            at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
            at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3600)
            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3545)
            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576)
            at org.whispersystems.textsecure.internal.util.JsonUtil.fromJson(JsonUtil.java:41)
            ... 11 more
```

**Comment by aegiap** [comment] 2015-07-29 15:34
TextSecure notification show a day later that a sending message reach a timeout. The application is now starting without any crash.

**Comment by moxie0** [comment] 2015-07-29 19:51
duplicate of #3827

**Closed by moxie0** 2015-07-29 19:51 UTC
