### ISSUE TITLE
MMS forward broken

### ISSUE THREAD

**Issue by rkula10** [WhisperSystems/TextSecure#1914] opened 2014-09-14 08:28 UTC
When I choose forward on a picture message the recipient list appears, but after choosing a person, the message text will be in the new message but not the picture. Ive tried on several occasions. Is this intended behavior?
Samsung Galaxy S4 on Sprint.

**Comment by rhodey** [comment] 2015-03-12 23:44
dupe of #1362, thanks for reporting though :) hopefully we'll have this resolved soon.

**Closed by rhodey** 2015-03-12 23:44 UTC
