### ISSUE TITLE
MMS Issue

### ISSUE THREAD

**Issue by Ste4thOverride** [WhisperSystems/TextSecure#3542] opened 2015-07-07 03:30 UTC
After sending an MMS to a contact I get a continuous spinning white circle on the image even though the message has been sent and the recipient has received the message.

**Comment by rhodey** [comment] 2015-07-07 18:06
@Ste4thOverride just to clarify, was this an actual old-school MMS to a non TextSecure user or a TextSecure message containing media to another TextSecure user?

our terminology is weird 0.o

**Comment by mcginty** [comment] 2015-07-08 19:56
closing as dupe of #3546

**Closed by mcginty** 2015-07-08 19:56 UTC
Labels: bug, mms
