### ISSUE TITLE
Received picture not centered

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2403] opened 2015-01-31 10:08 UTC
Hi, I'm testing the "conflicts-ui" branch. It has the new design, which I like, but I've noticed a "bug".
A friend of mine sent me a picture, ant it is not displayed in the center of the message bubble. It's aligned on the left side, leaving a lot of blank space on the right. It's not a big deal, but you know, you want things to be symmetrical...

**Comment by rhodey** [comment] 2015-03-13 20:12
hey @manhole11, trying to reproduce this but looks like it has been since resolved in master. let me know if you're still having this issue and I will re-open, thanks! :)

**Closed by rhodey** 2015-03-13 20:12 UTC
